package net.concini.sbebuddy.generator.corpus;

import static net.concini.sbebuddy.generator.Annotated.JavaPrimitive.FLOAT;
import static net.concini.sbebuddy.generator.Annotated.JavaPrimitive.INT;
import static net.concini.sbebuddy.generator.Annotated.JavaPrimitive.LONG;
import static net.concini.sbebuddy.generator.Fixtures.annotatedField;
import static net.concini.sbebuddy.generator.Fixtures.annotatedMessage;
import static net.concini.sbebuddy.generator.Fixtures.annotatedSchema;
import static net.concini.sbebuddy.generator.Fixtures.boxed;
import static net.concini.sbebuddy.generator.Fixtures.field;
import static net.concini.sbebuddy.generator.Fixtures.message;
import static net.concini.sbebuddy.generator.Fixtures.messageHeader;
import static net.concini.sbebuddy.generator.Fixtures.messageSchema;
import static net.concini.sbebuddy.generator.Fixtures.primitive;
import static uk.co.real_logic.sbe.xml.Presence.OPTIONAL;

import net.concini.sbebuddy.generator.Annotated;
import net.concini.sbebuddy.generator.Schema;

/**
 * A message grown over two schema versions under a baseline that retired the
 * first: the field appended in version 1 is a plain primitive again, the
 * required one appended in version 2 is boxed because a version 1 message lacks
 * it, and the optional one is boxed as any optional field is.
 */
final class AddedFields {

	static final String PACKAGE_INFO = """
			@SbeSchema(id = 1, version = 2, baselineVersion = 1)
			package corpus.addedfields;

			import net.concini.sbebuddy.SbeSchema;
			""";

	static final String SOURCE = """
			package corpus.addedfields;

			import static net.concini.sbebuddy.Presence.OPTIONAL;

			import net.concini.sbebuddy.SbeField;
			import net.concini.sbebuddy.SbeMessage;

			@SbeMessage(id = 1)
			record AddedFields(
					@SbeField(id = 1) long orderId,
					@SbeField(id = 2, sinceVersion = 1) int quantity,
					@SbeField(id = 3, sinceVersion = 2) Integer filled,
					@SbeField(id = 4, sinceVersion = 2, presence = OPTIONAL) Float ratio
			) {
			}
			""";

	static final String XML = """
			<?xml version="1.0" encoding="UTF-8"?>
			<sbe:messageSchema xmlns:sbe="http://fixprotocol.io/2016/sbe" package="corpus.addedfields" id="1" version="2">
			    <types>
			        <composite name="messageHeader">
			            <type name="blockLength" primitiveType="uint16"/>
			            <type name="templateId" primitiveType="uint16"/>
			            <type name="schemaId" primitiveType="uint16"/>
			            <type name="version" primitiveType="uint16"/>
			        </composite>
			    </types>
			    <sbe:message name="AddedFields" id="1">
			        <field name="orderId" id="1" type="int64"/>
			        <field name="quantity" id="2" type="int32" sinceVersion="1"/>
			        <field name="filled" id="3" type="int32" sinceVersion="2"/>
			        <field name="ratio" id="4" type="float" presence="optional" sinceVersion="2"/>
			    </sbe:message>
			</sbe:messageSchema>
			""";

	/**
	 * What the codec must be under a baseline: a message below it refused, a
	 * required field above it null below the acting version and refused as null on
	 * the way out, an optional one on the null value as ever.
	 */
	static final String CODEC = """
			package corpus.addedfields;

			/** Generated by sbe-buddy from the schema of this package; do not edit. */
			@javax.annotation.processing.Generated("net.concini.sbebuddy")
			public final class AddedFieldsCodec implements net.concini.sbebuddy.Codec<corpus.addedfields.AddedFields> {

				private final corpus.addedfields.sbe.MessageHeaderEncoder headerEncoder = new corpus.addedfields.sbe.MessageHeaderEncoder();
				private final corpus.addedfields.sbe.MessageHeaderDecoder headerDecoder = new corpus.addedfields.sbe.MessageHeaderDecoder();
				private final corpus.addedfields.sbe.AddedFieldsEncoder encoder = new corpus.addedfields.sbe.AddedFieldsEncoder();
				private final corpus.addedfields.sbe.AddedFieldsDecoder decoder = new corpus.addedfields.sbe.AddedFieldsDecoder();
				private int lastDecodedLength;

				public AddedFieldsCodec() {
				}

				@Override
				public int encodedLength(corpus.addedfields.AddedFields value) {
					return corpus.addedfields.sbe.MessageHeaderEncoder.ENCODED_LENGTH + corpus.addedfields.sbe.AddedFieldsEncoder.BLOCK_LENGTH;
				}

				@Override
				public int encode(corpus.addedfields.AddedFields value, org.agrona.MutableDirectBuffer buffer, int offset) {
					encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
					encoder.orderId(value.orderId());
					encoder.quantity(value.quantity());
					if (value.filled() == null) {
						throw new IllegalArgumentException("filled is required");
					}
					encoder.filled(value.filled());
					encoder.ratio(value.ratio() == null ? corpus.addedfields.sbe.AddedFieldsEncoder.ratioNullValue() : value.ratio());
					return corpus.addedfields.sbe.MessageHeaderEncoder.ENCODED_LENGTH + encoder.encodedLength();
				}

				@Override
				public corpus.addedfields.AddedFields decode(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					if (headerDecoder.schemaId() != corpus.addedfields.sbe.AddedFieldsDecoder.SCHEMA_ID
							|| headerDecoder.templateId() != corpus.addedfields.sbe.AddedFieldsDecoder.TEMPLATE_ID) {
						throw new IllegalArgumentException(
								"not a AddedFields: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
					}
					if (headerDecoder.version() < 1) {
						throw new IllegalArgumentException(
								"AddedFields version " + headerDecoder.version() + " is below the baseline 1");
					}
					decoder.wrap(buffer, offset + corpus.addedfields.sbe.MessageHeaderDecoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
					corpus.addedfields.AddedFields value = new corpus.addedfields.AddedFields(
							decoder.orderId(),
							decoder.quantity(),
							decoder.actingVersion() < corpus.addedfields.sbe.AddedFieldsDecoder.filledSinceVersion() ? null : decoder.filled(),
							Float.compare(decoder.ratio(), corpus.addedfields.sbe.AddedFieldsDecoder.ratioNullValue()) == 0 ? null : decoder.ratio()
					);
					lastDecodedLength = corpus.addedfields.sbe.MessageHeaderDecoder.ENCODED_LENGTH + decoder.encodedLength();
					return value;
				}

				@Override
				public int lastDecodedLength() {
					return lastDecodedLength;
				}

				@Override
				public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					return corpus.addedfields.sbe.MessageHeaderDecoder.ENCODED_LENGTH + headerDecoder.blockLength();
				}
			}
			""";

	private AddedFields() {
	}

	static Schema schema() {
		return messageSchema("corpus.addedfields", 1, 2)
				.types(messageHeader())
				.messages(
						message("AddedFields", 1).fields(
								field("orderId", 1, "int64"),
								field("quantity", 2, "int32").sinceVersion(1),
								field("filled", 3, "int32").sinceVersion(2),
								field("ratio", 4, "float").presence(OPTIONAL).sinceVersion(2)
						)
				)
				.build();
	}

	static Annotated annotated() {
		return annotatedSchema("corpus.addedfields", 1, 2)
				.baselineVersion(1)
				.messages(
						annotatedMessage("AddedFields", 1).components(
								annotatedField("orderId", 1, primitive(LONG)),
								annotatedField("quantity", 2, primitive(INT)).sinceVersion(1),
								annotatedField("filled", 3, boxed(INT)).sinceVersion(2),
								annotatedField("ratio", 4, boxed(FLOAT)).presence(OPTIONAL).sinceVersion(2)
						)
				)
				.build();
	}
}
