package net.concini.sbebuddy.generator.corpus;

import static net.concini.sbebuddy.generator.Annotated.JavaPrimitive.INT;
import static net.concini.sbebuddy.generator.Annotated.JavaPrimitive.SHORT;
import static net.concini.sbebuddy.generator.Fixtures.annotatedField;
import static net.concini.sbebuddy.generator.Fixtures.annotatedMessage;
import static net.concini.sbebuddy.generator.Fixtures.annotatedSchema;
import static net.concini.sbebuddy.generator.Fixtures.annotatedType;
import static net.concini.sbebuddy.generator.Fixtures.array;
import static net.concini.sbebuddy.generator.Fixtures.bytes;
import static net.concini.sbebuddy.generator.Fixtures.field;
import static net.concini.sbebuddy.generator.Fixtures.message;
import static net.concini.sbebuddy.generator.Fixtures.messageHeader;
import static net.concini.sbebuddy.generator.Fixtures.messageSchema;
import static net.concini.sbebuddy.generator.Fixtures.type;
import static uk.co.real_logic.sbe.PrimitiveType.INT16;
import static uk.co.real_logic.sbe.PrimitiveType.INT32;
import static uk.co.real_logic.sbe.PrimitiveType.UINT8;

import net.concini.sbebuddy.generator.Annotated;
import net.concini.sbebuddy.generator.Fixtures.AnnotatedTypeBuilder;
import net.concini.sbebuddy.generator.Schema;

/**
 * Fixed-length arrays of a primitive other than char, which is a string, not an
 * array: bytes through the bulk accessors, the rest by index.
 */
final class Arrays {

	static final String PACKAGE_INFO = """
			@SbeSchema(id = 1, version = 0)
			package corpus.arrays;

			import net.concini.sbebuddy.SbeSchema;
			""";

	static final String SOURCE = """
			package corpus.arrays;

			import static net.concini.sbebuddy.PrimitiveType.INT16;
			import static net.concini.sbebuddy.PrimitiveType.INT32;
			import static net.concini.sbebuddy.PrimitiveType.UINT8;

			import net.concini.sbebuddy.SbeField;
			import net.concini.sbebuddy.SbeMessage;
			import net.concini.sbebuddy.SbeType;

			@SbeType(primitiveType = UINT8, length = 3)
			final class Rgb {
			}

			@SbeType(primitiveType = INT32, length = 4, description = "Four readings, oldest first")
			final class Samples {
			}

			@SbeType(primitiveType = INT16, length = 2)
			final class Bounds {
			}

			@SbeMessage(id = 1)
			record Arrays(
					@SbeField(id = 1, type = Rgb.class) byte[] colour,
					@SbeField(id = 2, type = Samples.class) int[] samples,
					@SbeField(id = 3, type = Bounds.class) short[] bounds
			) {
			}
			""";

	static final String XML = """
			<?xml version="1.0" encoding="UTF-8"?>
			<sbe:messageSchema xmlns:sbe="http://fixprotocol.io/2016/sbe" package="corpus.arrays" id="1" version="0">
			    <types>
			        <composite name="messageHeader">
			            <type name="blockLength" primitiveType="uint16"/>
			            <type name="templateId" primitiveType="uint16"/>
			            <type name="schemaId" primitiveType="uint16"/>
			            <type name="version" primitiveType="uint16"/>
			        </composite>
			        <type name="Bounds" primitiveType="int16" length="2"/>
			        <type name="Rgb" primitiveType="uint8" length="3"/>
			        <type name="Samples" primitiveType="int32" length="4" description="Four readings, oldest first"/>
			    </types>
			    <sbe:message name="Arrays" id="1">
			        <field name="colour" id="1" type="Rgb"/>
			        <field name="samples" id="2" type="Samples"/>
			        <field name="bounds" id="3" type="Bounds"/>
			    </sbe:message>
			</sbe:messageSchema>
			""";

	/**
	 * What the codec must be: a write and read pair per array, the bytes through
	 * the bulk accessors and the rest by index.
	 */
	static final String CODEC = """
			package corpus.arrays;

			/** Generated by sbe-buddy from the schema of this package; do not edit. */
			@javax.annotation.processing.Generated("net.concini.sbebuddy")
			public final class ArraysCodec implements net.concini.sbebuddy.Codec<corpus.arrays.Arrays> {

				private final corpus.arrays.sbe.MessageHeaderEncoder headerEncoder = new corpus.arrays.sbe.MessageHeaderEncoder();
				private final corpus.arrays.sbe.MessageHeaderDecoder headerDecoder = new corpus.arrays.sbe.MessageHeaderDecoder();
				private final corpus.arrays.sbe.ArraysEncoder encoder = new corpus.arrays.sbe.ArraysEncoder();
				private final corpus.arrays.sbe.ArraysDecoder decoder = new corpus.arrays.sbe.ArraysDecoder();
				private int lastDecodedLength;

				public ArraysCodec() {
				}

				@Override
				public int encodedLength(corpus.arrays.Arrays value) {
					return corpus.arrays.sbe.MessageHeaderEncoder.ENCODED_LENGTH + corpus.arrays.sbe.ArraysEncoder.BLOCK_LENGTH;
				}

				@Override
				public int encode(corpus.arrays.Arrays value, org.agrona.MutableDirectBuffer buffer, int offset) {
					encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
					if (value.colour() == null) {
						throw new IllegalArgumentException("colour is required");
					}
					writeColour(value.colour(), encoder);
					if (value.samples() == null) {
						throw new IllegalArgumentException("samples is required");
					}
					writeSamples(value.samples(), encoder);
					if (value.bounds() == null) {
						throw new IllegalArgumentException("bounds is required");
					}
					writeBounds(value.bounds(), encoder);
					return corpus.arrays.sbe.MessageHeaderEncoder.ENCODED_LENGTH + encoder.encodedLength();
				}

				@Override
				public corpus.arrays.Arrays decode(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					if (headerDecoder.schemaId() != corpus.arrays.sbe.ArraysDecoder.SCHEMA_ID
							|| headerDecoder.templateId() != corpus.arrays.sbe.ArraysDecoder.TEMPLATE_ID) {
						throw new IllegalArgumentException(
								"not a Arrays: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
					}
					decoder.wrap(buffer, offset + corpus.arrays.sbe.MessageHeaderDecoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
					corpus.arrays.Arrays value = new corpus.arrays.Arrays(
							readColour(decoder),
							readSamples(decoder),
							readBounds(decoder)
					);
					lastDecodedLength = corpus.arrays.sbe.MessageHeaderDecoder.ENCODED_LENGTH + decoder.encodedLength();
					return value;
				}

				@Override
				public int lastDecodedLength() {
					return lastDecodedLength;
				}

				@Override
				public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					return corpus.arrays.sbe.MessageHeaderDecoder.ENCODED_LENGTH + headerDecoder.blockLength();
				}

				private static void writeColour(byte[] value, corpus.arrays.sbe.ArraysEncoder encoder) {
					if (value.length != corpus.arrays.sbe.ArraysEncoder.colourLength()) {
						throw new IllegalArgumentException(
								"colour must be " + corpus.arrays.sbe.ArraysEncoder.colourLength() + " long, not " + value.length);
					}
					encoder.putColour(value, 0, value.length);
				}

				private static byte[] readColour(corpus.arrays.sbe.ArraysDecoder decoder) {
					byte[] value = new byte[corpus.arrays.sbe.ArraysDecoder.colourLength()];
					decoder.getColour(value, 0, value.length);
					return value;
				}

				private static void writeSamples(int[] value, corpus.arrays.sbe.ArraysEncoder encoder) {
					if (value.length != corpus.arrays.sbe.ArraysEncoder.samplesLength()) {
						throw new IllegalArgumentException(
								"samples must be " + corpus.arrays.sbe.ArraysEncoder.samplesLength() + " long, not " + value.length);
					}
					for (int i = 0; i < value.length; i++) {
						encoder.samples(i, value[i]);
					}
				}

				private static int[] readSamples(corpus.arrays.sbe.ArraysDecoder decoder) {
					int[] value = new int[corpus.arrays.sbe.ArraysDecoder.samplesLength()];
					for (int i = 0; i < value.length; i++) {
						value[i] = decoder.samples(i);
					}
					return value;
				}

				private static void writeBounds(short[] value, corpus.arrays.sbe.ArraysEncoder encoder) {
					if (value.length != corpus.arrays.sbe.ArraysEncoder.boundsLength()) {
						throw new IllegalArgumentException(
								"bounds must be " + corpus.arrays.sbe.ArraysEncoder.boundsLength() + " long, not " + value.length);
					}
					for (int i = 0; i < value.length; i++) {
						encoder.bounds(i, value[i]);
					}
				}

				private static short[] readBounds(corpus.arrays.sbe.ArraysDecoder decoder) {
					short[] value = new short[corpus.arrays.sbe.ArraysDecoder.boundsLength()];
					for (int i = 0; i < value.length; i++) {
						value[i] = decoder.bounds(i);
					}
					return value;
				}
			}
			""";

	private Arrays() {
	}

	static Schema schema() {
		return messageSchema("corpus.arrays", 1, 0)
				.types(
						messageHeader(),
						type("Bounds", INT16).length(2),
						type("Rgb", UINT8).length(3),
						type("Samples", INT32).length(4).description("Four readings, oldest first")
				)
				.messages(
						message("Arrays", 1).fields(
								field("colour", 1, "Rgb"),
								field("samples", 2, "Samples"),
								field("bounds", 3, "Bounds")
						)
				)
				.build();
	}

	static Annotated annotated() {
		AnnotatedTypeBuilder rgb = annotatedType("Rgb", UINT8).length(3);
		AnnotatedTypeBuilder samples = annotatedType("Samples", INT32)
				.length(4)
				.description("Four readings, oldest first");
		AnnotatedTypeBuilder bounds = annotatedType("Bounds", INT16).length(2);
		return annotatedSchema("corpus.arrays", 1, 0)
				.types(bounds, rgb, samples)
				.messages(
						annotatedMessage("Arrays", 1).components(
								annotatedField("colour", 1, bytes()).type(rgb),
								annotatedField("samples", 2, array(INT)).type(samples),
								annotatedField("bounds", 3, array(SHORT)).type(bounds)
						)
				)
				.build();
	}
}
