package net.concini.sbebuddy.generator.corpus;

import static net.concini.sbebuddy.generator.Annotated.JavaPrimitive.BYTE;
import static net.concini.sbebuddy.generator.Fixtures.annotatedEnum;
import static net.concini.sbebuddy.generator.Fixtures.annotatedEnumValue;
import static net.concini.sbebuddy.generator.Fixtures.annotatedField;
import static net.concini.sbebuddy.generator.Fixtures.annotatedMessage;
import static net.concini.sbebuddy.generator.Fixtures.annotatedSchema;
import static net.concini.sbebuddy.generator.Fixtures.annotatedType;
import static net.concini.sbebuddy.generator.Fixtures.declared;
import static net.concini.sbebuddy.generator.Fixtures.enumeration;
import static net.concini.sbebuddy.generator.Fixtures.field;
import static net.concini.sbebuddy.generator.Fixtures.message;
import static net.concini.sbebuddy.generator.Fixtures.messageHeader;
import static net.concini.sbebuddy.generator.Fixtures.messageSchema;
import static net.concini.sbebuddy.generator.Fixtures.primitive;
import static net.concini.sbebuddy.generator.Fixtures.text;
import static net.concini.sbebuddy.generator.Fixtures.type;
import static net.concini.sbebuddy.generator.Fixtures.validValue;
import static uk.co.real_logic.sbe.PrimitiveType.CHAR;
import static uk.co.real_logic.sbe.xml.Presence.CONSTANT;

import net.concini.sbebuddy.generator.Annotated;
import net.concini.sbebuddy.generator.Fixtures.AnnotatedEnumBuilder;
import net.concini.sbebuddy.generator.Fixtures.AnnotatedTypeBuilder;
import net.concini.sbebuddy.generator.Schema;

/**
 * The three ways a value leaves the wire: a constant type holding its value as
 * text, a constant type naming a valid value, and a constant enum field.
 */
final class Constants {

	static final String PACKAGE_INFO = """
			@SbeSchema(id = 1, version = 0)
			package corpus.constants;

			import net.concini.sbebuddy.SbeSchema;
			""";

	static final String SOURCE = """
			package corpus.constants;

			import static net.concini.sbebuddy.Presence.CONSTANT;
			import static net.concini.sbebuddy.PrimitiveType.CHAR;

			import net.concini.sbebuddy.SbeEnum;
			import net.concini.sbebuddy.SbeEnumValue;
			import net.concini.sbebuddy.SbeField;
			import net.concini.sbebuddy.SbeMessage;
			import net.concini.sbebuddy.SbeType;

			@SbeEnum(primitiveType = CHAR)
			enum Side {

				@SbeEnumValue("B")
				Buy,

				@SbeEnumValue("S")
				Sell
			}

			@SbeType(primitiveType = CHAR, length = 3, presence = CONSTANT, value = "USD")
			final class Currency {
			}

			@SbeType(primitiveType = CHAR, presence = CONSTANT, valueRef = "Side.Buy")
			final class BuySide {
			}

			@SbeMessage(id = 1)
			record Constants(
					@SbeField(id = 1, type = Currency.class) String currency,
					@SbeField(id = 2, type = BuySide.class) byte buySide,
					@SbeField(id = 3, presence = CONSTANT, valueRef = "Side.Sell") Side side
			) {
			}
			""";

	static final String XML = """
			<?xml version="1.0" encoding="UTF-8"?>
			<sbe:messageSchema xmlns:sbe="http://fixprotocol.io/2016/sbe" package="corpus.constants" id="1" version="0">
			    <types>
			        <composite name="messageHeader">
			            <type name="blockLength" primitiveType="uint16"/>
			            <type name="templateId" primitiveType="uint16"/>
			            <type name="schemaId" primitiveType="uint16"/>
			            <type name="version" primitiveType="uint16"/>
			        </composite>
			        <type name="BuySide" primitiveType="char" presence="constant" valueRef="Side.Buy"/>
			        <type name="Currency" primitiveType="char" length="3" presence="constant">USD</type>
			        <enum name="Side" encodingType="char">
			            <validValue name="Buy">B</validValue>
			            <validValue name="Sell">S</validValue>
			        </enum>
			    </types>
			    <sbe:message name="Constants" id="1">
			        <field name="currency" id="1" type="Currency"/>
			        <field name="buySide" id="2" type="BuySide"/>
			        <field name="side" id="3" type="Side" presence="constant" valueRef="Side.Sell"/>
			    </sbe:message>
			</sbe:messageSchema>
			""";

	/**
	 * What the codec must be: each constant checked on encode and read on decode,
	 * the currency by equals, the buy side by ==, the side against the record's
	 * constant.
	 */
	static final String CODEC = """
			package corpus.constants;

			/** Generated by sbe-buddy from the schema of this package; do not edit. */
			@javax.annotation.processing.Generated("net.concini.sbebuddy")
			public final class ConstantsCodec implements net.concini.sbebuddy.Codec<corpus.constants.Constants> {

				private final corpus.constants.sbe.MessageHeaderEncoder headerEncoder = new corpus.constants.sbe.MessageHeaderEncoder();
				private final corpus.constants.sbe.MessageHeaderDecoder headerDecoder = new corpus.constants.sbe.MessageHeaderDecoder();
				private final corpus.constants.sbe.ConstantsEncoder encoder = new corpus.constants.sbe.ConstantsEncoder();
				private final corpus.constants.sbe.ConstantsDecoder decoder = new corpus.constants.sbe.ConstantsDecoder();
				private int lastDecodedLength;

				public ConstantsCodec() {
				}

				@Override
				public int encodedLength(corpus.constants.Constants value) {
					return corpus.constants.sbe.MessageHeaderEncoder.ENCODED_LENGTH + corpus.constants.sbe.ConstantsEncoder.BLOCK_LENGTH;
				}

				@Override
				public int encode(corpus.constants.Constants value, org.agrona.MutableDirectBuffer buffer, int offset) {
					encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
					if (value.currency() == null) {
						throw new IllegalArgumentException("currency is required");
					}
					if (!encoder.currency().equals(value.currency())) {
						throw new IllegalArgumentException("currency is the constant " + encoder.currency());
					}
					if (value.buySide() != encoder.buySide()) {
						throw new IllegalArgumentException("buySide is the constant " + encoder.buySide());
					}
					if (value.side() == null) {
						throw new IllegalArgumentException("side is required");
					}
					if (value.side() != corpus.constants.Side.Sell) {
						throw new IllegalArgumentException("side is the constant Sell");
					}
					return corpus.constants.sbe.MessageHeaderEncoder.ENCODED_LENGTH + encoder.encodedLength();
				}

				@Override
				public corpus.constants.Constants decode(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					if (headerDecoder.schemaId() != corpus.constants.sbe.ConstantsDecoder.SCHEMA_ID
							|| headerDecoder.templateId() != corpus.constants.sbe.ConstantsDecoder.TEMPLATE_ID) {
						throw new IllegalArgumentException(
								"not a Constants: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
					}
					decoder.wrap(buffer, offset + corpus.constants.sbe.MessageHeaderDecoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
					corpus.constants.Constants value = new corpus.constants.Constants(
							decoder.currency(),
							decoder.buySide(),
							decodeSide(decoder.sideRaw())
					);
					lastDecodedLength = corpus.constants.sbe.MessageHeaderDecoder.ENCODED_LENGTH + decoder.encodedLength();
					return value;
				}

				@Override
				public int lastDecodedLength() {
					return lastDecodedLength;
				}

				@Override
				public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					return corpus.constants.sbe.MessageHeaderDecoder.ENCODED_LENGTH + headerDecoder.blockLength();
				}

				private static corpus.constants.sbe.Side encodeSide(corpus.constants.Side value) {
					return switch (value) {
						case Buy -> corpus.constants.sbe.Side.Buy;
						case Sell -> corpus.constants.sbe.Side.Sell;
					};
				}

				private static corpus.constants.Side decodeSide(byte raw) {
					return switch (raw) {
						case (byte)66 -> corpus.constants.Side.Buy;
						case (byte)83 -> corpus.constants.Side.Sell;
						default -> throw new IllegalArgumentException("Side has no value " + raw);
					};
				}
			}
			""";

	private Constants() {
	}

	static Schema schema() {
		return messageSchema("corpus.constants", 1, 0)
				.types(
						messageHeader(),
						type("BuySide", CHAR).presence(CONSTANT).valueRef("Side.Buy"),
						type("Currency", CHAR).length(3).presence(CONSTANT).value("USD"),
						enumeration("Side", "char").validValues(
								validValue("Buy", "B"),
								validValue("Sell", "S")
						)
				)
				.messages(
						message("Constants", 1).fields(
								field("currency", 1, "Currency"),
								field("buySide", 2, "BuySide"),
								field("side", 3, "Side").presence(CONSTANT).valueRef("Side.Sell")
						)
				)
				.build();
	}

	static Annotated annotated() {
		AnnotatedEnumBuilder side = annotatedEnum("Side")
				.qualifiedName("corpus.constants.Side")
				.primitiveType(CHAR)
				.values(
						annotatedEnumValue("Buy", "B"),
						annotatedEnumValue("Sell", "S")
				);
		AnnotatedTypeBuilder currency = annotatedType("Currency", CHAR).length(3).presence(CONSTANT).value("USD");
		AnnotatedTypeBuilder buySide = annotatedType("BuySide", CHAR).presence(CONSTANT).valueRef("Side.Buy");
		return annotatedSchema("corpus.constants", 1, 0)
				.types(buySide, currency, side)
				.messages(
						annotatedMessage("Constants", 1).components(
								annotatedField("currency", 1, text()).type(currency),
								annotatedField("buySide", 2, primitive(BYTE)).type(buySide),
								annotatedField("side", 3, declared(side))
										.presence(CONSTANT)
										.valueRef("Side.Sell")
						)
				)
				.build();
	}
}
