package net.concini.sbebuddy.generator.corpus;

import static net.concini.sbebuddy.generator.Fixtures.annotatedEnum;
import static net.concini.sbebuddy.generator.Fixtures.annotatedEnumValue;
import static net.concini.sbebuddy.generator.Fixtures.annotatedField;
import static net.concini.sbebuddy.generator.Fixtures.annotatedMessage;
import static net.concini.sbebuddy.generator.Fixtures.annotatedSchema;
import static net.concini.sbebuddy.generator.Fixtures.annotatedType;
import static net.concini.sbebuddy.generator.Fixtures.declared;
import static net.concini.sbebuddy.generator.Fixtures.enumeration;
import static net.concini.sbebuddy.generator.Fixtures.field;
import static net.concini.sbebuddy.generator.Fixtures.message;
import static net.concini.sbebuddy.generator.Fixtures.messageHeader;
import static net.concini.sbebuddy.generator.Fixtures.messageSchema;
import static net.concini.sbebuddy.generator.Fixtures.type;
import static net.concini.sbebuddy.generator.Fixtures.validValue;
import static uk.co.real_logic.sbe.PrimitiveType.CHAR;
import static uk.co.real_logic.sbe.PrimitiveType.UINT8;

import net.concini.sbebuddy.generator.Annotated;
import net.concini.sbebuddy.generator.Fixtures.AnnotatedEnumBuilder;
import net.concini.sbebuddy.generator.Fixtures.AnnotatedTypeBuilder;
import net.concini.sbebuddy.generator.Schema;

/**
 * Enumerations over a primitive and over a named type, which sbe-tool resolves
 * to the primitive it encodes; one designates an unknown value, one does not.
 */
final class Enums {

	static final String PACKAGE_INFO = """
			@SbeSchema(id = 1, version = 0)
			package corpus.enums;

			import net.concini.sbebuddy.SbeSchema;
			""";

	static final String SOURCE = """
			package corpus.enums;

			import static net.concini.sbebuddy.PrimitiveType.CHAR;
			import static net.concini.sbebuddy.PrimitiveType.UINT8;

			import net.concini.sbebuddy.SbeEnum;
			import net.concini.sbebuddy.SbeEnumValue;
			import net.concini.sbebuddy.SbeField;
			import net.concini.sbebuddy.SbeMessage;
			import net.concini.sbebuddy.SbeType;
			import net.concini.sbebuddy.UnknownValue;

			@SbeType(primitiveType = UINT8)
			final class StatusCode {
			}

			@SbeEnum(primitiveType = CHAR, semanticType = "Side", description = "Which side of the market an order takes")
			enum Side {

				@SbeEnumValue(value = "B", description = "The order buys")
				Buy,

				@SbeEnumValue(value = "S", description = "The order sells")
				Sell
			}

			@SbeEnum(encodingType = StatusCode.class)
			enum OrderStatus {

				@SbeEnumValue("0")
				New,

				@SbeEnumValue("1")
				PartiallyFilled,

				@SbeEnumValue("2")
				Filled,

				@UnknownValue
				Unknown
			}

			@SbeMessage(id = 1)
			record Enums(
					@SbeField(id = 1) Side side,
					@SbeField(id = 2) OrderStatus status
			) {
			}
			""";

	static final String XML = """
			<?xml version="1.0" encoding="UTF-8"?>
			<sbe:messageSchema xmlns:sbe="http://fixprotocol.io/2016/sbe" package="corpus.enums" id="1" version="0">
			    <types>
			        <composite name="messageHeader">
			            <type name="blockLength" primitiveType="uint16"/>
			            <type name="templateId" primitiveType="uint16"/>
			            <type name="schemaId" primitiveType="uint16"/>
			            <type name="version" primitiveType="uint16"/>
			        </composite>
			        <type name="StatusCode" primitiveType="uint8"/>
			        <enum name="OrderStatus" encodingType="StatusCode">
			            <validValue name="New">0</validValue>
			            <validValue name="PartiallyFilled">1</validValue>
			            <validValue name="Filled">2</validValue>
			        </enum>
			        <enum name="Side" encodingType="char" semanticType="Side" description="Which side of the market an order takes">
			            <validValue name="Buy" description="The order buys">B</validValue>
			            <validValue name="Sell" description="The order sells">S</validValue>
			        </enum>
			    </types>
			    <sbe:message name="Enums" id="1">
			        <field name="side" id="1" type="Side"/>
			        <field name="status" id="2" type="OrderStatus"/>
			    </sbe:message>
			</sbe:messageSchema>
			""";

	/**
	 * What the codec must be for enums: the wire value read raw and mapped by the
	 * valid values, an unknown value the exception or the designated constant, and
	 * that constant refused on the way out.
	 */
	static final String CODEC = """
			package corpus.enums;

			/** Generated by sbe-buddy from the schema of this package; do not edit. */
			@javax.annotation.processing.Generated("net.concini.sbebuddy")
			public final class EnumsCodec implements net.concini.sbebuddy.Codec<corpus.enums.Enums> {

				private final corpus.enums.sbe.MessageHeaderEncoder headerEncoder = new corpus.enums.sbe.MessageHeaderEncoder();
				private final corpus.enums.sbe.MessageHeaderDecoder headerDecoder = new corpus.enums.sbe.MessageHeaderDecoder();
				private final corpus.enums.sbe.EnumsEncoder encoder = new corpus.enums.sbe.EnumsEncoder();
				private final corpus.enums.sbe.EnumsDecoder decoder = new corpus.enums.sbe.EnumsDecoder();
				private int lastDecodedLength;

				public EnumsCodec() {
				}

				@Override
				public int encodedLength(corpus.enums.Enums value) {
					return corpus.enums.sbe.MessageHeaderEncoder.ENCODED_LENGTH + corpus.enums.sbe.EnumsEncoder.BLOCK_LENGTH;
				}

				@Override
				public int encode(corpus.enums.Enums value, org.agrona.MutableDirectBuffer buffer, int offset) {
					encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
					if (value.side() == null) {
						throw new IllegalArgumentException("side is required");
					}
					encoder.side(encodeSide(value.side()));
					if (value.status() == null) {
						throw new IllegalArgumentException("status is required");
					}
					encoder.status(encodeOrderStatus(value.status()));
					return corpus.enums.sbe.MessageHeaderEncoder.ENCODED_LENGTH + encoder.encodedLength();
				}

				@Override
				public corpus.enums.Enums decode(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					if (headerDecoder.schemaId() != corpus.enums.sbe.EnumsDecoder.SCHEMA_ID
							|| headerDecoder.templateId() != corpus.enums.sbe.EnumsDecoder.TEMPLATE_ID) {
						throw new IllegalArgumentException(
								"not a Enums: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
					}
					decoder.wrap(buffer, offset + corpus.enums.sbe.MessageHeaderDecoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
					corpus.enums.Enums value = new corpus.enums.Enums(
							decodeSide(decoder.sideRaw()),
							decodeOrderStatus(decoder.statusRaw())
					);
					lastDecodedLength = corpus.enums.sbe.MessageHeaderDecoder.ENCODED_LENGTH + decoder.encodedLength();
					return value;
				}

				@Override
				public int lastDecodedLength() {
					return lastDecodedLength;
				}

				@Override
				public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					return corpus.enums.sbe.MessageHeaderDecoder.ENCODED_LENGTH + headerDecoder.blockLength();
				}

				private static corpus.enums.sbe.Side encodeSide(corpus.enums.Side value) {
					return switch (value) {
						case Buy -> corpus.enums.sbe.Side.Buy;
						case Sell -> corpus.enums.sbe.Side.Sell;
					};
				}

				private static corpus.enums.Side decodeSide(byte raw) {
					return switch (raw) {
						case (byte)66 -> corpus.enums.Side.Buy;
						case (byte)83 -> corpus.enums.Side.Sell;
						default -> throw new IllegalArgumentException("Side has no value " + raw);
					};
				}

				private static corpus.enums.sbe.OrderStatus encodeOrderStatus(corpus.enums.OrderStatus value) {
					return switch (value) {
						case New -> corpus.enums.sbe.OrderStatus.New;
						case PartiallyFilled -> corpus.enums.sbe.OrderStatus.PartiallyFilled;
						case Filled -> corpus.enums.sbe.OrderStatus.Filled;
						case Unknown -> throw new IllegalArgumentException("OrderStatus.Unknown has no wire form");
					};
				}

				private static corpus.enums.OrderStatus decodeOrderStatus(short raw) {
					return switch (raw) {
						case (short)0 -> corpus.enums.OrderStatus.New;
						case (short)1 -> corpus.enums.OrderStatus.PartiallyFilled;
						case (short)2 -> corpus.enums.OrderStatus.Filled;
						default -> corpus.enums.OrderStatus.Unknown;
					};
				}
			}
			""";

	private Enums() {
	}

	static Schema schema() {
		return messageSchema("corpus.enums", 1, 0)
				.types(
						messageHeader(),
						type("StatusCode", UINT8),
						enumeration("OrderStatus", "StatusCode").validValues(
								validValue("New", "0"),
								validValue("PartiallyFilled", "1"),
								validValue("Filled", "2")
						),
						enumeration("Side", "char")
								.semanticType("Side")
								.description("Which side of the market an order takes")
								.validValues(
										validValue("Buy", "B").description("The order buys"),
										validValue("Sell", "S").description("The order sells")
								)
				)
				.messages(
						message("Enums", 1).fields(
								field("side", 1, "Side"),
								field("status", 2, "OrderStatus")
						)
				)
				.build();
	}

	static Annotated annotated() {
		AnnotatedTypeBuilder statusCode = annotatedType("StatusCode", UINT8);
		AnnotatedEnumBuilder side = annotatedEnum("Side")
				.qualifiedName("corpus.enums.Side")
				.primitiveType(CHAR)
				.semanticType("Side")
				.description("Which side of the market an order takes")
				.values(
						annotatedEnumValue("Buy", "B").description("The order buys"),
						annotatedEnumValue("Sell", "S").description("The order sells")
				);
		AnnotatedEnumBuilder orderStatus = annotatedEnum("OrderStatus")
				.qualifiedName("corpus.enums.OrderStatus")
				.unknownValue("Unknown")
				.encodingType(statusCode)
				.values(
						annotatedEnumValue("New", "0"),
						annotatedEnumValue("PartiallyFilled", "1"),
						annotatedEnumValue("Filled", "2")
				);
		return annotatedSchema("corpus.enums", 1, 0)
				.types(orderStatus, side, statusCode)
				.messages(
						annotatedMessage("Enums", 1).components(
								annotatedField("side", 1, declared(side)),
								annotatedField("status", 2, declared(orderStatus))
						)
				)
				.build();
	}
}
