package net.concini.sbebuddy.generator.corpus;

import static net.concini.sbebuddy.generator.Annotated.JavaPrimitive.INT;
import static net.concini.sbebuddy.generator.Annotated.JavaPrimitive.LONG;
import static net.concini.sbebuddy.generator.Fixtures.annotatedField;
import static net.concini.sbebuddy.generator.Fixtures.annotatedMessage;
import static net.concini.sbebuddy.generator.Fixtures.annotatedSchema;
import static net.concini.sbebuddy.generator.Fixtures.field;
import static net.concini.sbebuddy.generator.Fixtures.message;
import static net.concini.sbebuddy.generator.Fixtures.messageHeader;
import static net.concini.sbebuddy.generator.Fixtures.messageSchema;
import static net.concini.sbebuddy.generator.Fixtures.primitive;
import static net.concini.sbebuddy.generator.Fixtures.unmapped;
import static uk.co.real_logic.sbe.PrimitiveType.INT64;

import net.concini.sbebuddy.generator.Annotated;
import net.concini.sbebuddy.generator.Schema;

/**
 * A record that says its wire order at the top: its components declared out of
 * that order, and a deprecated field in the middle of the block that no
 * component carries. The document is the one a record in wire order would
 * write.
 */
final class Layout {

	static final String PACKAGE_INFO = """
			@SbeSchema(id = 1, version = 1)
			package corpus.layout;

			import net.concini.sbebuddy.SbeSchema;
			""";

	static final String SOURCE = """
			package corpus.layout;

			import static net.concini.sbebuddy.PrimitiveType.INT64;

			import net.concini.sbebuddy.SbeField;
			import net.concini.sbebuddy.SbeMessage;

			@SbeMessage(
					id = 1, layout = {"orderId", "price", "quantity"},
					unmapped = @SbeField(id = 2, name = "price", primitiveType = INT64, deprecated = 1)
			)
			record Layout(
					@SbeField(id = 3) int quantity,
					@SbeField(id = 1) long orderId
			) {
			}
			""";

	static final String XML = """
			<?xml version="1.0" encoding="UTF-8"?>
			<sbe:messageSchema xmlns:sbe="http://fixprotocol.io/2016/sbe" package="corpus.layout" id="1" version="1">
			    <types>
			        <composite name="messageHeader">
			            <type name="blockLength" primitiveType="uint16"/>
			            <type name="templateId" primitiveType="uint16"/>
			            <type name="schemaId" primitiveType="uint16"/>
			            <type name="version" primitiveType="uint16"/>
			        </composite>
			    </types>
			    <sbe:message name="Layout" id="1">
			        <field name="orderId" id="1" type="int64"/>
			        <field name="price" id="2" type="int64" deprecated="1"/>
			        <field name="quantity" id="3" type="int32"/>
			    </sbe:message>
			</sbe:messageSchema>
			""";

	/**
	 * What the codec must be under a layout: the fields written in wire order, the
	 * unmapped one as its null value, and the constructor called in the record's
	 * own order.
	 */
	static final String CODEC = """
			package corpus.layout;

			/** Generated by sbe-buddy from the schema of this package; do not edit. */
			@javax.annotation.processing.Generated("net.concini.sbebuddy")
			public final class LayoutCodec implements net.concini.sbebuddy.Codec<corpus.layout.Layout> {

				private final corpus.layout.sbe.MessageHeaderEncoder headerEncoder = new corpus.layout.sbe.MessageHeaderEncoder();
				private final corpus.layout.sbe.MessageHeaderDecoder headerDecoder = new corpus.layout.sbe.MessageHeaderDecoder();
				private final corpus.layout.sbe.LayoutEncoder encoder = new corpus.layout.sbe.LayoutEncoder();
				private final corpus.layout.sbe.LayoutDecoder decoder = new corpus.layout.sbe.LayoutDecoder();
				private int lastDecodedLength;

				public LayoutCodec() {
				}

				@Override
				public int encodedLength(corpus.layout.Layout value) {
					return corpus.layout.sbe.MessageHeaderEncoder.ENCODED_LENGTH + corpus.layout.sbe.LayoutEncoder.BLOCK_LENGTH;
				}

				@Override
				public int encode(corpus.layout.Layout value, org.agrona.MutableDirectBuffer buffer, int offset) {
					encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
					encoder.orderId(value.orderId());
					encoder.price(corpus.layout.sbe.LayoutEncoder.priceNullValue());
					encoder.quantity(value.quantity());
					return corpus.layout.sbe.MessageHeaderEncoder.ENCODED_LENGTH + encoder.encodedLength();
				}

				@Override
				public corpus.layout.Layout decode(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					if (headerDecoder.schemaId() != corpus.layout.sbe.LayoutDecoder.SCHEMA_ID
							|| headerDecoder.templateId() != corpus.layout.sbe.LayoutDecoder.TEMPLATE_ID) {
						throw new IllegalArgumentException(
								"not a Layout: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
					}
					decoder.wrap(buffer, offset + corpus.layout.sbe.MessageHeaderDecoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
					corpus.layout.Layout value = new corpus.layout.Layout(
							decoder.quantity(),
							decoder.orderId()
					);
					lastDecodedLength = corpus.layout.sbe.MessageHeaderDecoder.ENCODED_LENGTH + decoder.encodedLength();
					return value;
				}

				@Override
				public int lastDecodedLength() {
					return lastDecodedLength;
				}

				@Override
				public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					return corpus.layout.sbe.MessageHeaderDecoder.ENCODED_LENGTH + headerDecoder.blockLength();
				}
			}
			""";

	private Layout() {
	}

	static Schema schema() {
		return messageSchema("corpus.layout", 1, 1)
				.types(messageHeader())
				.messages(
						message("Layout", 1).fields(
								field("orderId", 1, "int64"),
								field("price", 2, "int64").deprecated(1),
								field("quantity", 3, "int32")
						)
				)
				.build();
	}

	static Annotated annotated() {
		return annotatedSchema("corpus.layout", 1, 1)
				.messages(
						annotatedMessage("Layout", 1)
								.components(
										annotatedField("quantity", 3, primitive(INT)),
										annotatedField("orderId", 1, primitive(LONG))
								)
								.unmapped(
										annotatedField("price", 2, unmapped()).name("price").primitiveType(INT64)
												.deprecated(1)
								)
								.layout("orderId", "price", "quantity")
				)
				.build();
	}
}
