package net.concini.sbebuddy.generator.corpus;

import static net.concini.sbebuddy.generator.Annotated.JavaPrimitive.LONG;
import static net.concini.sbebuddy.generator.Fixtures.annotatedField;
import static net.concini.sbebuddy.generator.Fixtures.annotatedMessage;
import static net.concini.sbebuddy.generator.Fixtures.annotatedSchema;
import static net.concini.sbebuddy.generator.Fixtures.field;
import static net.concini.sbebuddy.generator.Fixtures.message;
import static net.concini.sbebuddy.generator.Fixtures.messageHeader;
import static net.concini.sbebuddy.generator.Fixtures.messageSchema;
import static net.concini.sbebuddy.generator.Fixtures.primitive;
import static uk.co.real_logic.sbe.PrimitiveType.UINT64;

import net.concini.sbebuddy.generator.Annotated;
import net.concini.sbebuddy.generator.Schema;

/**
 * Two messages in one schema, with the descriptive attributes a message and its
 * fields carry and a block reserved wider than its fields need.
 */
final class Messages {

	static final String PACKAGE_INFO = """
			@SbeSchema(id = 1, version = 0, description = "What a message and its fields may say about themselves")
			package corpus.messages;

			import net.concini.sbebuddy.SbeSchema;
			""";

	static final String SOURCE = """
			package corpus.messages;

			import static net.concini.sbebuddy.PrimitiveType.UINT64;

			import net.concini.sbebuddy.SbeField;
			import net.concini.sbebuddy.SbeMessage;

			@SbeMessage(id = 1, blockLength = 32, semanticType = "D", description = "A new single order")
			record NewOrder(
					@SbeField(id = 1, description = "The identifier the sender gave the order") long orderId,
					@SbeField(
							id = 2, primitiveType = UINT64, epoch = "unix", timeUnit = "nanosecond",
							semanticType = "UTCTimestamp", description = "When the order was sent"
					) long sentAt,
					@SbeField(id = 3, offset = 16, semanticType = "Price") long price
			) {
			}

			@SbeMessage(id = 2, semanticType = "F")
			record CancelOrder(
					@SbeField(id = 1) long orderId
			) {
			}
			""";

	static final String XML = """
			<?xml version="1.0" encoding="UTF-8"?>
			<sbe:messageSchema xmlns:sbe="http://fixprotocol.io/2016/sbe" package="corpus.messages" id="1" version="0" description="What a message and its fields may say about themselves">
			    <types>
			        <composite name="messageHeader">
			            <type name="blockLength" primitiveType="uint16"/>
			            <type name="templateId" primitiveType="uint16"/>
			            <type name="schemaId" primitiveType="uint16"/>
			            <type name="version" primitiveType="uint16"/>
			        </composite>
			    </types>
			    <sbe:message name="NewOrder" id="1" blockLength="32" semanticType="D" description="A new single order">
			        <field name="orderId" id="1" type="int64" description="The identifier the sender gave the order"/>
			        <field name="sentAt" id="2" type="uint64" epoch="unix" timeUnit="nanosecond" semanticType="UTCTimestamp" description="When the order was sent"/>
			        <field name="price" id="3" type="int64" offset="16" semanticType="Price"/>
			    </sbe:message>
			    <sbe:message name="CancelOrder" id="2" semanticType="F">
			        <field name="orderId" id="1" type="int64"/>
			    </sbe:message>
			</sbe:messageSchema>
			""";

	/**
	 * Two codecs from one schema, each owning its own flyweights; the block
	 * reserved wider is the flyweight's constant, not the codec's.
	 */
	static final String NEW_ORDER_CODEC = """
			package corpus.messages;

			/** Generated by sbe-buddy from the schema of this package; do not edit. */
			@javax.annotation.processing.Generated("net.concini.sbebuddy")
			public final class NewOrderCodec implements net.concini.sbebuddy.Codec<corpus.messages.NewOrder> {

				private final corpus.messages.sbe.MessageHeaderEncoder headerEncoder = new corpus.messages.sbe.MessageHeaderEncoder();
				private final corpus.messages.sbe.MessageHeaderDecoder headerDecoder = new corpus.messages.sbe.MessageHeaderDecoder();
				private final corpus.messages.sbe.NewOrderEncoder encoder = new corpus.messages.sbe.NewOrderEncoder();
				private final corpus.messages.sbe.NewOrderDecoder decoder = new corpus.messages.sbe.NewOrderDecoder();
				private int lastDecodedLength;

				public NewOrderCodec() {
				}

				@Override
				public int encodedLength(corpus.messages.NewOrder value) {
					return corpus.messages.sbe.MessageHeaderEncoder.ENCODED_LENGTH + corpus.messages.sbe.NewOrderEncoder.BLOCK_LENGTH;
				}

				@Override
				public int encode(corpus.messages.NewOrder value, org.agrona.MutableDirectBuffer buffer, int offset) {
					encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
					encoder.orderId(value.orderId());
					encoder.sentAt(value.sentAt());
					encoder.price(value.price());
					return corpus.messages.sbe.MessageHeaderEncoder.ENCODED_LENGTH + encoder.encodedLength();
				}

				@Override
				public corpus.messages.NewOrder decode(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					if (headerDecoder.schemaId() != corpus.messages.sbe.NewOrderDecoder.SCHEMA_ID
							|| headerDecoder.templateId() != corpus.messages.sbe.NewOrderDecoder.TEMPLATE_ID) {
						throw new IllegalArgumentException(
								"not a NewOrder: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
					}
					decoder.wrap(buffer, offset + corpus.messages.sbe.MessageHeaderDecoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
					corpus.messages.NewOrder value = new corpus.messages.NewOrder(
							decoder.orderId(),
							decoder.sentAt(),
							decoder.price()
					);
					lastDecodedLength = corpus.messages.sbe.MessageHeaderDecoder.ENCODED_LENGTH + decoder.encodedLength();
					return value;
				}

				@Override
				public int lastDecodedLength() {
					return lastDecodedLength;
				}

				@Override
				public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					return corpus.messages.sbe.MessageHeaderDecoder.ENCODED_LENGTH + headerDecoder.blockLength();
				}
			}
			""";

	static final String CANCEL_ORDER_CODEC = """
			package corpus.messages;

			/** Generated by sbe-buddy from the schema of this package; do not edit. */
			@javax.annotation.processing.Generated("net.concini.sbebuddy")
			public final class CancelOrderCodec implements net.concini.sbebuddy.Codec<corpus.messages.CancelOrder> {

				private final corpus.messages.sbe.MessageHeaderEncoder headerEncoder = new corpus.messages.sbe.MessageHeaderEncoder();
				private final corpus.messages.sbe.MessageHeaderDecoder headerDecoder = new corpus.messages.sbe.MessageHeaderDecoder();
				private final corpus.messages.sbe.CancelOrderEncoder encoder = new corpus.messages.sbe.CancelOrderEncoder();
				private final corpus.messages.sbe.CancelOrderDecoder decoder = new corpus.messages.sbe.CancelOrderDecoder();
				private int lastDecodedLength;

				public CancelOrderCodec() {
				}

				@Override
				public int encodedLength(corpus.messages.CancelOrder value) {
					return corpus.messages.sbe.MessageHeaderEncoder.ENCODED_LENGTH + corpus.messages.sbe.CancelOrderEncoder.BLOCK_LENGTH;
				}

				@Override
				public int encode(corpus.messages.CancelOrder value, org.agrona.MutableDirectBuffer buffer, int offset) {
					encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
					encoder.orderId(value.orderId());
					return corpus.messages.sbe.MessageHeaderEncoder.ENCODED_LENGTH + encoder.encodedLength();
				}

				@Override
				public corpus.messages.CancelOrder decode(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					if (headerDecoder.schemaId() != corpus.messages.sbe.CancelOrderDecoder.SCHEMA_ID
							|| headerDecoder.templateId() != corpus.messages.sbe.CancelOrderDecoder.TEMPLATE_ID) {
						throw new IllegalArgumentException(
								"not a CancelOrder: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
					}
					decoder.wrap(buffer, offset + corpus.messages.sbe.MessageHeaderDecoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
					corpus.messages.CancelOrder value = new corpus.messages.CancelOrder(
							decoder.orderId()
					);
					lastDecodedLength = corpus.messages.sbe.MessageHeaderDecoder.ENCODED_LENGTH + decoder.encodedLength();
					return value;
				}

				@Override
				public int lastDecodedLength() {
					return lastDecodedLength;
				}

				@Override
				public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					return corpus.messages.sbe.MessageHeaderDecoder.ENCODED_LENGTH + headerDecoder.blockLength();
				}
			}
			""";

	private Messages() {
	}

	static Schema schema() {
		return messageSchema("corpus.messages", 1, 0)
				.description("What a message and its fields may say about themselves")
				.types(messageHeader())
				.messages(
						message("NewOrder", 1)
								.blockLength(32)
								.semanticType("D")
								.description("A new single order")
								.fields(
										field("orderId", 1, "int64")
												.description("The identifier the sender gave the order"),
										field("sentAt", 2, "uint64")
												.epoch("unix")
												.timeUnit("nanosecond")
												.semanticType("UTCTimestamp")
												.description("When the order was sent"),
										field("price", 3, "int64").offset(16).semanticType("Price")
								),
						message("CancelOrder", 2)
								.semanticType("F")
								.fields(field("orderId", 1, "int64"))
				)
				.build();
	}

	static Annotated annotated() {
		return annotatedSchema("corpus.messages", 1, 0)
				.description("What a message and its fields may say about themselves")
				.messages(
						annotatedMessage("NewOrder", 1)
								.blockLength(32)
								.semanticType("D")
								.description("A new single order")
								.components(
										annotatedField("orderId", 1, primitive(LONG))
												.description("The identifier the sender gave the order"),
										annotatedField("sentAt", 2, primitive(LONG))
												.primitiveType(UINT64)
												.epoch("unix")
												.timeUnit("nanosecond")
												.semanticType("UTCTimestamp")
												.description("When the order was sent"),
										annotatedField("price", 3, primitive(LONG))
												.offset(16)
												.semanticType("Price")
								),
						annotatedMessage("CancelOrder", 2)
								.semanticType("F")
								.components(annotatedField("orderId", 1, primitive(LONG)))
				)
				.build();
	}
}
