package net.concini.sbebuddy.generator.corpus;

import static net.concini.sbebuddy.generator.Annotated.JavaPrimitive.DOUBLE;
import static net.concini.sbebuddy.generator.Annotated.JavaPrimitive.INT;
import static net.concini.sbebuddy.generator.Annotated.JavaPrimitive.LONG;
import static net.concini.sbebuddy.generator.Fixtures.annotatedField;
import static net.concini.sbebuddy.generator.Fixtures.annotatedMessage;
import static net.concini.sbebuddy.generator.Fixtures.annotatedSchema;
import static net.concini.sbebuddy.generator.Fixtures.boxed;
import static net.concini.sbebuddy.generator.Fixtures.field;
import static net.concini.sbebuddy.generator.Fixtures.message;
import static net.concini.sbebuddy.generator.Fixtures.messageHeader;
import static net.concini.sbebuddy.generator.Fixtures.messageSchema;
import static net.concini.sbebuddy.generator.Fixtures.primitive;
import static uk.co.real_logic.sbe.xml.Presence.OPTIONAL;

import net.concini.sbebuddy.generator.Annotated;
import net.concini.sbebuddy.generator.Schema;

/**
 * Presence declared on the field itself rather than on a named type; the
 * primitive's null value applies.
 */
final class OptionalFields {

	static final String PACKAGE_INFO = """
			@SbeSchema(id = 1, version = 0)
			package corpus.optionalfields;

			import net.concini.sbebuddy.SbeSchema;
			""";

	static final String SOURCE = """
			package corpus.optionalfields;

			import static net.concini.sbebuddy.Presence.OPTIONAL;

			import net.concini.sbebuddy.SbeField;
			import net.concini.sbebuddy.SbeMessage;

			@SbeMessage(id = 1)
			record OptionalFields(
					@SbeField(id = 1) long orderId,
					@SbeField(id = 2, presence = OPTIONAL) Integer quantity,
					@SbeField(id = 3, presence = OPTIONAL, description = "Absent for a market order") Double price
			) {
			}
			""";

	static final String XML = """
			<?xml version="1.0" encoding="UTF-8"?>
			<sbe:messageSchema xmlns:sbe="http://fixprotocol.io/2016/sbe" package="corpus.optionalfields" id="1" version="0">
			    <types>
			        <composite name="messageHeader">
			            <type name="blockLength" primitiveType="uint16"/>
			            <type name="templateId" primitiveType="uint16"/>
			            <type name="schemaId" primitiveType="uint16"/>
			            <type name="version" primitiveType="uint16"/>
			        </composite>
			    </types>
			    <sbe:message name="OptionalFields" id="1">
			        <field name="orderId" id="1" type="int64"/>
			        <field name="quantity" id="2" type="int32" presence="optional"/>
			        <field name="price" id="3" type="double" presence="optional" description="Absent for a market order"/>
			    </sbe:message>
			</sbe:messageSchema>
			""";

	/**
	 * What the codec must be for optional fields: the null value for null on the
	 * way out, null for the null value on the way back, compared as the floats
	 * need.
	 */
	static final String CODEC = """
			package corpus.optionalfields;

			/** Generated by sbe-buddy from the schema of this package; do not edit. */
			@javax.annotation.processing.Generated("net.concini.sbebuddy")
			public final class OptionalFieldsCodec implements net.concini.sbebuddy.Codec<corpus.optionalfields.OptionalFields> {

				private final corpus.optionalfields.sbe.MessageHeaderEncoder headerEncoder = new corpus.optionalfields.sbe.MessageHeaderEncoder();
				private final corpus.optionalfields.sbe.MessageHeaderDecoder headerDecoder = new corpus.optionalfields.sbe.MessageHeaderDecoder();
				private final corpus.optionalfields.sbe.OptionalFieldsEncoder encoder = new corpus.optionalfields.sbe.OptionalFieldsEncoder();
				private final corpus.optionalfields.sbe.OptionalFieldsDecoder decoder = new corpus.optionalfields.sbe.OptionalFieldsDecoder();
				private int lastDecodedLength;

				public OptionalFieldsCodec() {
				}

				@Override
				public int encodedLength(corpus.optionalfields.OptionalFields value) {
					return corpus.optionalfields.sbe.MessageHeaderEncoder.ENCODED_LENGTH + corpus.optionalfields.sbe.OptionalFieldsEncoder.BLOCK_LENGTH;
				}

				@Override
				public int encode(corpus.optionalfields.OptionalFields value, org.agrona.MutableDirectBuffer buffer, int offset) {
					encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
					encoder.orderId(value.orderId());
					encoder.quantity(value.quantity() == null ? corpus.optionalfields.sbe.OptionalFieldsEncoder.quantityNullValue() : value.quantity());
					encoder.price(value.price() == null ? corpus.optionalfields.sbe.OptionalFieldsEncoder.priceNullValue() : value.price());
					return corpus.optionalfields.sbe.MessageHeaderEncoder.ENCODED_LENGTH + encoder.encodedLength();
				}

				@Override
				public corpus.optionalfields.OptionalFields decode(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					if (headerDecoder.schemaId() != corpus.optionalfields.sbe.OptionalFieldsDecoder.SCHEMA_ID
							|| headerDecoder.templateId() != corpus.optionalfields.sbe.OptionalFieldsDecoder.TEMPLATE_ID) {
						throw new IllegalArgumentException(
								"not a OptionalFields: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
					}
					decoder.wrap(buffer, offset + corpus.optionalfields.sbe.MessageHeaderDecoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
					corpus.optionalfields.OptionalFields value = new corpus.optionalfields.OptionalFields(
							decoder.orderId(),
							decoder.quantity() == corpus.optionalfields.sbe.OptionalFieldsDecoder.quantityNullValue() ? null : decoder.quantity(),
							Double.compare(decoder.price(), corpus.optionalfields.sbe.OptionalFieldsDecoder.priceNullValue()) == 0 ? null : decoder.price()
					);
					lastDecodedLength = corpus.optionalfields.sbe.MessageHeaderDecoder.ENCODED_LENGTH + decoder.encodedLength();
					return value;
				}

				@Override
				public int lastDecodedLength() {
					return lastDecodedLength;
				}

				@Override
				public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					return corpus.optionalfields.sbe.MessageHeaderDecoder.ENCODED_LENGTH + headerDecoder.blockLength();
				}
			}
			""";

	private OptionalFields() {
	}

	static Schema schema() {
		return messageSchema("corpus.optionalfields", 1, 0)
				.types(messageHeader())
				.messages(
						message("OptionalFields", 1).fields(
								field("orderId", 1, "int64"),
								field("quantity", 2, "int32").presence(OPTIONAL),
								field("price", 3, "double").presence(OPTIONAL).description("Absent for a market order")
						)
				)
				.build();
	}

	static Annotated annotated() {
		return annotatedSchema("corpus.optionalfields", 1, 0)
				.messages(
						annotatedMessage("OptionalFields", 1).components(
								annotatedField("orderId", 1, primitive(LONG)),
								annotatedField("quantity", 2, boxed(INT)).presence(OPTIONAL),
								annotatedField("price", 3, boxed(DOUBLE))
										.presence(OPTIONAL)
										.description("Absent for a market order")
						)
				)
				.build();
	}
}
