package net.concini.sbebuddy.generator.corpus;

import static net.concini.sbebuddy.generator.Fixtures.annotatedChoice;
import static net.concini.sbebuddy.generator.Fixtures.annotatedField;
import static net.concini.sbebuddy.generator.Fixtures.annotatedMessage;
import static net.concini.sbebuddy.generator.Fixtures.annotatedSchema;
import static net.concini.sbebuddy.generator.Fixtures.annotatedSet;
import static net.concini.sbebuddy.generator.Fixtures.annotatedType;
import static net.concini.sbebuddy.generator.Fixtures.choice;
import static net.concini.sbebuddy.generator.Fixtures.field;
import static net.concini.sbebuddy.generator.Fixtures.message;
import static net.concini.sbebuddy.generator.Fixtures.messageHeader;
import static net.concini.sbebuddy.generator.Fixtures.messageSchema;
import static net.concini.sbebuddy.generator.Fixtures.set;
import static net.concini.sbebuddy.generator.Fixtures.setOf;
import static net.concini.sbebuddy.generator.Fixtures.type;
import static uk.co.real_logic.sbe.PrimitiveType.UINT16;
import static uk.co.real_logic.sbe.PrimitiveType.UINT8;

import net.concini.sbebuddy.generator.Annotated;
import net.concini.sbebuddy.generator.Fixtures.AnnotatedSetBuilder;
import net.concini.sbebuddy.generator.Fixtures.AnnotatedTypeBuilder;
import net.concini.sbebuddy.generator.Schema;

/**
 * Bit sets over a primitive and over a named type; a choice's text is the bit's
 * zero-based position, not its mask.
 */
final class Sets {

	static final String PACKAGE_INFO = """
			@SbeSchema(id = 1, version = 0)
			package corpus.sets;

			import net.concini.sbebuddy.SbeSchema;
			""";

	static final String SOURCE = """
			package corpus.sets;

			import static net.concini.sbebuddy.PrimitiveType.UINT16;
			import static net.concini.sbebuddy.PrimitiveType.UINT8;

			import java.util.Set;

			import net.concini.sbebuddy.SbeChoice;
			import net.concini.sbebuddy.SbeField;
			import net.concini.sbebuddy.SbeMessage;
			import net.concini.sbebuddy.SbeSet;
			import net.concini.sbebuddy.SbeType;

			@SbeType(primitiveType = UINT8)
			final class FlagsEncoding {
			}

			@SbeSet(primitiveType = UINT16, semanticType = "MultipleCharValue", description = "What the account may do")
			enum Permissions {

				@SbeChoice(value = 0, description = "May submit orders")
				canTrade,

				@SbeChoice(value = 1, description = "May submit quotes")
				canQuote,

				@SbeChoice(2)
				canCancel
			}

			@SbeSet(encodingType = FlagsEncoding.class)
			enum Handling {

				@SbeChoice(0)
				urgent,

				@SbeChoice(7)
				manual
			}

			@SbeMessage(id = 1)
			record Sets(
					@SbeField(id = 1) Set<Permissions> permissions,
					@SbeField(id = 2) Set<Handling> handling
			) {
			}
			""";

	static final String XML = """
			<?xml version="1.0" encoding="UTF-8"?>
			<sbe:messageSchema xmlns:sbe="http://fixprotocol.io/2016/sbe" package="corpus.sets" id="1" version="0">
			    <types>
			        <composite name="messageHeader">
			            <type name="blockLength" primitiveType="uint16"/>
			            <type name="templateId" primitiveType="uint16"/>
			            <type name="schemaId" primitiveType="uint16"/>
			            <type name="version" primitiveType="uint16"/>
			        </composite>
			        <type name="FlagsEncoding" primitiveType="uint8"/>
			        <set name="Permissions" encodingType="uint16" semanticType="MultipleCharValue" description="What the account may do">
			            <choice name="canTrade" description="May submit orders">0</choice>
			            <choice name="canQuote" description="May submit quotes">1</choice>
			            <choice name="canCancel">2</choice>
			        </set>
			        <set name="Handling" encodingType="FlagsEncoding">
			            <choice name="urgent">0</choice>
			            <choice name="manual">7</choice>
			        </set>
			    </types>
			    <sbe:message name="Sets" id="1">
			        <field name="permissions" id="1" type="Permissions"/>
			        <field name="handling" id="2" type="Handling"/>
			    </sbe:message>
			</sbe:messageSchema>
			""";

	/**
	 * What the codec must be for sets: every choice set from the Set on the way
	 * out, every choice on the wire added to an EnumSet on the way back, and a bit
	 * no choice names refused.
	 */
	static final String CODEC = """
			package corpus.sets;

			/** Generated by sbe-buddy from the schema of this package; do not edit. */
			@javax.annotation.processing.Generated("net.concini.sbebuddy")
			public final class SetsCodec implements net.concini.sbebuddy.Codec<corpus.sets.Sets> {

				private final corpus.sets.sbe.MessageHeaderEncoder headerEncoder = new corpus.sets.sbe.MessageHeaderEncoder();
				private final corpus.sets.sbe.MessageHeaderDecoder headerDecoder = new corpus.sets.sbe.MessageHeaderDecoder();
				private final corpus.sets.sbe.SetsEncoder encoder = new corpus.sets.sbe.SetsEncoder();
				private final corpus.sets.sbe.SetsDecoder decoder = new corpus.sets.sbe.SetsDecoder();
				private int lastDecodedLength;

				public SetsCodec() {
				}

				@Override
				public int encodedLength(corpus.sets.Sets value) {
					return corpus.sets.sbe.MessageHeaderEncoder.ENCODED_LENGTH + corpus.sets.sbe.SetsEncoder.BLOCK_LENGTH;
				}

				@Override
				public int encode(corpus.sets.Sets value, org.agrona.MutableDirectBuffer buffer, int offset) {
					encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
					if (value.permissions() == null) {
						throw new IllegalArgumentException("permissions is required");
					}
					encodePermissions(value.permissions(), encoder.permissions());
					if (value.handling() == null) {
						throw new IllegalArgumentException("handling is required");
					}
					encodeHandling(value.handling(), encoder.handling());
					return corpus.sets.sbe.MessageHeaderEncoder.ENCODED_LENGTH + encoder.encodedLength();
				}

				@Override
				public corpus.sets.Sets decode(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					if (headerDecoder.schemaId() != corpus.sets.sbe.SetsDecoder.SCHEMA_ID
							|| headerDecoder.templateId() != corpus.sets.sbe.SetsDecoder.TEMPLATE_ID) {
						throw new IllegalArgumentException(
								"not a Sets: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
					}
					decoder.wrap(buffer, offset + corpus.sets.sbe.MessageHeaderDecoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
					corpus.sets.Sets value = new corpus.sets.Sets(
							decodePermissions(decoder.permissions()),
							decodeHandling(decoder.handling())
					);
					lastDecodedLength = corpus.sets.sbe.MessageHeaderDecoder.ENCODED_LENGTH + decoder.encodedLength();
					return value;
				}

				@Override
				public int lastDecodedLength() {
					return lastDecodedLength;
				}

				@Override
				public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
					headerDecoder.wrap(buffer, offset);
					return corpus.sets.sbe.MessageHeaderDecoder.ENCODED_LENGTH + headerDecoder.blockLength();
				}

				private static void encodePermissions(java.util.Set<corpus.sets.Permissions> value, corpus.sets.sbe.PermissionsEncoder wire) {
					wire.clear();
					wire.canTrade(value.contains(corpus.sets.Permissions.canTrade));
					wire.canQuote(value.contains(corpus.sets.Permissions.canQuote));
					wire.canCancel(value.contains(corpus.sets.Permissions.canCancel));
				}

				private static java.util.Set<corpus.sets.Permissions> decodePermissions(corpus.sets.sbe.PermissionsDecoder wire) {
					if ((wire.getRaw() & ~(1L << 0 | 1L << 1 | 1L << 2)) != 0) {
						throw new IllegalArgumentException("Permissions has a bit no choice names: " + wire.getRaw());
					}
					java.util.Set<corpus.sets.Permissions> value = java.util.EnumSet.noneOf(corpus.sets.Permissions.class);
					if (wire.canTrade()) {
						value.add(corpus.sets.Permissions.canTrade);
					}
					if (wire.canQuote()) {
						value.add(corpus.sets.Permissions.canQuote);
					}
					if (wire.canCancel()) {
						value.add(corpus.sets.Permissions.canCancel);
					}
					return value;
				}

				private static void encodeHandling(java.util.Set<corpus.sets.Handling> value, corpus.sets.sbe.HandlingEncoder wire) {
					wire.clear();
					wire.urgent(value.contains(corpus.sets.Handling.urgent));
					wire.manual(value.contains(corpus.sets.Handling.manual));
				}

				private static java.util.Set<corpus.sets.Handling> decodeHandling(corpus.sets.sbe.HandlingDecoder wire) {
					if ((wire.getRaw() & ~(1L << 0 | 1L << 7)) != 0) {
						throw new IllegalArgumentException("Handling has a bit no choice names: " + wire.getRaw());
					}
					java.util.Set<corpus.sets.Handling> value = java.util.EnumSet.noneOf(corpus.sets.Handling.class);
					if (wire.urgent()) {
						value.add(corpus.sets.Handling.urgent);
					}
					if (wire.manual()) {
						value.add(corpus.sets.Handling.manual);
					}
					return value;
				}
			}
			""";

	private Sets() {
	}

	static Schema schema() {
		return messageSchema("corpus.sets", 1, 0)
				.types(
						messageHeader(),
						type("FlagsEncoding", UINT8),
						set("Permissions", "uint16")
								.semanticType("MultipleCharValue")
								.description("What the account may do")
								.choices(
										choice("canTrade", 0).description("May submit orders"),
										choice("canQuote", 1).description("May submit quotes"),
										choice("canCancel", 2)
								),
						set("Handling", "FlagsEncoding").choices(
								choice("urgent", 0),
								choice("manual", 7)
						)
				)
				.messages(
						message("Sets", 1).fields(
								field("permissions", 1, "Permissions"),
								field("handling", 2, "Handling")
						)
				)
				.build();
	}

	static Annotated annotated() {
		AnnotatedTypeBuilder flagsEncoding = annotatedType("FlagsEncoding", UINT8);
		AnnotatedSetBuilder permissions = annotatedSet("Permissions")
				.qualifiedName("corpus.sets.Permissions")
				.primitiveType(UINT16)
				.semanticType("MultipleCharValue")
				.description("What the account may do")
				.choices(
						annotatedChoice("canTrade", 0).description("May submit orders"),
						annotatedChoice("canQuote", 1).description("May submit quotes"),
						annotatedChoice("canCancel", 2)
				);
		AnnotatedSetBuilder handling = annotatedSet("Handling")
				.qualifiedName("corpus.sets.Handling")
				.encodingType(flagsEncoding)
				.choices(
						annotatedChoice("urgent", 0),
						annotatedChoice("manual", 7)
				);
		return annotatedSchema("corpus.sets", 1, 0)
				.types(flagsEncoding, permissions, handling)
				.messages(
						annotatedMessage("Sets", 1).components(
								annotatedField("permissions", 1, setOf(permissions)),
								annotatedField("handling", 2, setOf(handling))
						)
				)
				.build();
	}
}
