package net.concini.sbebuddy.processor;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.Element;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.ElementFilter;
import javax.tools.Diagnostic;
import javax.tools.StandardLocation;

import org.jspecify.annotations.Nullable;

import net.concini.sbebuddy.SbeMessage;
import net.concini.sbebuddy.SbeSchema;
import net.concini.sbebuddy.generator.Annotated;
import net.concini.sbebuddy.generator.Generator;
import net.concini.sbebuddy.generator.Mapping;
import net.concini.sbebuddy.generator.Problem;
import net.concini.sbebuddy.generator.Schema;
import net.concini.sbebuddy.generator.SchemaXml;

/**
 * The javac front-end: any annotated element in a round makes its package the
 * unit of work, handled once, in the round that first shows it. A package
 * without {@code @SbeSchema} declares types for a schema elsewhere and produces
 * nothing. Otherwise: discover, map, validate, generate; every problem is a
 * diagnostic of its severity on the element it names; a package without an
 * error gets its flyweights and codecs as sources and its {@code schema.xml} in
 * the class output.
 */
@SupportedAnnotationTypes("net.concini.sbebuddy.*")
public final class SbeProcessor extends AbstractProcessor {

	private final Set<String> handled = new HashSet<>();

	@Override
	public SourceVersion getSupportedSourceVersion() {
		return SourceVersion.latest();
	}

	@Override
	public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment round) {
		if (round.processingOver()) {
			return false;
		}
		Set<PackageElement> packages = new LinkedHashSet<>();
		for (TypeElement annotation : annotations) {
			for (Element element : round.getElementsAnnotatedWith(annotation)) {
				packages.add(processingEnv.getElementUtils().getPackageOf(element));
			}
		}
		for (PackageElement schemaPackage : packages) {
			if (handled.add(schemaPackage.getQualifiedName().toString())) {
				schema(schemaPackage);
			}
		}
		return false;
	}

	private void schema(PackageElement schemaPackage) {
		if (Discovery.annotation(schemaPackage, SbeSchema.class) == null) {
			// A package may hold declared types alone, which a schema elsewhere
			// references by class. A message is the one thing that needs its own
			// schema, so a message here would be generated by nothing.
			for (TypeElement message : messagesIn(schemaPackage.getEnclosedElements())) {
				error(
						"@SbeMessage in package " + schemaPackage.getQualifiedName()
								+ ", whose package-info.java carries no @SbeSchema",
						message, Discovery.annotation(message, SbeMessage.class)
				);
			}
			return;
		}
		Discovery.Discovered discovered = Discovery.discover(schemaPackage, processingEnv.getElementUtils());
		if (!discovered.problems().isEmpty()) {
			report(discovered.problems(), discovered, null, schemaPackage);
			return;
		}
		Mapping.Mapped mapped = Mapping.map(discovered.annotated());
		List<Problem> problems = new ArrayList<>(mapped.problems());
		if (problems.stream().noneMatch(Problem::isError)) {
			problems.addAll(Generator.validate(mapped.schema()));
		}
		report(problems, discovered, mapped, schemaPackage);
		if (problems.stream().anyMatch(Problem::isError)) {
			return;
		}
		List<Problem> generation = generate(schemaPackage, mapped.schema(), discovered.annotated());
		if (!generation.isEmpty()) {
			report(generation, discovered, mapped, schemaPackage);
			return;
		}
		write(schemaPackage, mapped.schema());
	}

	private List<Problem> generate(PackageElement schemaPackage, Schema schema, Annotated annotated) {
		try {
			return Generator
					.generate(schema, annotated, new FilerOutputManager(processingEnv.getFiler(), schemaPackage));
		} catch (UncheckedIOException e) {
			return List.of(new Problem(schema, "could not write generated code: " + e.getMessage()));
		}
	}

	/** Every {@code @SbeMessage} the elements hold, however deeply nested. */
	private static List<TypeElement> messagesIn(List<? extends Element> elements) {
		List<TypeElement> messages = new ArrayList<>();
		for (TypeElement type : ElementFilter.typesIn(elements)) {
			if (Discovery.annotation(type, SbeMessage.class) != null) {
				messages.add(type);
			}
			messages.addAll(messagesIn(type.getEnclosedElements()));
		}
		return messages;
	}

	/**
	 * A problem names an element, an annotated node or a schema node; the node is
	 * resolved in at most two lookups, and a node that resolves to nothing, which
	 * cannot happen, lands on the package. A warning is reported like an error and
	 * stops nothing.
	 */
	private void report(
			List<Problem> problems, Discovery.Discovered discovered, Mapping.@Nullable Mapped mapped,
			PackageElement schemaPackage
	) {
		for (Problem problem : problems) {
			Object node = problem.node();
			if (mapped != null) {
				Object origin = mapped.origins().get(node);
				node = origin == null ? node : origin;
			}
			Element element = node instanceof Element direct ? direct : discovered.elements().get(node);
			Diagnostic.Kind kind = problem.isError() ? Diagnostic.Kind.ERROR : Diagnostic.Kind.WARNING;
			print(kind, problem.message(), element == null ? schemaPackage : element, discovered.mirrors().get(node));
		}
	}

	private void error(String message, Element element, @Nullable AnnotationMirror mirror) {
		print(Diagnostic.Kind.ERROR, message, element, mirror);
	}

	private void print(Diagnostic.Kind kind, String message, Element element, @Nullable AnnotationMirror mirror) {
		if (mirror == null) {
			processingEnv.getMessager().printMessage(kind, message, element);
		} else {
			processingEnv.getMessager().printMessage(kind, message, element, mirror);
		}
	}

	private void write(PackageElement schemaPackage, Schema schema) {
		try (
				Writer writer = processingEnv.getFiler()
						.createResource(
								StandardLocation.CLASS_OUTPUT, schemaPackage.getQualifiedName(), "schema.xml",
								schemaPackage
						)
						.openWriter()) {
			SchemaXml.write(schema, writer);
		} catch (IOException e) {
			error("could not write schema.xml: " + e.getMessage(), schemaPackage, null);
		}
	}
}
