package corpus.groups;

/**
 * The message {@code Groups} as the sequence of its stages over sbe-tool's
 * {@code GroupsDecoder}: the root block, then each group's header and entries
 * and each var-data, in wire order. Generated by sbe-buddy from the schema of
 * this package; do not edit.
 */
@javax.annotation.processing.Generated("net.concini.sbebuddy")
public final class GroupsReader implements Iterable<GroupsReader.Stage>, java.util.Iterator<GroupsReader.Stage> {

	/** A stage of {@code Groups}, in the order they come. */
	public sealed interface Stage extends net.concini.sbebuddy.Stage permits RootBlock, Legs, LegsEntry, Allocations, AllocationsEntry, Fills, FillsEntry {
	}

	/** Where the reader is, in wire order: a stage is open while this lies in its range. */
	private enum At {
		BEFORE_ROOT_BLOCK,
		ROOT_BLOCK,
		LEGS,
		LEGS_ENTRY,
		ALLOCATIONS,
		ALLOCATIONS_ENTRY,
		AFTER_ALLOCATIONS,
		AFTER_LEGS,
		FILLS,
		FILLS_ENTRY,
		AFTER_FILLS,
		END,
	}

	private static final net.concini.sbebuddy.BindingContext fills$PriceContext = new net.concini.sbebuddy.BindingContext("price", net.concini.sbebuddy.PrimitiveType.INT64, null, null, null, net.concini.sbebuddy.Presence.REQUIRED);
	private final corpus.groups.sbe.MessageHeaderDecoder header = new corpus.groups.sbe.MessageHeaderDecoder();
	private final corpus.groups.sbe.GroupsDecoder decoder = new corpus.groups.sbe.GroupsDecoder();
	private final corpus.groups.sbe.GroupsDecoder measure = new corpus.groups.sbe.GroupsDecoder();
	private final corpus.groups.CentsBinding centsBinding = new corpus.groups.CentsBinding();
	private final RootBlock rootBlockStage = new RootBlock();
	private final RootBlockBound rootBlockBound = new RootBlockBound();
	private final Legs legsStage = new Legs();
	private final LegsEntry legsEntryStage = new LegsEntry();
	private final LegsEntryBound legsEntryBound = new LegsEntryBound();
	private corpus.groups.sbe.GroupsDecoder.LegsDecoder legsDecoder;
	private int legsIndex;
	private final Allocations allocationsStage = new Allocations();
	private final AllocationsEntry allocationsEntryStage = new AllocationsEntry();
	private final AllocationsEntryBound allocationsEntryBound = new AllocationsEntryBound();
	private corpus.groups.sbe.GroupsDecoder.LegsDecoder.AllocationsDecoder allocationsDecoder;
	private int allocationsIndex;
	private final Fills fillsStage = new Fills();
	private final FillsEntry fillsEntryStage = new FillsEntry();
	private final FillsEntryBound fillsEntryBound = new FillsEntryBound();
	private corpus.groups.sbe.GroupsDecoder.FillsDecoder fillsDecoder;
	private int fillsIndex;
	private At at = At.BEFORE_ROOT_BLOCK;

	/**
	 * Reads the header at the offset and stands before the root block; another
	 * template is sbe-tool's {@link IllegalStateException}.
	 */
	public GroupsReader wrap(org.agrona.DirectBuffer buffer, int offset) {
		decoder.wrapAndApplyHeader(buffer, offset, header);
		at = At.BEFORE_ROOT_BLOCK;
		return this;
	}

	/** Back before the root block of the message wrapped. */
	public GroupsReader rewind() {
		decoder.sbeRewind();
		at = At.BEFORE_ROOT_BLOCK;
		return this;
	}

	/** The header as read, for its own members. */
	public corpus.groups.sbe.MessageHeaderDecoder header() {
		return header;
	}

	public int actingVersion() {
		return decoder.actingVersion();
	}

	/**
	 * The bytes of the whole message, header included, at any point. Once no stage
	 * is left the limit is at its end; before that a second decoder walks the
	 * message, so the group decoders in use are not disturbed.
	 */
	public int decodedLength() {
		if (!hasNext()) {
			return corpus.groups.sbe.MessageHeaderDecoder.ENCODED_LENGTH + decoder.encodedLength();
		}
		return corpus.groups.sbe.MessageHeaderDecoder.ENCODED_LENGTH
				+ measure.wrap(decoder.buffer(), decoder.offset(), header.blockLength(), header.version()).sbeDecodedLength();
	}

	@Override
	public java.util.Iterator<Stage> iterator() {
		return this;
	}

	/** Whether a stage follows; reads nothing and moves nothing. */
	@Override
	public boolean hasNext() {
		return switch (at) {
			case BEFORE_ROOT_BLOCK -> true;
			case ROOT_BLOCK -> true;
			case LEGS -> hasRestLegs();
			case LEGS_ENTRY -> true;
			case ALLOCATIONS -> hasRestAllocations();
			case ALLOCATIONS_ENTRY -> hasRestAllocations();
			case AFTER_ALLOCATIONS -> hasRestLegs();
			case AFTER_LEGS -> decoder.actingVersion() >= corpus.groups.sbe.GroupsDecoder.fillsDecoderSinceVersion();
			case FILLS -> hasRestFills();
			case FILLS_ENTRY -> hasRestFills();
			case AFTER_FILLS -> false;
			case END -> false;
		};
	}

	/** The next stage; what the current one left unread is passed over. */
	@Override
	public Stage next() {
		return switch (at) {
			case BEFORE_ROOT_BLOCK -> openRootBlock();
			case ROOT_BLOCK -> openLegs();
			case LEGS -> restLegs();
			case LEGS_ENTRY -> openAllocations();
			case ALLOCATIONS -> restAllocations();
			case ALLOCATIONS_ENTRY -> restAllocations();
			case AFTER_ALLOCATIONS -> restLegs();
			case AFTER_LEGS -> decoder.actingVersion() >= corpus.groups.sbe.GroupsDecoder.fillsDecoderSinceVersion() ? openFills() : end();
			case FILLS -> restFills();
			case FILLS_ENTRY -> restFills();
			case AFTER_FILLS -> end();
			case END -> end();
		};
	}

	private Stage openRootBlock() {
		at = At.ROOT_BLOCK;
		return rootBlockStage;
	}

	private Stage openLegs() {
		legsDecoder = decoder.legs();
		legsIndex = -1;
		at = At.LEGS;
		return legsStage;
	}

	private Stage nextLegsEntry() {
		legsDecoder.next();
		legsIndex++;
		at = At.LEGS_ENTRY;
		return legsEntryStage;
	}

	/** Past an entry of {@code legs}, or its header: the next entry, else what follows the group. */
	private Stage restLegs() {
		return legsDecoder.hasNext() ? nextLegsEntry() : decoder.actingVersion() >= corpus.groups.sbe.GroupsDecoder.fillsDecoderSinceVersion() ? openFills() : end();
	}

	private boolean hasRestLegs() {
		return legsDecoder.hasNext() || decoder.actingVersion() >= corpus.groups.sbe.GroupsDecoder.fillsDecoderSinceVersion();
	}

	private Stage openAllocations() {
		allocationsDecoder = legsDecoder.allocations();
		allocationsIndex = -1;
		at = At.ALLOCATIONS;
		return allocationsStage;
	}

	private Stage nextAllocationsEntry() {
		allocationsDecoder.next();
		allocationsIndex++;
		at = At.ALLOCATIONS_ENTRY;
		return allocationsEntryStage;
	}

	/** Past an entry of {@code legs.allocations}, or its header: the next entry, else what follows the group. */
	private Stage restAllocations() {
		return allocationsDecoder.hasNext() ? nextAllocationsEntry() : restLegs();
	}

	private boolean hasRestAllocations() {
		return allocationsDecoder.hasNext() || hasRestLegs();
	}

	private Stage openFills() {
		fillsDecoder = decoder.fills();
		fillsIndex = -1;
		at = At.FILLS;
		return fillsStage;
	}

	private Stage nextFillsEntry() {
		fillsDecoder.next();
		fillsIndex++;
		at = At.FILLS_ENTRY;
		return fillsEntryStage;
	}

	/** Past an entry of {@code fills}, or its header: the next entry, else what follows the group. */
	private Stage restFills() {
		return fillsDecoder.hasNext() ? nextFillsEntry() : end();
	}

	private boolean hasRestFills() {
		return fillsDecoder.hasNext();
	}

	private Stage end() {
		at = At.END;
		throw new java.util.NoSuchElementException();
	}

	private void open(At first, At last, String stage) {
		if (at.compareTo(first) < 0 || at.compareTo(last) > 0) {
			throw new IllegalStateException(stage + " is not open");
		}
	}

	private void current(At expected, String stage) {
		if (at != expected) {
			throw new IllegalStateException(stage + " is not the current stage");
		}
	}

	/**
	 * The root block of {@code Groups}: its fields, delegated to sbe-tool's
	 * decoder; open for the whole message.
	 */
	public final class RootBlock implements Stage {

		private RootBlock() {
		}

		public long orderId() {
			GroupsReader.this.open(At.ROOT_BLOCK, At.END, "RootBlock");
			return decoder.orderId();
		}

		/** The record's view of this stage. */
		public RootBlockBound bound() {
			GroupsReader.this.open(At.ROOT_BLOCK, At.END, "RootBlock");
			return rootBlockBound;
		}

		/** The rest of the message: iteration ends. */
		@Override
		public void skip() {
			GroupsReader.this.current(At.ROOT_BLOCK, "RootBlock");
			decoder.sbeSkip();
			at = At.END;
		}
	}

	/**
	 * The components of {@code corpus.groups.Groups} in the root block, each read and
	 * bound on every call, never cached: null where absent, and above the acting
	 * version.
	 */
	public final class RootBlockBound {

		private RootBlockBound() {
		}

		public long orderId() {
			GroupsReader.this.open(At.ROOT_BLOCK, At.END, "RootBlock");
			return decoder.orderId();
		}

		/** The stage this is the view of. */
		public RootBlock wire() {
			GroupsReader.this.open(At.ROOT_BLOCK, At.END, "RootBlock");
			return rootBlockStage;
		}
	}

	/**
	 * The header of the group {@code legs}: its count, over sbe-tool's group
	 * decoder; open while the reader is inside the group.
	 */
	public final class Legs implements Stage {

		private Legs() {
		}

		public int count() {
			GroupsReader.this.open(At.LEGS, At.AFTER_ALLOCATIONS, "Legs");
			return legsDecoder.count();
		}

		/** Every entry, with all it holds: no {@code LegsEntry} comes. */
		@Override
		public void skip() {
			GroupsReader.this.current(At.LEGS, "Legs");
			while (legsDecoder.hasNext()) {
				legsDecoder.next();
				legsDecoder.sbeSkip();
			}
			at = At.AFTER_LEGS;
		}
	}

	/**
	 * An entry of the group {@code legs}: its fields, over sbe-tool's group decoder
	 * after its {@code next()}; open while the reader is inside it.
	 */
	public final class LegsEntry implements Stage {

		private LegsEntry() {
		}

		/** Which entry of the group this is, from 0. */
		public int index() {
			GroupsReader.this.open(At.LEGS_ENTRY, At.AFTER_ALLOCATIONS, "LegsEntry");
			return legsIndex;
		}

		public int legId() {
			GroupsReader.this.open(At.LEGS_ENTRY, At.AFTER_ALLOCATIONS, "LegsEntry");
			return legsDecoder.legId();
		}

		public short legRatio() {
			GroupsReader.this.open(At.LEGS_ENTRY, At.AFTER_ALLOCATIONS, "LegsEntry");
			return legsDecoder.legRatio();
		}

		/** The record's view of this stage. */
		public LegsEntryBound bound() {
			GroupsReader.this.open(At.LEGS_ENTRY, At.AFTER_ALLOCATIONS, "LegsEntry");
			return legsEntryBound;
		}

		/** What the entry holds past its block: its groups and var-data never come. */
		@Override
		public void skip() {
			GroupsReader.this.current(At.LEGS_ENTRY, "LegsEntry");
			legsDecoder.sbeSkip();
			at = At.AFTER_ALLOCATIONS;
		}
	}

	/**
	 * The components of {@code corpus.groups.Groups.Leg} in an entry of {@code legs}, each read and
	 * bound on every call, never cached: null where absent, and above the acting
	 * version.
	 */
	public final class LegsEntryBound {

		private LegsEntryBound() {
		}

		/** Which entry of the group this is, from 0. */
		public int index() {
			GroupsReader.this.open(At.LEGS_ENTRY, At.AFTER_ALLOCATIONS, "LegsEntry");
			return legsIndex;
		}

		public int legId() {
			GroupsReader.this.open(At.LEGS_ENTRY, At.AFTER_ALLOCATIONS, "LegsEntry");
			return legsDecoder.legId();
		}

		/** The stage this is the view of. */
		public LegsEntry wire() {
			GroupsReader.this.open(At.LEGS_ENTRY, At.AFTER_ALLOCATIONS, "LegsEntry");
			return legsEntryStage;
		}
	}

	/**
	 * The header of the group {@code legs.allocations}: its count, over sbe-tool's group
	 * decoder; open while the reader is inside the group.
	 */
	public final class Allocations implements Stage {

		private Allocations() {
		}

		public int count() {
			GroupsReader.this.open(At.ALLOCATIONS, At.ALLOCATIONS_ENTRY, "Allocations");
			return allocationsDecoder.count();
		}

		/** Every entry, with all it holds: no {@code AllocationsEntry} comes. */
		@Override
		public void skip() {
			GroupsReader.this.current(At.ALLOCATIONS, "Allocations");
			while (allocationsDecoder.hasNext()) {
				allocationsDecoder.next();
				allocationsDecoder.sbeSkip();
			}
			at = At.AFTER_ALLOCATIONS;
		}
	}

	/**
	 * An entry of the group {@code legs.allocations}: its fields, over sbe-tool's group decoder
	 * after its {@code next()}; open while the reader is inside it.
	 */
	public final class AllocationsEntry implements Stage {

		private AllocationsEntry() {
		}

		/** Which entry of the group this is, from 0. */
		public int index() {
			GroupsReader.this.open(At.ALLOCATIONS_ENTRY, At.ALLOCATIONS_ENTRY, "AllocationsEntry");
			return allocationsIndex;
		}

		public int account() {
			GroupsReader.this.open(At.ALLOCATIONS_ENTRY, At.ALLOCATIONS_ENTRY, "AllocationsEntry");
			return allocationsDecoder.account();
		}

		public int share() {
			GroupsReader.this.open(At.ALLOCATIONS_ENTRY, At.ALLOCATIONS_ENTRY, "AllocationsEntry");
			return allocationsDecoder.share();
		}

		/** The record's view of this stage. */
		public AllocationsEntryBound bound() {
			GroupsReader.this.open(At.ALLOCATIONS_ENTRY, At.ALLOCATIONS_ENTRY, "AllocationsEntry");
			return allocationsEntryBound;
		}

		/** What the entry holds past its block: its groups and var-data never come. */
		@Override
		public void skip() {
			GroupsReader.this.current(At.ALLOCATIONS_ENTRY, "AllocationsEntry");
			allocationsDecoder.sbeSkip();
			at = At.ALLOCATIONS_ENTRY;
		}
	}

	/**
	 * The components of {@code corpus.groups.Groups.Leg.Allocation} in an entry of {@code legs.allocations}, each read and
	 * bound on every call, never cached: null where absent, and above the acting
	 * version.
	 */
	public final class AllocationsEntryBound {

		private AllocationsEntryBound() {
		}

		/** Which entry of the group this is, from 0. */
		public int index() {
			GroupsReader.this.open(At.ALLOCATIONS_ENTRY, At.ALLOCATIONS_ENTRY, "AllocationsEntry");
			return allocationsIndex;
		}

		public int account() {
			GroupsReader.this.open(At.ALLOCATIONS_ENTRY, At.ALLOCATIONS_ENTRY, "AllocationsEntry");
			return allocationsDecoder.account();
		}

		public java.lang.Integer share() {
			GroupsReader.this.open(At.ALLOCATIONS_ENTRY, At.ALLOCATIONS_ENTRY, "AllocationsEntry");
			return allocationsDecoder.share() == corpus.groups.sbe.GroupsDecoder.LegsDecoder.AllocationsDecoder.shareNullValue() ? null : allocationsDecoder.share();
		}

		/** The stage this is the view of. */
		public AllocationsEntry wire() {
			GroupsReader.this.open(At.ALLOCATIONS_ENTRY, At.ALLOCATIONS_ENTRY, "AllocationsEntry");
			return allocationsEntryStage;
		}
	}

	/**
	 * The header of the group {@code fills}: its count, over sbe-tool's group
	 * decoder; open while the reader is inside the group.
	 */
	public final class Fills implements Stage {

		private Fills() {
		}

		public int count() {
			GroupsReader.this.open(At.FILLS, At.FILLS_ENTRY, "Fills");
			return fillsDecoder.count();
		}

		/** Every entry, with all it holds: no {@code FillsEntry} comes. */
		@Override
		public void skip() {
			GroupsReader.this.current(At.FILLS, "Fills");
			while (fillsDecoder.hasNext()) {
				fillsDecoder.next();
				fillsDecoder.sbeSkip();
			}
			at = At.AFTER_FILLS;
		}
	}

	/**
	 * An entry of the group {@code fills}: its fields, over sbe-tool's group decoder
	 * after its {@code next()}; open while the reader is inside it.
	 */
	public final class FillsEntry implements Stage {

		private FillsEntry() {
		}

		/** Which entry of the group this is, from 0. */
		public int index() {
			GroupsReader.this.open(At.FILLS_ENTRY, At.FILLS_ENTRY, "FillsEntry");
			return fillsIndex;
		}

		public long price() {
			GroupsReader.this.open(At.FILLS_ENTRY, At.FILLS_ENTRY, "FillsEntry");
			return fillsDecoder.price();
		}

		/** The record's view of this stage. */
		public FillsEntryBound bound() {
			GroupsReader.this.open(At.FILLS_ENTRY, At.FILLS_ENTRY, "FillsEntry");
			return fillsEntryBound;
		}

		/** What the entry holds past its block: its groups and var-data never come. */
		@Override
		public void skip() {
			GroupsReader.this.current(At.FILLS_ENTRY, "FillsEntry");
			fillsDecoder.sbeSkip();
			at = At.FILLS_ENTRY;
		}
	}

	/**
	 * The components of {@code corpus.groups.Groups.Fill} in an entry of {@code fills}, each read and
	 * bound on every call, never cached: null where absent, and above the acting
	 * version.
	 */
	public final class FillsEntryBound {

		private FillsEntryBound() {
		}

		/** Which entry of the group this is, from 0. */
		public int index() {
			GroupsReader.this.open(At.FILLS_ENTRY, At.FILLS_ENTRY, "FillsEntry");
			return fillsIndex;
		}

		public java.math.BigDecimal price() {
			GroupsReader.this.open(At.FILLS_ENTRY, At.FILLS_ENTRY, "FillsEntry");
			return centsBinding.fromWire(fillsDecoder.price(), fills$PriceContext);
		}

		/** The stage this is the view of. */
		public FillsEntry wire() {
			GroupsReader.this.open(At.FILLS_ENTRY, At.FILLS_ENTRY, "FillsEntry");
			return fillsEntryStage;
		}
	}
}
