package net.concini.sbebuddy.generator;

/**
 * The text of a codec around its leaves: the class, the header, the lengths,
 * the groups and the var-data, and a union's codec. {@link CodecWriter} and
 * {@link UnionWriter} fill them from their models; a template's names in braces
 * are the only values it takes.
 */
final class CodecTemplates {

	private CodecTemplates() {
	}

	static final Template CODEC = Template.of(
			"""
					package {packageName};

					/** Generated by sbe-buddy from the schema of this package; do not edit. */
					@javax.annotation.processing.Generated("net.concini.sbebuddy")
					public final class {codec} implements net.concini.sbebuddy.Codec<{record}, {headerRecord}> {

						{contexts}
						private final {flyweights}.{headerClass}Encoder headerEncoder = new {flyweights}.{headerClass}Encoder();
						private final {flyweights}.{headerClass}Decoder headerDecoder = new {flyweights}.{headerClass}Decoder();
						private final {flyweights}.{message}Encoder encoder = new {flyweights}.{message}Encoder();
						private final {flyweights}.{message}Decoder decoder = new {flyweights}.{message}Decoder();
						{bindings}
						private int lastDecodedLength;

						public {codec}() {
						}

						@Override
						public int encodedLength({record} value) {
							if (value == null) {
								throw new IllegalArgumentException("value is required");
							}
							return {flyweights}.{headerClass}Encoder.ENCODED_LENGTH + {flyweights}.{message}Encoder.BLOCK_LENGTH{variableLengths};
						}

						@Override
						public int encode({record} value, org.agrona.MutableDirectBuffer buffer, int offset) {
							if (value == null) {
								throw new IllegalArgumentException("value is required");
							}
							encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
							{writeNullHeader}
							return encodeBody(value);
						}

						@Override
						public int encode({record} value, {headerRecord} header, org.agrona.MutableDirectBuffer buffer, int offset) {
							if (value == null) {
								throw new IllegalArgumentException("value is required");
							}
							if (header == null) {
								throw new IllegalArgumentException("header is required");
							}
							encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
							{writeHeader}
							return encodeBody(value);
						}

						private int encodeBody({record} value) {
							{encodeFields}
							return {flyweights}.{headerClass}Encoder.ENCODED_LENGTH + encoder.encodedLength();
						}

						@Override
						public {record} decode(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							if (headerDecoder.schemaId() != {flyweights}.{message}Decoder.SCHEMA_ID
									|| headerDecoder.templateId() != {flyweights}.{message}Decoder.TEMPLATE_ID) {
								throw new IllegalArgumentException(
										"not a {message}: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
							}
							{refuseBelowBaseline}
							decoder.wrap(buffer, offset + {flyweights}.{headerClass}Decoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
							{decodeVariable}
							{record} value = new {record}(
									{decodeFields}
							);
							lastDecodedLength = {flyweights}.{headerClass}Decoder.ENCODED_LENGTH + decoder.encodedLength();
							return value;
						}

						@Override
						public boolean canDecode(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							return headerDecoder.schemaId() == {flyweights}.{message}Decoder.SCHEMA_ID
									&& headerDecoder.templateId() == {flyweights}.{message}Decoder.TEMPLATE_ID{atBaseline};
						}

						@Override
						public {headerRecord} decodeHeader(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							return readHeader(headerDecoder);
						}

						@Override
						public int lastDecodedLength() {
							return lastDecodedLength;
						}

						@Override
						public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							{decodedLength}
						}

						{headerMethods}
						{helpers}
					}
					"""
	);

	/** A message older than the baseline is not this codec's to decode. */
	static final Template AT_BASELINE = Template.of(" && headerDecoder.version() >= {baseline}");

	/**
	 * A message older than the baseline would read the null value of every field
	 * appended up to it into a primitive component; the baseline is the schema's
	 * own declaration, which no flyweight constant carries.
	 */
	static final Template REFUSE_BELOW_BASELINE = Template.of("""
			if (headerDecoder.version() < {baseline}) {
				throw new IllegalArgumentException(
						"{message} version " + headerDecoder.version() + " is below the baseline {baseline}");
			}""");

	/**
	 * Without a group or var-data the length is the header's block length, no walk
	 * needed.
	 */
	static final Template BLOCK_DECODED_LENGTH = Template
			.of("return {flyweights}.{headerClass}Decoder.ENCODED_LENGTH + headerDecoder.blockLength();");

	/**
	 * With either, the flyweight walks every group and var-data and restores its
	 * limit.
	 */
	static final Template WALKED_DECODED_LENGTH = Template.of(
			"""
					decoder.wrap(buffer, offset + {flyweights}.{headerClass}Decoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
					return {flyweights}.{headerClass}Decoder.ENCODED_LENGTH + decoder.sbeDecodedLength();"""
	);

	// ---- a union: one case per member, delegating to the member's codec

	static final Template UNION_CODEC = Template.of(
			"""
					package {packageName};

					/** Generated by sbe-buddy from the schema of this package; do not edit. */
					@javax.annotation.processing.Generated("net.concini.sbebuddy")
					public final class {codec} implements net.concini.sbebuddy.Codec<{union}, {headerRecord}> {

						private final {flyweights}.{headerClass}Decoder headerDecoder = new {flyweights}.{headerClass}Decoder();
						{fields}
						private net.concini.sbebuddy.Codec<?, ?> lastDecoder = {first};

						public {codec}() {
						}

						@Override
						public int encodedLength({union} value) {
							if (value == null) {
								throw new IllegalArgumentException("value is required");
							}
							return switch (value) {
								{encodedLengths}
							};
						}

						@Override
						public int encode({union} value, org.agrona.MutableDirectBuffer buffer, int offset) {
							if (value == null) {
								throw new IllegalArgumentException("value is required");
							}
							return switch (value) {
								{encodes}
							};
						}

						@Override
						public int encode({union} value, {headerRecord} header, org.agrona.MutableDirectBuffer buffer, int offset) {
							if (value == null) {
								throw new IllegalArgumentException("value is required");
							}
							return switch (value) {
								{headerEncodes}
							};
						}

						@Override
						public {union} decode(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							if (headerDecoder.schemaId() != {firstDecoder}.SCHEMA_ID) {
								throw notOurs();
							}
							return switch (headerDecoder.templateId()) {
								{decodes}
								default -> throw notOurs();
							};
						}

						@Override
						public boolean canDecode(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							return switch (headerDecoder.templateId()) {
								{canDecodes}
								default -> false;
							};
						}

						@Override
						public {headerRecord} decodeHeader(org.agrona.DirectBuffer buffer, int offset) {
							return {first}.decodeHeader(buffer, offset);
						}

						@Override
						public int lastDecodedLength() {
							return lastDecoder.lastDecodedLength();
						}

						@Override
						public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							if (headerDecoder.schemaId() != {firstDecoder}.SCHEMA_ID) {
								throw notOurs();
							}
							return switch (headerDecoder.templateId()) {
								{decodedLengths}
								default -> throw notOurs();
							};
						}

						private IllegalArgumentException notOurs() {
							return new IllegalArgumentException("not a {unionName}: schemaId " + headerDecoder.schemaId() + ", templateId "
									+ headerDecoder.templateId() + "; its templates are " + {templateIds});
						}
					}
					"""
	);

	static final Template UNION_CODEC_FIELD = Template.of("private final {codec} {field} = new {codec}();");

	static final Template UNION_ENCODED_LENGTH_CASE = Template
			.of("case {record} member -> {field}.encodedLength(member);");

	static final Template UNION_ENCODE_CASE = Template
			.of("case {record} member -> {field}.encode(member, buffer, offset);");

	static final Template UNION_HEADER_ENCODE_CASE = Template
			.of("case {record} member -> {field}.encode(member, header, buffer, offset);");

	/** The decoding codec is remembered, so {@code lastDecodedLength} asks it. */
	static final Template UNION_DECODE_CASE = Template.of("""
			case {decoder}.TEMPLATE_ID -> {
				lastDecoder = {field};
				yield {field}.decode(buffer, offset);
			}""");

	static final Template UNION_DECODED_LENGTH_CASE = Template
			.of("case {decoder}.TEMPLATE_ID -> {field}.decodedLength(buffer, offset);");

	static final Template UNION_CAN_DECODE_CASE = Template
			.of("case {decoder}.TEMPLATE_ID -> {field}.canDecode(buffer, offset);");

	static final Template UNION_TEMPLATE_ID = Template.of("{decoder}.TEMPLATE_ID");

	// ---- the header: read whole, its own members written from a header or as
	// null

	static final Template WRITE_NULL_HEADER_CALL = Template.of("writeNullHeader(headerEncoder);");

	static final Template WRITE_HEADER_CALL = Template.of("writeHeader(header, headerEncoder);");

	static final Template READ_HEADER = Template.of("""
			private {record} readHeader({decoder} decoder) {
				return new {record}(
						{members}
				);
			}""");

	/**
	 * The parameters bear the message's names, so every field shape serves a header
	 * member as it is.
	 */
	static final Template WRITE_HEADER = Template.of("""
			private void writeHeader({record} value, {encoder} encoder) {
				{members}
			}""");

	static final Template WRITE_NULL_HEADER = Template.of("""
			private static void writeNullHeader({encoder} encoder) {
				{members}
			}""");

	// ---- a binding: the component mapped before the flyweight and after it,
	// handed the component's context

	/** A group or var-data read into its local, handed to the record as it is. */
	static final Template LOCAL = Template.of("{component}");

	/** A group or var-data read into its local, bound on its way to the record. */
	static final Template BOUND_LOCAL = Template.of("{binding}.fromWire({component}, {context})");

	/** Absent from an older message, it stays null past the binding. */
	static final Template BOUND_ADDED_LOCAL = Template
			.of("{component} == null ? null : {binding}.fromWire({component}, {context})");

	// ---- a group: three methods per group, keyed by its path, over its own
	// classes

	static final Template ENCODE_GROUP_FIELD = Template.of("write{path}({source}, encoder);");

	static final Template DECODE_GROUP = Template
			.of("java.util.List<{record}> {component} = read{path}(decoder.{property}());");

	/**
	 * Absent below the acting version, as a field is; count zero is never read.
	 * sbe-tool names the group's static methods after its decoder class,
	 * {@code legsDecoderSinceVersion()}.
	 */
	static final Template DECODE_ADDED_GROUP = Template.of(
			"java.util.List<{record}> {component} = decoder.actingVersion() < {decoder}.{addedSince}() ? null : read{path}(decoder.{property}());"
	);

	/**
	 * The entry's shapes are the message's, over the group's classes: the loop's
	 * variable and local bear the names the field templates use, and the methods
	 * are the codec's own, since a bound field reaches its binding. The body the
	 * group is in sizes it.
	 */
	static final Template WRITE_GROUP = Template.of("""
			private void write{path}(java.util.List<{record}> entries, {parent} parent) {
				{encoder} encoder = parent.{property}Count(entries.size());
				for ({record} value : entries) {
					encoder.next();
					{body}
				}
			}""");

	static final Template READ_GROUP = Template.of("""
			private java.util.List<{record}> read{path}({decoder} decoder) {
				java.util.List<{record}> entries = new java.util.ArrayList<>(decoder.count());
				while (decoder.hasNext()) {
					decoder.next();
					{reads}
					entries.add(new {record}(
							{arguments}
					));
				}
				return entries;
			}""");

	/** The dimensions and the entries, without encoding; null has no wire form. */
	static final Template GROUP_LENGTH = Template.of("""
			private int {length}(java.util.List<{record}> entries) {
				if (entries == null) {
					throw new IllegalArgumentException("{component} is required");
				}
				return {encoder}.sbeHeaderSize() + entries.size() * {encoder}.sbeBlockLength();
			}""");

	static final Template NESTED_GROUP_LENGTH = Template.of("""
			private int {length}(java.util.List<{record}> entries) {
				if (entries == null) {
					throw new IllegalArgumentException("{component} is required");
				}
				int length = {encoder}.sbeHeaderSize() + entries.size() * {encoder}.sbeBlockLength();
				for ({record} value : entries) {
					{terms}
				}
				return length;
			}""");

	// ---- var-data: methods per data member, keyed by its path, over its body's
	// classes; its bytes counted without encoding

	static final Template DECODE_DATA = Template.of("{face} {component} = {read};");

	/** Absent below the acting version, as a group is. */
	static final Template DECODE_ADDED_DATA = Template.of(
			"{face} {component} = decoder.actingVersion() < {decoder}.{addedSince}() ? null : {read};"
	);

	// ---- the shapes over them

	/** A group's or a data member's share of the length, at the message. */
	static final Template LENGTH_TERM = Template.of(" + {length}({source})");

	/** A group's or a data member's share of the length, in an entry. */
	static final Template NESTED_LENGTH_TERM = Template.of("length += {length}({source});");
}
