package net.concini.sbebuddy.generator;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.io.Writer;
import java.nio.ByteOrder;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.agrona.generation.DynamicPackageOutputManager;
import org.jspecify.annotations.Nullable;

import uk.co.real_logic.sbe.PrimitiveType;
import uk.co.real_logic.sbe.generation.java.JavaUtil;
import uk.co.real_logic.sbe.ir.Encoding;
import uk.co.real_logic.sbe.ir.GenerationUtil;
import uk.co.real_logic.sbe.ir.Ir;
import uk.co.real_logic.sbe.ir.Signal;
import uk.co.real_logic.sbe.ir.Token;

/**
 * Step 7 of the pipeline: one {@code <Msg>Codec} per message, from the IR the
 * way {@code JavaGenerator} reads it and from {@link Annotated} for the Java
 * face, written from text-block templates. Every flyweight member it calls is
 * named through {@link JavaUtil}, so it calls what was generated. A construct
 * the codec does not cover yet is a problem naming the message; nothing is
 * skipped silently.
 */
public final class CodecEmitter {

	private static final String STANDARD_HEADER = "messageHeader";

	private static final Template CODEC = Template.of(
			"""
					package {package};

					/** Generated by sbe-buddy from the schema of this package; do not edit. */
					@javax.annotation.processing.Generated("net.concini.sbebuddy")
					public final class {codec} implements net.concini.sbebuddy.Codec<{record}> {

						private final {flyweights}.{header}Encoder headerEncoder = new {flyweights}.{header}Encoder();
						private final {flyweights}.{header}Decoder headerDecoder = new {flyweights}.{header}Decoder();
						private final {flyweights}.{message}Encoder encoder = new {flyweights}.{message}Encoder();
						private final {flyweights}.{message}Decoder decoder = new {flyweights}.{message}Decoder();
						private int lastDecodedLength;

						public {codec}() {
						}

						@Override
						public int encodedLength({record} value) {
							return {flyweights}.{header}Encoder.ENCODED_LENGTH + {flyweights}.{message}Encoder.BLOCK_LENGTH;
						}

						@Override
						public int encode({record} value, org.agrona.MutableDirectBuffer buffer, int offset) {
							encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
							{encodeFields}
							return {flyweights}.{header}Encoder.ENCODED_LENGTH + encoder.encodedLength();
						}

						@Override
						public {record} decode(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							if (headerDecoder.schemaId() != {flyweights}.{message}Decoder.SCHEMA_ID
									|| headerDecoder.templateId() != {flyweights}.{message}Decoder.TEMPLATE_ID) {
								throw new IllegalArgumentException(
										"not a {message}: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
							}
							{refuseBelowBaseline}
							decoder.wrap(buffer, offset + {flyweights}.{header}Decoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
							{record} value = new {record}(
									{decodeFields}
							);
							lastDecodedLength = {flyweights}.{header}Decoder.ENCODED_LENGTH + decoder.encodedLength();
							return value;
						}

						@Override
						public int lastDecodedLength() {
							return lastDecodedLength;
						}

						@Override
						public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							return {flyweights}.{header}Decoder.ENCODED_LENGTH + headerDecoder.blockLength();
						}
						{declaredTypes}
					}
					"""
	);

	/**
	 * A message older than the baseline would read the null value of every field
	 * appended up to it into a primitive component; the baseline is the schema's
	 * own declaration, which no flyweight constant carries.
	 */
	private static final Template REFUSE_BELOW_BASELINE = Template.of("""
			if (headerDecoder.version() < {baseline}) {
				throw new IllegalArgumentException(
						"{message} version " + headerDecoder.version() + " is below the baseline {baseline}");
			}""");

	// ---- a primitive field

	private static final Template ENCODE_FIELD = Template.of("encoder.{property}(value.{component}());");

	private static final Template ENCODE_OPTIONAL_FIELD = Template.of(
			"encoder.{property}(value.{component}() == null ? {flyweights}.{message}Encoder.{property}NullValue() : value.{component}());"
	);

	private static final Template DECODE_FIELD = Template.of("decoder.{property}()");

	private static final Template IS_NULL = Template.of(
			"decoder.{property}() == {flyweights}.{message}Decoder.{property}NullValue()"
	);

	/** The null value of the floats is NaN, which == never matches. */
	private static final Template IS_NULL_FLOATING = Template.of(
			"{box}.compare(decoder.{property}(), {flyweights}.{message}Decoder.{property}NullValue()) == 0"
	);

	// ---- a field of an enum

	private static final Template ENCODE_ENUM_FIELD = Template
			.of("encoder.{property}(encode{enum}(value.{component}()));");

	private static final Template ENCODE_OPTIONAL_ENUM_FIELD = Template.of(
			"encoder.{property}(value.{component}() == null ? {flyweights}.{enum}.NULL_VAL : encode{enum}(value.{component}()));"
	);

	private static final Template DECODE_ENUM_FIELD = Template.of("decode{enum}(decoder.{property}Raw())");

	private static final Template IS_NULL_ENUM = Template.of(
			"decoder.{property}Raw() == {flyweights}.{enum}.NULL_VAL.value()"
	);

	// ---- a field of a set

	private static final Template ENCODE_SET_FIELD = Template
			.of("encode{set}(value.{component}(), encoder.{property}());");

	private static final Template DECODE_SET_FIELD = Template.of("decode{set}(decoder.{property}())");

	// ---- the shapes over them

	/** A component that may be null on a required field: null has no wire form. */
	private static final Template ENCODE_CHECKED_FIELD = Template.of("""
			if (value.{component}() == null) {
				throw new IllegalArgumentException("{component} is required");
			}
			{call}""");

	private static final Template DECODE_OPTIONAL_FIELD = Template.of("{isNull} ? null : {read}");

	/**
	 * Absent below the acting version, decided on the version and never on the null
	 * value, which a required field may legitimately hold.
	 */
	private static final Template DECODE_ADDED_FIELD = Template.of(
			"decoder.actingVersion() < {flyweights}.{message}Decoder.{property}SinceVersion() ? null : {read}"
	);

	// ---- an enum's mapping, one pair per codec

	private static final Template ENCODE_ENUM = Template.of("""
			private static {flyweights}.{enum} encode{enum}({javaEnum} value) {
				return switch (value) {
					{cases}
				};
			}""");

	private static final Template ENUM_TO_WIRE = Template.of("case {constant} -> {flyweights}.{enum}.{wireConstant};");

	private static final Template UNKNOWN_TO_WIRE = Template.of(
			"case {constant} -> throw new IllegalArgumentException(\"{enum}.{constant} has no wire form\");"
	);

	private static final Template DECODE_ENUM = Template.of("""
			private static {javaEnum} decode{enum}({face} raw) {
				return switch (raw) {
					{cases}
				};
			}""");

	private static final Template WIRE_TO_ENUM = Template.of("case {literal} -> {javaEnum}.{constant};");

	private static final Template WIRE_TO_UNKNOWN = Template.of("default -> {javaEnum}.{constant};");

	private static final Template WIRE_TO_NOTHING = Template.of(
			"default -> throw new IllegalArgumentException(\"{enum} has no value \" + raw);"
	);

	// ---- a set's mapping, one pair per codec

	private static final Template ENCODE_SET = Template.of("""
			private static void encode{set}(java.util.Set<{javaEnum}> value, {flyweights}.{set}Encoder wire) {
				wire.clear();
				{choices}
			}""");

	private static final Template ENCODE_CHOICE = Template.of("wire.{choice}(value.contains({javaEnum}.{constant}));");

	/** A bit no choice names has nowhere to go in a Set of the enum. */
	private static final Template DECODE_SET = Template.of("""
			private static java.util.Set<{javaEnum}> decode{set}({flyweights}.{set}Decoder wire) {
				if ((wire.getRaw() & ~({knownBits})) != 0) {
					throw new IllegalArgumentException("{set} has a bit no choice names: " + wire.getRaw());
				}
				java.util.Set<{javaEnum}> value = java.util.EnumSet.noneOf({javaEnum}.class);
				{choices}
				return value;
			}""");

	private static final Template KNOWN_BIT = Template.of("1L << {bit}");

	private static final Template DECODE_CHOICE = Template.of("""
			if (wire.{choice}()) {
				value.add({javaEnum}.{constant});
			}""");

	private final Ir ir;
	private final Annotated annotated;
	private final List<Problem> problems = new ArrayList<>();

	private CodecEmitter(Ir ir, Annotated annotated) {
		this.ir = ir;
		this.annotated = annotated;
	}

	/**
	 * Writes each message's codec through the output under the schema package, or
	 * writes nothing and returns the problems: a construct the codec lacks in any
	 * message is collected, never a partial write. An output that fails to write is
	 * an {@link UncheckedIOException}.
	 */
	public static List<Problem> emit(Ir ir, Annotated annotated, DynamicPackageOutputManager output) {
		CodecEmitter emitter = new CodecEmitter(ir, annotated);
		Map<String, String> sources = new LinkedHashMap<>();
		for (Annotated.Message message : annotated.messages()) {
			String source = emitter.codec(message);
			if (source != null) {
				sources.put(message.javaName() + "Codec", source);
			}
		}
		if (!emitter.problems.isEmpty()) {
			return List.copyOf(emitter.problems);
		}
		for (Map.Entry<String, String> source : sources.entrySet()) {
			// Before every file: Agrona's manager falls back to the first package it
			// was given when a writer closes.
			output.setPackageName(annotated.packageName());
			try (Writer writer = output.createOutput(source.getKey())) {
				writer.write(source.getValue());
			} catch (IOException e) {
				throw new UncheckedIOException(e);
			}
		}
		return List.of();
	}

	/**
	 * How one field reaches the wire: the plain call each way, and the optional
	 * forms where the wire has a null value for it.
	 */
	private record Access(String encode, @Nullable String encodeOptional, String decode, @Nullable String isNull) {
	}

	/**
	 * The codec's source, or null with a problem for a construct not covered yet.
	 */
	private @Nullable String codec(Annotated.Message message) {
		String header = ir.headerStructure().tokens().get(0).name();
		if (!header.equals(STANDARD_HEADER)) {
			return refuse(message, "a header type of its own");
		}
		if (ir.byteOrder() != ByteOrder.LITTLE_ENDIAN) {
			return refuse(message, "big-endian byte order");
		}
		List<Token> tokens = ir.getMessage(message.id());
		List<Token> fields = new ArrayList<>();
		List<Token> groups = new ArrayList<>();
		List<Token> varData = new ArrayList<>();
		int index = GenerationUtil.collectFields(tokens, 1, fields);
		index = GenerationUtil.collectGroups(tokens, index, groups);
		GenerationUtil.collectVarData(tokens, index, varData);
		if (!groups.isEmpty()) {
			return refuse(message, "a group");
		}
		if (!varData.isEmpty()) {
			return refuse(message, "var-data");
		}
		String flyweights = ir.applicableNamespace();
		String messageClass = JavaUtil.formatClassName(tokens.get(0).name());
		List<String> encodeFields = new ArrayList<>();
		List<String> decodeFields = new ArrayList<>();
		Map<String, String> declaredTypes = new LinkedHashMap<>();
		for (int i = 0; i < fields.size(); i += fields.get(i).componentTokenCount()) {
			Token field = fields.get(i);
			Token type = fields.get(i + 1);
			if (field.encoding().presence() == Encoding.Presence.CONSTANT) {
				return refuse(message, "a constant");
			}
			String unsupported = unsupported(type);
			if (unsupported != null) {
				return refuse(message, unsupported);
			}
			Annotated.Field component = component(message, field);
			String property = JavaUtil.formatPropertyName(field.name());
			List<Token> typeTokens = fields.subList(i + 1, i + 1 + type.componentTokenCount());
			Access access = switch (type.signal()) {
				case ENCODING -> primitiveAccess(type, flyweights, messageClass, property, component.javaName());
				case BEGIN_ENUM -> enumAccess(
						typeTokens, enumOf(component), flyweights, messageClass, property, component.javaName(),
						declaredTypes
				);
				case BEGIN_SET ->
					setAccess(typeTokens, setOf(component), flyweights, property, component.javaName(), declaredTypes);
				default -> throw new IllegalStateException("a field of " + type.signal());
			};
			encodeFields.add(encodeField(field, component, access));
			decodeFields.add(decodeField(field, flyweights, messageClass, property, access));
		}
		int baseline = annotated.baselineVersion();
		return CODEC.fill(
				"package", annotated.packageName(),
				"codec", message.javaName() + "Codec",
				"record", annotated.packageName() + "." + message.javaName(),
				"flyweights", flyweights,
				"header", JavaUtil.formatClassName(header),
				"message", messageClass,
				"encodeFields", String.join("\n", encodeFields),
				"refuseBelowBaseline", baseline == 0
						? ""
						: REFUSE_BELOW_BASELINE.fill("message", messageClass, "baseline", String.valueOf(baseline)),
				"decodeFields", String.join(",\n", decodeFields),
				"declaredTypes", declaredTypes.isEmpty() ? "" : "\n" + String.join("\n\n", declaredTypes.values())
		);
	}

	/**
	 * The encode side is decided from the component: an optional field takes the
	 * null value for null, any other component that may be null refuses it.
	 */
	private static String encodeField(Token field, Annotated.Field component, Access access) {
		if (optional(field)) {
			if (access.encodeOptional() == null) {
				throw new IllegalStateException(component.javaName() + " is optional without a null value");
			}
			return access.encodeOptional();
		}
		if (component.javaType() instanceof Annotated.Primitive primitive && !primitive.boxed()) {
			return access.encode();
		}
		return ENCODE_CHECKED_FIELD.fill("component", component.javaName(), "call", access.encode());
	}

	/**
	 * The decode side is decided from the wire: the null value for an optional
	 * field, whatever its version, since below the acting version the getter
	 * returns it; the version for a required field added above the baseline.
	 */
	private String decodeField(Token field, String flyweights, String messageClass, String property, Access access) {
		if (optional(field)) {
			if (access.isNull() == null) {
				throw new IllegalStateException(field.name() + " is optional without a null value");
			}
			return DECODE_OPTIONAL_FIELD.fill("isNull", access.isNull(), "read", access.decode());
		}
		if (field.version() > annotated.baselineVersion()) {
			return DECODE_ADDED_FIELD.fill(
					"flyweights", flyweights, "message", messageClass, "property", property, "read", access.decode()
			);
		}
		return access.decode();
	}

	private static Access primitiveAccess(
			Token type, String flyweights, String messageClass, String property, String component
	) {
		return new Access(
				ENCODE_FIELD.fill("property", property, "component", component),
				ENCODE_OPTIONAL_FIELD.fill(
						"property", property, "component", component, "flyweights", flyweights, "message", messageClass
				),
				DECODE_FIELD.fill("property", property),
				isNull(type, flyweights, messageClass, property)
		);
	}

	private static String isNull(Token type, String flyweights, String messageClass, String property) {
		PrimitiveType primitive = type.encoding().primitiveType();
		if (primitive == PrimitiveType.FLOAT || primitive == PrimitiveType.DOUBLE) {
			// The box is the one name that neither the IR nor JavaUtil holds.
			String box = primitive == PrimitiveType.FLOAT ? "Float" : "Double";
			return IS_NULL_FLOATING
					.fill("box", box, "property", property, "flyweights", flyweights, "message", messageClass);
		}
		return IS_NULL.fill("property", property, "flyweights", flyweights, "message", messageClass);
	}

	private static Access enumAccess(
			List<Token> tokens, Annotated.Enum enumeration, String flyweights, String messageClass, String property,
			String component, Map<String, String> declaredTypes
	) {
		String enumClass = JavaUtil.formatClassName(tokens.get(0).applicableTypeName());
		declaredTypes.computeIfAbsent(
				tokens.get(0).applicableTypeName(), name -> enumPair(tokens, enumeration, flyweights, enumClass)
		);
		return new Access(
				ENCODE_ENUM_FIELD.fill("property", property, "enum", enumClass, "component", component),
				ENCODE_OPTIONAL_ENUM_FIELD
						.fill(
								"property", property, "component", component, "flyweights", flyweights, "enum",
								enumClass
						),
				DECODE_ENUM_FIELD.fill("enum", enumClass, "property", property),
				IS_NULL_ENUM.fill("property", property, "flyweights", flyweights, "enum", enumClass)
		);
	}

	/**
	 * The wire value is read raw and mapped by the valid values' text, never
	 * through the flyweight's enum, so an unknown value is ours to decide: the
	 * constant the enum designates, or an exception.
	 */
	private static String enumPair(
			List<Token> tokens, Annotated.Enum enumeration, String flyweights, String enumClass
	) {
		PrimitiveType primitive = tokens.get(0).encoding().primitiveType();
		List<String> toWire = new ArrayList<>();
		List<String> fromWire = new ArrayList<>();
		for (Token value : tokens) {
			if (value.signal() != Signal.VALID_VALUE) {
				continue;
			}
			String constant = validValue(enumeration, value.name()).javaName();
			toWire.add(
					ENUM_TO_WIRE.fill(
							"constant", constant, "flyweights", flyweights, "enum", enumClass,
							"wireConstant", JavaUtil.formatForJavaKeyword(value.name())
					)
			);
			fromWire.add(
					WIRE_TO_ENUM.fill(
							"literal", JavaUtil.generateLiteral(primitive, value.encoding().constValue().toString()),
							"javaEnum", enumeration.qualifiedName(), "constant", constant
					)
			);
		}
		String unknown = enumeration.unknownValue();
		if (unknown == null) {
			fromWire.add(WIRE_TO_NOTHING.fill("enum", enumClass));
		} else {
			toWire.add(UNKNOWN_TO_WIRE.fill("constant", unknown, "enum", enumClass));
			fromWire.add(WIRE_TO_UNKNOWN.fill("javaEnum", enumeration.qualifiedName(), "constant", unknown));
		}
		return String.join(
				"\n\n",
				ENCODE_ENUM.fill(
						"flyweights", flyweights, "enum", enumClass, "javaEnum", enumeration.qualifiedName(),
						"cases", String.join("\n", toWire)
				),
				DECODE_ENUM.fill(
						"javaEnum", enumeration.qualifiedName(), "enum", enumClass,
						"face", JavaUtil.javaTypeName(primitive), "cases", String.join("\n", fromWire)
				)
		);
	}

	private static Access setAccess(
			List<Token> tokens, Annotated.Set set, String flyweights, String property, String component,
			Map<String, String> declaredTypes
	) {
		String setClass = JavaUtil.formatClassName(tokens.get(0).applicableTypeName());
		declaredTypes.computeIfAbsent(
				tokens.get(0).applicableTypeName(), name -> setPair(tokens, set, flyweights, setClass)
		);
		return new Access(
				ENCODE_SET_FIELD.fill("set", setClass, "component", component, "property", property),
				null,
				DECODE_SET_FIELD.fill("set", setClass, "property", property),
				null
		);
	}

	private static String setPair(List<Token> tokens, Annotated.Set set, String flyweights, String setClass) {
		List<String> encodeChoices = new ArrayList<>();
		List<String> decodeChoices = new ArrayList<>();
		List<String> knownBits = new ArrayList<>();
		for (Token choice : tokens) {
			if (choice.signal() != Signal.CHOICE) {
				continue;
			}
			String property = JavaUtil.formatPropertyName(choice.name());
			String constant = choice(set, choice.name()).javaName();
			encodeChoices
					.add(ENCODE_CHOICE.fill("choice", property, "javaEnum", set.qualifiedName(), "constant", constant));
			decodeChoices
					.add(DECODE_CHOICE.fill("choice", property, "javaEnum", set.qualifiedName(), "constant", constant));
			knownBits.add(KNOWN_BIT.fill("bit", choice.encoding().constValue().toString()));
		}
		return String.join(
				"\n\n",
				ENCODE_SET.fill(
						"set", setClass, "javaEnum", set.qualifiedName(), "flyweights", flyweights,
						"choices", String.join("\n", encodeChoices)
				),
				DECODE_SET.fill(
						"javaEnum", set.qualifiedName(), "set", setClass, "flyweights", flyweights,
						"knownBits", String.join(" | ", knownBits), "choices", String.join("\n", decodeChoices)
				)
		);
	}

	private static boolean optional(Token field) {
		return field.encoding().presence() == Encoding.Presence.OPTIONAL;
	}

	/**
	 * What the codec cannot do with the field's type yet, or null for a primitive,
	 * an enum or a set.
	 */
	private static @Nullable String unsupported(Token type) {
		return switch (type.signal()) {
			case BEGIN_ENUM, BEGIN_SET -> null;
			case BEGIN_COMPOSITE -> "a composite";
			case ENCODING -> encodingUnsupported(type);
			default -> throw new IllegalStateException("a field of " + type.signal());
		};
	}

	private static @Nullable String encodingUnsupported(Token type) {
		if (type.arrayLength() > 1) {
			return "an array";
		}
		if (type.encoding().presence() == Encoding.Presence.CONSTANT) {
			return "a constant";
		}
		return null;
	}

	private @Nullable String refuse(Annotated.Message message, String construct) {
		problems.add(new Problem(message, "no codec for " + construct + " yet; set codecs = false on @SbeSchema"));
		return null;
	}

	/** The record component the field token came from, by wire name. */
	private static Annotated.Field component(Annotated.Message message, Token field) {
		for (Annotated.Component component : message.components()) {
			if (component instanceof Annotated.Field candidate && wireName(candidate).equals(field.name())) {
				return candidate;
			}
		}
		throw new IllegalStateException(message.javaName() + " has no component for field " + field.name());
	}

	/**
	 * The field's enum, named by {@code type} or as the component's own type; the
	 * face rule saw to it.
	 */
	private static Annotated.Enum enumOf(Annotated.Field field) {
		if (field.type() instanceof Annotated.Enum enumeration) {
			return enumeration;
		}
		if (field.javaType() instanceof Annotated.Declared declared
				&& declared.declaration() instanceof Annotated.Enum enumeration) {
			return enumeration;
		}
		throw new IllegalStateException(field.javaName() + " is not a field of an enum");
	}

	private static Annotated.Set setOf(Annotated.Field field) {
		if (field.type() instanceof Annotated.Set set) {
			return set;
		}
		if (field.javaType() instanceof Annotated.SetOf setOf && setOf.declaration() instanceof Annotated.Set set) {
			return set;
		}
		throw new IllegalStateException(field.javaName() + " is not a field of a set");
	}

	private static Annotated.ValidValue validValue(Annotated.Enum enumeration, String wireName) {
		for (Annotated.ValidValue value : enumeration.values()) {
			if ((value.name().isEmpty() ? value.javaName() : value.name()).equals(wireName)) {
				return value;
			}
		}
		throw new IllegalStateException(enumeration.javaName() + " has no value " + wireName);
	}

	private static Annotated.Choice choice(Annotated.Set set, String wireName) {
		for (Annotated.Choice choice : set.choices()) {
			if ((choice.name().isEmpty() ? choice.javaName() : choice.name()).equals(wireName)) {
				return choice;
			}
		}
		throw new IllegalStateException(set.javaName() + " has no choice " + wireName);
	}

	private static String wireName(Annotated.Field field) {
		return field.name().isEmpty() ? field.javaName() : field.name();
	}
}
