package net.concini.sbebuddy.generator;

/**
 * The text of a codec over its message's reader and writer: the class, the
 * header, the lengths, the chain a block is written by, the groups and the
 * var-data. {@link CodecWriter} fills them from its model; a template's names
 * in braces are the only values it takes.
 */
final class CodecTemplates {

	private CodecTemplates() {
	}

	static final Template CODEC = Template.of(
			"""
					package {packageName};

					/** Generated by sbe-buddy from the schema of this package; do not edit. */
					@javax.annotation.processing.Generated("net.concini.sbebuddy")
					public final class {codec} implements net.concini.sbebuddy.Codec<{record}, {headerRecord}> {

						{contexts}
						private final {flyweights}.{headerClass}Decoder headerDecoder = new {flyweights}.{headerClass}Decoder();
						private final {reader} reader = new {reader}();
						private final {writer} writer = new {writer}();
						{bindings}
						private int lastDecodedLength;

						public {codec}() {
						}

						@Override
						public int encodedLength({record} value) {
							if (value == null) {
								throw new IllegalArgumentException("value is required");
							}
							return {flyweights}.{headerClass}Encoder.ENCODED_LENGTH + {flyweights}.{message}Encoder.BLOCK_LENGTH{variableLengths};
						}

						@Override
						public int encode({record} value, org.agrona.MutableDirectBuffer buffer, int offset) {
							if (value == null) {
								throw new IllegalArgumentException("value is required");
							}
							return encodeBody(value, writer.wrap(buffer, offset));
						}

						@Override
						public int encode({record} value, {headerRecord} header, org.agrona.MutableDirectBuffer buffer, int offset) {
							if (value == null) {
								throw new IllegalArgumentException("value is required");
							}
							if (header == null) {
								throw new IllegalArgumentException("header is required");
							}
							{first} first = writer.wrap(buffer, offset);
							{writeHeader}
							return encodeBody(value, first);
						}

						private int encodeBody({record} value, {first} first) {
							{encodeBlock}
						}

						@Override
						public {record} decode(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							if (headerDecoder.schemaId() != {flyweights}.{message}Decoder.SCHEMA_ID
									|| headerDecoder.templateId() != {flyweights}.{message}Decoder.TEMPLATE_ID) {
								throw new IllegalArgumentException(
										"not a {message}: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
							}
							{refuseBelowBaseline}
							{readBlock}
							{decodeVariable}
							{record} value = new {record}(
									{decodeFields}
							);
							lastDecodedLength = reader.decodedLength();
							return value;
						}

						@Override
						public boolean canDecode(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							return headerDecoder.schemaId() == {flyweights}.{message}Decoder.SCHEMA_ID
									&& headerDecoder.templateId() == {flyweights}.{message}Decoder.TEMPLATE_ID{atBaseline};
						}

						@Override
						public {headerRecord} decodeHeader(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							return readHeader(headerDecoder);
						}

						@Override
						public int lastDecodedLength() {
							return lastDecodedLength;
						}

						@Override
						public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
							return reader.wrap(buffer, offset).decodedLength();
						}

						{headerMethods}
						{groupMethods}
						{helpers}
					}
					"""
	);

	/** A message older than the baseline is not this codec's to decode. */
	static final Template AT_BASELINE = Template.of(" && headerDecoder.version() >= {baseline}");

	/**
	 * A message older than the baseline would read the null value of every field
	 * appended up to it into a primitive component; the baseline is the schema's
	 * own declaration, which no flyweight constant carries.
	 */
	static final Template REFUSE_BELOW_BASELINE = Template.of("""
			if (headerDecoder.version() < {baseline}) {
				throw new IllegalArgumentException(
						"{message} version " + headerDecoder.version() + " is below the baseline {baseline}");
			}""");

	// ---- reading a block: its stage from the reader, its components from the
	// stage's bound stage

	/**
	 * The root block arrives first, and its bound stage reads for the whole
	 * message.
	 */
	static final Template READ_ROOT_BLOCK = Template
			.of("{bound} block = (({stage}) reader.wrap(buffer, offset).next()).bound();");

	/** A root block carrying no component is passed, to reach what follows it. */
	static final Template PASS_ROOT_BLOCK = Template.of("reader.wrap(buffer, offset).next();");

	/** An entry's bound stage reads while the reader is inside the entry. */
	static final Template READ_ENTRY = Template.of("{bound} entry = (({stage}) reader.next()).bound();");

	static final Template PASS_ENTRY = Template.of("reader.next();");

	/**
	 * A component of the block, read through its bound stage, held in
	 * {@code variable}.
	 */
	static final Template READ_FIELD = Template.of("{variable}.{component}()");

	// ---- writing a block: the writer's chain, from the stage it starts at

	static final Template HOP = Template.of(".bound()");

	static final Template TAKE = Template.of(".{component}(value.{component}())");

	/** An entry's last step, which ends its statement. */
	static final Template LAST_TAKE = Template.of(".{component}(value.{component}());");

	/** A group opened where the chain stands, held for its entries. */
	static final Template OPEN_GROUP = Template.of("""
			{stage} {local} = {start}
					{calls}
					.{method}();""");

	static final Template OPEN_GROUP_AT_START = Template.of("{stage} {local} = {start}.{method}();");

	/** The message complete: its length. */
	static final Template CHAIN_LENGTH = Template.of("""
			return {start}
					{calls}
					.length();""");

	static final Template LENGTH_AT_START = Template.of("return {start}.length();");

	/** An entry complete, its group's to continue. */
	static final Template CHAIN_END = Template.of("""
			{start}
					{calls}""");

	static final Template END_AT_START = Template.of("{start};");

	/**
	 * A group's entries written, from the stage its {@code end()} hands back on.
	 */
	static final Template WRITE_GROUP_CALL = Template.of("write{path}({source}, {local})");

	/** An entry's chain starts at the group's next entry. */
	static final Template ENTRY_START = Template.of("group.entry()");

	static final Template MESSAGE_START = Template.of("first");

	/** A group has no wire form for null: refused before the block is written. */
	static final Template CHECK_GROUP = Template.of("""
			if (value.{component}() == null) {
				throw new IllegalArgumentException("{component} is required");
			}""");

	// ---- the header: read whole from any message, its own members written from
	// a header

	static final Template WRITE_HEADER_CALL = Template.of("writeHeader(header, writer.header());");

	static final Template READ_HEADER = Template.of("""
			private {record} readHeader({decoder} decoder) {
				return new {record}(
						{members}
				);
			}""");

	/**
	 * The parameters bear the leaves' names, so every field shape serves a header
	 * member as it is.
	 */
	static final Template WRITE_HEADER = Template.of("""
			private void writeHeader({record} value, {encoder} encoder) {
				{members}
			}""");

	// ---- a binding over a whole group, and one over var-data, which the codec
	// hands the writer's length

	/** A group or var-data read into its local, handed to the record as it is. */
	static final Template LOCAL = Template.of("{component}");

	/** A group read into its local, bound on its way to the record. */
	static final Template BOUND_LOCAL = Template.of("{binding}.fromWire({component}, {context})");

	/** Absent from an older message, it stays null past the binding. */
	static final Template BOUND_ADDED_LOCAL = Template
			.of("{component} == null ? null : {binding}.fromWire({component}, {context})");

	/**
	 * A group's entries as the writer takes them: through the binding over them.
	 */
	static final Template BOUND_GROUP_SOURCE = Template.of("{binding}.toWire(value.{component}(), {context})");

	/**
	 * A group's or var-data's view, whose null the length refuses: the binding is
	 * never handed null.
	 */
	static final Template NULLABLE_BOUND_COMPONENT = Template
			.of("value.{component}() == null ? null : {binding}.toWire(value.{component}(), {context})");

	// ---- a group: three methods per group, keyed by its path, over the reader's
	// and the writer's stages

	static final Template READ_GROUP_LOCAL = Template.of("java.util.List<{record}> {component} = read{path}();");

	/**
	 * Absent below the acting version, as a field is; the reader never comes to it.
	 * sbe-tool names the group's static methods after its decoder class,
	 * {@code legsDecoderSinceVersion()}.
	 */
	static final Template READ_ADDED_GROUP_LOCAL = Template.of(
			"java.util.List<{record}> {component} = reader.actingVersion() < {decoder}.{addedSince}() ? null : read{path}();"
	);

	/**
	 * The entries written each through the entry's chain, whose loop variable bears
	 * the name the chain reads the components from.
	 */
	static final Template WRITE_GROUP = Template.of("""
			private {after} write{path}(java.util.List<{record}> entries, {stage} group) {
				for ({record} value : entries) {
					{body}
				}
				return group.end();
			}""");

	/** As many entries as the header counts, each read before what it holds. */
	static final Template READ_GROUP = Template.of("""
			private java.util.List<{record}> read{path}() {
				{header} group = ({header}) reader.next();
				java.util.List<{record}> entries = new java.util.ArrayList<>(group.count());
				for (int i = 0; i < group.count(); i++) {
					{entry}
					{reads}
					entries.add(new {record}(
							{arguments}
					));
				}
				return entries;
			}""");

	/** The dimensions and the entries, without encoding; null has no wire form. */
	static final Template GROUP_LENGTH = Template.of("""
			private int {length}(java.util.List<{record}> entries) {
				if (entries == null) {
					throw new IllegalArgumentException("{component} is required");
				}
				return {encoder}.sbeHeaderSize() + entries.size() * {encoder}.sbeBlockLength();
			}""");

	static final Template NESTED_GROUP_LENGTH = Template.of("""
			private int {length}(java.util.List<{record}> entries) {
				if (entries == null) {
					throw new IllegalArgumentException("{component} is required");
				}
				int length = {encoder}.sbeHeaderSize() + entries.size() * {encoder}.sbeBlockLength();
				for ({record} value : entries) {
					{terms}
				}
				return length;
			}""");

	// ---- var-data: read through its stage's bound stage, counted by the writer

	static final Template READ_DATA_LOCAL = Template
			.of("{type} {component} = (({stage}) reader.next()).bound().value();");

	/** Absent below the acting version, as a group is. */
	static final Template READ_ADDED_DATA_LOCAL = Template.of(
			"{type} {component} = reader.actingVersion() < {decoder}.{addedSince}() ? null : (({stage}) reader.next()).bound().value();"
	);

	// ---- the lengths over them

	/** A group's or a data member's share of the length, at the message. */
	static final Template LENGTH_TERM = Template.of(" + {length}({source})");

	/** A group's or a data member's share of the length, in an entry. */
	static final Template NESTED_LENGTH_TERM = Template.of("length += {length}({source});");
}
