package net.concini.sbebuddy.generator;

/**
 * The text of a codec, one template per piece, grouped by the shape it writes.
 * {@link CodecWriter} fills them from a {@link CodecModel}; a template's names
 * in braces are the only values it takes.
 */
final class CodecTemplates {

	private CodecTemplates() {
	}

	static final Template CODEC = Template.of(
			"""
					package {package};

					/** Generated by sbe-buddy from the schema of this package; do not edit. */
					@javax.annotation.processing.Generated("net.concini.sbebuddy")
					public final class {codec} implements net.concini.sbebuddy.Codec<{record}> {

						private final {flyweights}.{header}Encoder headerEncoder = new {flyweights}.{header}Encoder();
						private final {flyweights}.{header}Decoder headerDecoder = new {flyweights}.{header}Decoder();
						private final {flyweights}.{message}Encoder encoder = new {flyweights}.{message}Encoder();
						private final {flyweights}.{message}Decoder decoder = new {flyweights}.{message}Decoder();
						{bindings}
						private int lastDecodedLength;

						public {codec}() {
						}

						@Override
						public int encodedLength({record} value) {
							return {flyweights}.{header}Encoder.ENCODED_LENGTH + {flyweights}.{message}Encoder.BLOCK_LENGTH{groupLengths};
						}

						@Override
						public int encode({record} value, org.agrona.MutableDirectBuffer buffer, int offset) {
							encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
							{encodeFields}
							return {flyweights}.{header}Encoder.ENCODED_LENGTH + encoder.encodedLength();
						}

						@Override
						public {record} decode(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							if (headerDecoder.schemaId() != {flyweights}.{message}Decoder.SCHEMA_ID
									|| headerDecoder.templateId() != {flyweights}.{message}Decoder.TEMPLATE_ID) {
								throw new IllegalArgumentException(
										"not a {message}: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
							}
							{refuseBelowBaseline}
							decoder.wrap(buffer, offset + {flyweights}.{header}Decoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
							{decodeGroups}
							{record} value = new {record}(
									{decodeFields}
							);
							lastDecodedLength = {flyweights}.{header}Decoder.ENCODED_LENGTH + decoder.encodedLength();
							return value;
						}

						@Override
						public int lastDecodedLength() {
							return lastDecodedLength;
						}

						@Override
						public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							{decodedLength}
						}
						{helpers}
					}
					"""
	);

	/**
	 * A message older than the baseline would read the null value of every field
	 * appended up to it into a primitive component; the baseline is the schema's
	 * own declaration, which no flyweight constant carries.
	 */
	static final Template REFUSE_BELOW_BASELINE = Template.of("""
			if (headerDecoder.version() < {baseline}) {
				throw new IllegalArgumentException(
						"{message} version " + headerDecoder.version() + " is below the baseline {baseline}");
			}""");

	/** Without a group the length is the header's block length, no walk needed. */
	static final Template BLOCK_DECODED_LENGTH = Template
			.of("return {flyweights}.{header}Decoder.ENCODED_LENGTH + headerDecoder.blockLength();");

	/** With one, the flyweight walks every group and restores its limit. */
	static final Template WALKED_DECODED_LENGTH = Template.of(
			"""
					decoder.wrap(buffer, offset + {flyweights}.{header}Decoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
					return {flyweights}.{header}Decoder.ENCODED_LENGTH + decoder.sbeDecodedLength();"""
	);

	// ---- a primitive field

	static final Template ENCODE_FIELD = Template.of("encoder.{property}({source});");

	static final Template ENCODE_OPTIONAL_FIELD = Template.of(
			"encoder.{property}(value.{component}() == null ? {encoder}.{property}NullValue() : {source});"
	);

	static final Template DECODE_FIELD = Template.of("decoder.{property}()");

	static final Template IS_NULL = Template.of("decoder.{property}() == {decoder}.{property}NullValue()");

	/** The null value of the floats is NaN, which == never matches. */
	static final Template IS_NULL_FLOATING = Template.of(
			"{box}.compare(decoder.{property}(), {decoder}.{property}NullValue()) == 0"
	);

	// ---- a field of an enum

	static final Template ENCODE_ENUM_FIELD = Template
			.of("encoder.{property}(encode{enum}(value.{component}()));");

	static final Template ENCODE_OPTIONAL_ENUM_FIELD = Template.of(
			"encoder.{property}(value.{component}() == null ? {flyweights}.{enum}.NULL_VAL : encode{enum}(value.{component}()));"
	);

	static final Template DECODE_ENUM_FIELD = Template.of("decode{enum}(decoder.{property}Raw())");

	static final Template IS_NULL_ENUM = Template.of(
			"decoder.{property}Raw() == {flyweights}.{enum}.NULL_VAL.value()"
	);

	// ---- a field of a set

	static final Template ENCODE_SET_FIELD = Template
			.of("encode{set}(value.{component}(), encoder.{property}());");

	static final Template DECODE_SET_FIELD = Template.of("decode{set}(decoder.{property}())");

	// ---- a field no component carries: the null value out, nothing back

	static final Template ENCODE_UNMAPPED_FIELD = Template
			.of("encoder.{property}({encoder}.{property}NullValue());");

	static final Template ENCODE_UNMAPPED_ENUM_FIELD = Template
			.of("encoder.{property}({flyweights}.{enum}.NULL_VAL);");

	static final Template ENCODE_UNMAPPED_SET_FIELD = Template.of("encoder.{property}().clear();");

	// ---- a char string: the flyweight's own String form, checked first

	static final Template ENCODE_STRING_FIELD = Template.of(
			"encoder.{property}(ascii({source}, {encoder}.{property}Length(), \"{component}\"));"
	);

	/**
	 * The flyweight writes a char above 127 as '?' and throws its own exception
	 * over the length; the codec refuses both first.
	 */
	static final Template ASCII = Template.of("""
			private static String ascii(String value, int length, String field) {
				if (value.length() > length) {
					throw new IllegalArgumentException(field + " is longer than " + length + ": " + value);
				}
				for (int i = 0; i < value.length(); i++) {
					if (value.charAt(i) > 127) {
						throw new IllegalArgumentException(field + " is not ASCII: " + value);
					}
				}
				return value;
			}""");

	// ---- a fixed-length array: a pair per field, over the index accessors

	static final Template ENCODE_ARRAY_FIELD = Template.of("write{field}({source}, encoder);");

	static final Template DECODE_ARRAY_FIELD = Template.of("read{field}(decoder)");

	static final Template WRITE_ARRAY = Template.of("""
			private static void write{field}({face}[] value, {encoder} encoder) {
				if (value.length != {encoder}.{property}Length()) {
					throw new IllegalArgumentException(
							"{component} must be " + {encoder}.{property}Length() + " long, not " + value.length);
				}
				for (int i = 0; i < value.length; i++) {
					encoder.{property}(i, value[i]);
				}
			}""");

	static final Template READ_ARRAY = Template.of("""
			private static {face}[] read{field}({decoder} decoder) {
				{face}[] value = new {face}[{decoder}.{property}Length()];
				for (int i = 0; i < value.length; i++) {
					value[i] = decoder.{property}(i);
				}
				return value;
			}""");

	/**
	 * A uint8 array has bulk accessors over byte[], where its index accessors widen
	 * to short.
	 */
	static final Template WRITE_BYTES = Template.of("""
			private static void write{field}(byte[] value, {encoder} encoder) {
				if (value.length != {encoder}.{property}Length()) {
					throw new IllegalArgumentException(
							"{component} must be " + {encoder}.{property}Length() + " long, not " + value.length);
				}
				encoder.put{field}(value, 0, value.length);
			}""");

	static final Template READ_BYTES = Template.of("""
			private static byte[] read{field}({decoder} decoder) {
				byte[] value = new byte[{decoder}.{property}Length()];
				decoder.get{field}(value, 0, value.length);
				return value;
			}""");

	// ---- a constant: no bytes; the record must agree with the schema

	static final Template CHECK_CONSTANT_FIELD = Template.of("""
			if ({source} != encoder.{property}()) {
				throw new IllegalArgumentException("{component} is the constant " + encoder.{property}());
			}""");

	static final Template CHECK_CONSTANT_STRING_FIELD = Template.of("""
			if (!encoder.{property}().equals({source})) {
				throw new IllegalArgumentException("{component} is the constant " + encoder.{property}());
			}""");

	static final Template CHECK_CONSTANT_ENUM_FIELD = Template.of("""
			if (value.{component}() != {javaEnum}.{constant}) {
				throw new IllegalArgumentException("{component} is the constant {constant}");
			}""");

	// ---- a binding: the component mapped before the flyweight and after it

	static final Template BINDING_FIELD = Template.of("private final {binding} {name} = new {binding}();");

	/** What the flyweight is handed: the component, or the binding's view of it. */
	static final Template SOURCE = Template.of("value.{component}()");

	static final Template BOUND_SOURCE = Template.of("{name}.toWire(value.{component}())");

	static final Template BOUND_READ = Template.of("{name}.fromWire({read})");

	// ---- a composite: a pair per composite type, over its own flyweights

	static final Template ENCODE_COMPOSITE_FIELD = Template
			.of("write{composite}({source}, encoder.{property}());");

	static final Template DECODE_COMPOSITE_FIELD = Template.of("read{composite}(decoder.{property}())");

	/**
	 * The pair's parameters bear the message's names, so every field shape serves a
	 * member as it is.
	 */
	static final Template WRITE_COMPOSITE = Template.of("""
			private static void write{composite}({record} value, {encoder} encoder) {
				{members}
			}""");

	static final Template READ_COMPOSITE = Template.of("""
			private static {record} read{composite}({decoder} decoder) {
				return new {record}(
						{members}
				);
			}""");

	// ---- a group: three methods per group, keyed by its path, over its own
	// classes

	static final Template ENCODE_GROUP_FIELD = Template
			.of("write{path}({source}, encoder.{property}Count({source}.size()));");

	static final Template GROUP_LENGTH_TERM = Template.of(" + {length}(value.{component}())");

	static final Template DECODE_GROUP = Template
			.of("java.util.List<{record}> {local} = read{path}(decoder.{property}());");

	/**
	 * Absent below the acting version, as a field is; count zero is never read.
	 * sbe-tool names the group's static methods after its decoder class,
	 * {@code legsDecoderSinceVersion()}.
	 */
	static final Template DECODE_ADDED_GROUP = Template.of(
			"java.util.List<{record}> {local} = decoder.actingVersion() < {decoder}.{since}() ? null : read{path}(decoder.{property}());"
	);

	/**
	 * The entry's shapes are the message's, over the group's classes: the loop's
	 * variable and parameter bear the names the field templates use, and the
	 * methods are the codec's own, since a bound field reaches its binding.
	 */
	static final Template WRITE_GROUP = Template.of("""
			private void write{path}(java.util.List<{record}> entries, {encoder} encoder) {
				for ({record} value : entries) {
					encoder.next();
					{body}
				}
			}""");

	static final Template READ_GROUP = Template.of("""
			private java.util.List<{record}> read{path}({decoder} decoder) {
				java.util.List<{record}> entries = new java.util.ArrayList<>(decoder.count());
				while (decoder.hasNext()) {
					decoder.next();
					{groups}
					entries.add(new {record}(
							{arguments}
					));
				}
				return entries;
			}""");

	/** The dimensions and the entries, without encoding; null has no wire form. */
	static final Template GROUP_LENGTH = Template.of("""
			private static int {length}(java.util.List<{record}> entries) {
				if (entries == null) {
					throw new IllegalArgumentException("{component} is required");
				}
				return {encoder}.sbeHeaderSize() + entries.size() * {encoder}.sbeBlockLength();
			}""");

	static final Template NESTED_GROUP_LENGTH = Template.of("""
			private static int {length}(java.util.List<{record}> entries) {
				if (entries == null) {
					throw new IllegalArgumentException("{component} is required");
				}
				int length = {encoder}.sbeHeaderSize() + entries.size() * {encoder}.sbeBlockLength();
				for ({record} value : entries) {
					{terms}
				}
				return length;
			}""");

	static final Template NESTED_GROUP_LENGTH_TERM = Template.of("length += {length}(value.{component}());");

	// ---- the shapes over them

	/** A component that may be null on a required field: null has no wire form. */
	static final Template ENCODE_CHECKED_FIELD = Template.of("""
			if (value.{component}() == null) {
				throw new IllegalArgumentException("{component} is required");
			}
			{call}""");

	static final Template DECODE_OPTIONAL_FIELD = Template.of("{isNull} ? null : {read}");

	/**
	 * Absent below the acting version, decided on the version and never on the null
	 * value, which a required field may legitimately hold.
	 */
	static final Template DECODE_ADDED_FIELD = Template.of(
			"decoder.actingVersion() < {decoder}.{property}SinceVersion() ? null : {read}"
	);

	// ---- an enum's mapping, one pair per codec

	static final Template ENCODE_ENUM = Template.of("""
			private static {flyweights}.{enum} encode{enum}({javaEnum} value) {
				return switch (value) {
					{cases}
				};
			}""");

	static final Template ENUM_TO_WIRE = Template.of("case {constant} -> {flyweights}.{enum}.{wireConstant};");

	static final Template UNKNOWN_TO_WIRE = Template.of(
			"case {constant} -> throw new IllegalArgumentException(\"{enum}.{constant} has no wire form\");"
	);

	static final Template DECODE_ENUM = Template.of("""
			private static {javaEnum} decode{enum}({face} raw) {
				return switch (raw) {
					{cases}
				};
			}""");

	static final Template WIRE_TO_ENUM = Template.of("case {literal} -> {javaEnum}.{constant};");

	static final Template WIRE_TO_UNKNOWN = Template.of("default -> {javaEnum}.{constant};");

	static final Template WIRE_TO_NOTHING = Template.of(
			"default -> throw new IllegalArgumentException(\"{enum} has no value \" + raw);"
	);

	// ---- a set's mapping, one pair per codec

	static final Template ENCODE_SET = Template.of("""
			private static void encode{set}(java.util.Set<{javaEnum}> value, {flyweights}.{set}Encoder wire) {
				wire.clear();
				{choices}
			}""");

	static final Template ENCODE_CHOICE = Template.of("wire.{choice}(value.contains({javaEnum}.{constant}));");

	/** A bit no choice names has nowhere to go in a Set of the enum. */
	static final Template DECODE_SET = Template.of("""
			private static java.util.Set<{javaEnum}> decode{set}({flyweights}.{set}Decoder wire) {
				if ((wire.getRaw() & ~({knownBits})) != 0) {
					throw new IllegalArgumentException("{set} has a bit no choice names: " + wire.getRaw());
				}
				java.util.Set<{javaEnum}> value = java.util.EnumSet.noneOf({javaEnum}.class);
				{choices}
				return value;
			}""");

	static final Template KNOWN_BIT = Template.of("1L << {bit}");

	static final Template DECODE_CHOICE = Template.of("""
			if (wire.{choice}()) {
				value.add({javaEnum}.{constant});
			}""");
}
