package net.concini.sbebuddy.generator;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.io.Writer;
import java.nio.ByteOrder;
import java.util.ArrayList;
import java.util.IdentityHashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.agrona.generation.DynamicPackageOutputManager;
import org.jspecify.annotations.Nullable;

import uk.co.real_logic.sbe.PrimitiveType;
import uk.co.real_logic.sbe.generation.Generators;
import uk.co.real_logic.sbe.generation.java.JavaUtil;
import uk.co.real_logic.sbe.ir.Encoding;
import uk.co.real_logic.sbe.ir.GenerationUtil;
import uk.co.real_logic.sbe.ir.Ir;
import uk.co.real_logic.sbe.ir.Signal;
import uk.co.real_logic.sbe.ir.Token;

/**
 * Step 7 of the pipeline: one {@code <Msg>Codec} per message, from the IR the
 * way {@code JavaGenerator} reads it and from {@link Annotated} for the Java
 * face, written from text-block templates. Every flyweight member it calls is
 * named through {@link JavaUtil}, so it calls what was generated. A construct
 * the codec does not cover yet is a problem naming the message; nothing is
 * skipped silently.
 */
public final class CodecEmitter {

	private static final String STANDARD_HEADER = "messageHeader";

	private static final Template CODEC = Template.of(
			"""
					package {package};

					/** Generated by sbe-buddy from the schema of this package; do not edit. */
					@javax.annotation.processing.Generated("net.concini.sbebuddy")
					public final class {codec} implements net.concini.sbebuddy.Codec<{record}> {

						private final {flyweights}.{header}Encoder headerEncoder = new {flyweights}.{header}Encoder();
						private final {flyweights}.{header}Decoder headerDecoder = new {flyweights}.{header}Decoder();
						private final {flyweights}.{message}Encoder encoder = new {flyweights}.{message}Encoder();
						private final {flyweights}.{message}Decoder decoder = new {flyweights}.{message}Decoder();
						{bindings}
						private int lastDecodedLength;

						public {codec}() {
						}

						@Override
						public int encodedLength({record} value) {
							return {flyweights}.{header}Encoder.ENCODED_LENGTH + {flyweights}.{message}Encoder.BLOCK_LENGTH;
						}

						@Override
						public int encode({record} value, org.agrona.MutableDirectBuffer buffer, int offset) {
							encoder.wrapAndApplyHeader(buffer, offset, headerEncoder);
							{encodeFields}
							return {flyweights}.{header}Encoder.ENCODED_LENGTH + encoder.encodedLength();
						}

						@Override
						public {record} decode(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							if (headerDecoder.schemaId() != {flyweights}.{message}Decoder.SCHEMA_ID
									|| headerDecoder.templateId() != {flyweights}.{message}Decoder.TEMPLATE_ID) {
								throw new IllegalArgumentException(
										"not a {message}: schemaId " + headerDecoder.schemaId() + ", templateId " + headerDecoder.templateId());
							}
							{refuseBelowBaseline}
							decoder.wrap(buffer, offset + {flyweights}.{header}Decoder.ENCODED_LENGTH, headerDecoder.blockLength(), headerDecoder.version());
							{record} value = new {record}(
									{decodeFields}
							);
							lastDecodedLength = {flyweights}.{header}Decoder.ENCODED_LENGTH + decoder.encodedLength();
							return value;
						}

						@Override
						public int lastDecodedLength() {
							return lastDecodedLength;
						}

						@Override
						public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							return {flyweights}.{header}Decoder.ENCODED_LENGTH + headerDecoder.blockLength();
						}
						{helpers}
					}
					"""
	);

	/**
	 * A message older than the baseline would read the null value of every field
	 * appended up to it into a primitive component; the baseline is the schema's
	 * own declaration, which no flyweight constant carries.
	 */
	private static final Template REFUSE_BELOW_BASELINE = Template.of("""
			if (headerDecoder.version() < {baseline}) {
				throw new IllegalArgumentException(
						"{message} version " + headerDecoder.version() + " is below the baseline {baseline}");
			}""");

	// ---- a primitive field

	private static final Template ENCODE_FIELD = Template.of("encoder.{property}({source});");

	private static final Template ENCODE_OPTIONAL_FIELD = Template.of(
			"encoder.{property}(value.{component}() == null ? {flyweights}.{message}Encoder.{property}NullValue() : {source});"
	);

	private static final Template DECODE_FIELD = Template.of("decoder.{property}()");

	private static final Template IS_NULL = Template.of(
			"decoder.{property}() == {flyweights}.{message}Decoder.{property}NullValue()"
	);

	/** The null value of the floats is NaN, which == never matches. */
	private static final Template IS_NULL_FLOATING = Template.of(
			"{box}.compare(decoder.{property}(), {flyweights}.{message}Decoder.{property}NullValue()) == 0"
	);

	// ---- a field of an enum

	private static final Template ENCODE_ENUM_FIELD = Template
			.of("encoder.{property}(encode{enum}(value.{component}()));");

	private static final Template ENCODE_OPTIONAL_ENUM_FIELD = Template.of(
			"encoder.{property}(value.{component}() == null ? {flyweights}.{enum}.NULL_VAL : encode{enum}(value.{component}()));"
	);

	private static final Template DECODE_ENUM_FIELD = Template.of("decode{enum}(decoder.{property}Raw())");

	private static final Template IS_NULL_ENUM = Template.of(
			"decoder.{property}Raw() == {flyweights}.{enum}.NULL_VAL.value()"
	);

	// ---- a field of a set

	private static final Template ENCODE_SET_FIELD = Template
			.of("encode{set}(value.{component}(), encoder.{property}());");

	private static final Template DECODE_SET_FIELD = Template.of("decode{set}(decoder.{property}())");

	// ---- a field no component carries: the null value out, nothing back

	private static final Template ENCODE_UNMAPPED_FIELD = Template.of(
			"encoder.{property}({flyweights}.{message}Encoder.{property}NullValue());"
	);

	private static final Template ENCODE_UNMAPPED_ENUM_FIELD = Template
			.of("encoder.{property}({flyweights}.{enum}.NULL_VAL);");

	private static final Template ENCODE_UNMAPPED_SET_FIELD = Template.of("encoder.{property}().clear();");

	// ---- a char string: the flyweight's own String form, checked first

	private static final Template ENCODE_STRING_FIELD = Template.of(
			"encoder.{property}(ascii({source}, {flyweights}.{message}Encoder.{property}Length(), \"{component}\"));"
	);

	/**
	 * The flyweight writes a char above 127 as '?' and throws its own exception
	 * over the length; the codec refuses both first.
	 */
	private static final Template ASCII = Template.of("""
			private static String ascii(String value, int length, String field) {
				if (value.length() > length) {
					throw new IllegalArgumentException(field + " is longer than " + length + ": " + value);
				}
				for (int i = 0; i < value.length(); i++) {
					if (value.charAt(i) > 127) {
						throw new IllegalArgumentException(field + " is not ASCII: " + value);
					}
				}
				return value;
			}""");

	// ---- a fixed-length array: a pair per field, over the index accessors

	private static final Template ENCODE_ARRAY_FIELD = Template.of("write{field}({source}, encoder);");

	private static final Template DECODE_ARRAY_FIELD = Template.of("read{field}(decoder)");

	private static final Template WRITE_ARRAY = Template.of(
			"""
					private static void write{field}({face}[] value, {flyweights}.{message}Encoder encoder) {
						if (value.length != {flyweights}.{message}Encoder.{property}Length()) {
							throw new IllegalArgumentException(
									"{component} must be " + {flyweights}.{message}Encoder.{property}Length() + " long, not " + value.length);
						}
						for (int i = 0; i < value.length; i++) {
							encoder.{property}(i, value[i]);
						}
					}"""
	);

	private static final Template READ_ARRAY = Template.of("""
			private static {face}[] read{field}({flyweights}.{message}Decoder decoder) {
				{face}[] value = new {face}[{flyweights}.{message}Decoder.{property}Length()];
				for (int i = 0; i < value.length; i++) {
					value[i] = decoder.{property}(i);
				}
				return value;
			}""");

	/**
	 * A uint8 array has bulk accessors over byte[], where its index accessors widen
	 * to short.
	 */
	private static final Template WRITE_BYTES = Template.of(
			"""
					private static void write{field}(byte[] value, {flyweights}.{message}Encoder encoder) {
						if (value.length != {flyweights}.{message}Encoder.{property}Length()) {
							throw new IllegalArgumentException(
									"{component} must be " + {flyweights}.{message}Encoder.{property}Length() + " long, not " + value.length);
						}
						encoder.put{field}(value, 0, value.length);
					}"""
	);

	private static final Template READ_BYTES = Template.of("""
			private static byte[] read{field}({flyweights}.{message}Decoder decoder) {
				byte[] value = new byte[{flyweights}.{message}Decoder.{property}Length()];
				decoder.get{field}(value, 0, value.length);
				return value;
			}""");

	// ---- a constant: no bytes; the record must agree with the schema

	private static final Template CHECK_CONSTANT_FIELD = Template.of("""
			if ({source} != encoder.{property}()) {
				throw new IllegalArgumentException("{component} is the constant " + encoder.{property}());
			}""");

	private static final Template CHECK_CONSTANT_STRING_FIELD = Template.of("""
			if (!encoder.{property}().equals({source})) {
				throw new IllegalArgumentException("{component} is the constant " + encoder.{property}());
			}""");

	private static final Template CHECK_CONSTANT_ENUM_FIELD = Template.of("""
			if (value.{component}() != {javaEnum}.{constant}) {
				throw new IllegalArgumentException("{component} is the constant {constant}");
			}""");

	// ---- a binding: the component mapped before the flyweight and after it

	private static final Template BINDING_FIELD = Template.of("private final {binding} {name} = new {binding}();");

	/** What the flyweight is handed: the component, or the binding's view of it. */
	private static final Template SOURCE = Template.of("value.{component}()");

	private static final Template BOUND_SOURCE = Template.of("{name}.toWire(value.{component}())");

	private static final Template BOUND_READ = Template.of("{name}.fromWire({read})");

	// ---- a composite: a pair per composite type, over its own flyweights

	private static final Template ENCODE_COMPOSITE_FIELD = Template
			.of("write{composite}({source}, encoder.{property}());");

	private static final Template DECODE_COMPOSITE_FIELD = Template.of("read{composite}(decoder.{property}())");

	/**
	 * The pair's parameters bear the message's names, so every field shape serves a
	 * member as it is.
	 */
	private static final Template WRITE_COMPOSITE = Template.of("""
			private static void write{composite}({record} value, {flyweights}.{composite}Encoder encoder) {
				{members}
			}""");

	private static final Template READ_COMPOSITE = Template.of("""
			private static {record} read{composite}({flyweights}.{composite}Decoder decoder) {
				return new {record}(
						{members}
				);
			}""");

	// ---- the shapes over them

	/** A component that may be null on a required field: null has no wire form. */
	private static final Template ENCODE_CHECKED_FIELD = Template.of("""
			if (value.{component}() == null) {
				throw new IllegalArgumentException("{component} is required");
			}
			{call}""");

	private static final Template DECODE_OPTIONAL_FIELD = Template.of("{isNull} ? null : {read}");

	/**
	 * Absent below the acting version, decided on the version and never on the null
	 * value, which a required field may legitimately hold.
	 */
	private static final Template DECODE_ADDED_FIELD = Template.of(
			"decoder.actingVersion() < {flyweights}.{message}Decoder.{property}SinceVersion() ? null : {read}"
	);

	// ---- an enum's mapping, one pair per codec

	private static final Template ENCODE_ENUM = Template.of("""
			private static {flyweights}.{enum} encode{enum}({javaEnum} value) {
				return switch (value) {
					{cases}
				};
			}""");

	private static final Template ENUM_TO_WIRE = Template.of("case {constant} -> {flyweights}.{enum}.{wireConstant};");

	private static final Template UNKNOWN_TO_WIRE = Template.of(
			"case {constant} -> throw new IllegalArgumentException(\"{enum}.{constant} has no wire form\");"
	);

	private static final Template DECODE_ENUM = Template.of("""
			private static {javaEnum} decode{enum}({face} raw) {
				return switch (raw) {
					{cases}
				};
			}""");

	private static final Template WIRE_TO_ENUM = Template.of("case {literal} -> {javaEnum}.{constant};");

	private static final Template WIRE_TO_UNKNOWN = Template.of("default -> {javaEnum}.{constant};");

	private static final Template WIRE_TO_NOTHING = Template.of(
			"default -> throw new IllegalArgumentException(\"{enum} has no value \" + raw);"
	);

	// ---- a set's mapping, one pair per codec

	private static final Template ENCODE_SET = Template.of("""
			private static void encode{set}(java.util.Set<{javaEnum}> value, {flyweights}.{set}Encoder wire) {
				wire.clear();
				{choices}
			}""");

	private static final Template ENCODE_CHOICE = Template.of("wire.{choice}(value.contains({javaEnum}.{constant}));");

	/** A bit no choice names has nowhere to go in a Set of the enum. */
	private static final Template DECODE_SET = Template.of("""
			private static java.util.Set<{javaEnum}> decode{set}({flyweights}.{set}Decoder wire) {
				if ((wire.getRaw() & ~({knownBits})) != 0) {
					throw new IllegalArgumentException("{set} has a bit no choice names: " + wire.getRaw());
				}
				java.util.Set<{javaEnum}> value = java.util.EnumSet.noneOf({javaEnum}.class);
				{choices}
				return value;
			}""");

	private static final Template KNOWN_BIT = Template.of("1L << {bit}");

	private static final Template DECODE_CHOICE = Template.of("""
			if (wire.{choice}()) {
				value.add({javaEnum}.{constant});
			}""");

	private final Ir ir;
	private final Annotated annotated;
	private final List<Problem> problems = new ArrayList<>();

	private CodecEmitter(Ir ir, Annotated annotated) {
		this.ir = ir;
		this.annotated = annotated;
	}

	/**
	 * Writes each message's codec through the output under the schema package, or
	 * writes nothing and returns the problems: a construct the codec lacks in any
	 * message is collected, never a partial write. An output that fails to write is
	 * an {@link UncheckedIOException}.
	 */
	public static List<Problem> emit(Ir ir, Annotated annotated, DynamicPackageOutputManager output) {
		CodecEmitter emitter = new CodecEmitter(ir, annotated);
		Map<String, String> sources = new LinkedHashMap<>();
		for (Annotated.Message message : annotated.messages()) {
			String source = emitter.codec(message);
			if (source != null) {
				sources.put(message.javaName() + "Codec", source);
			}
		}
		if (!emitter.problems.isEmpty()) {
			return List.copyOf(emitter.problems);
		}
		for (Map.Entry<String, String> source : sources.entrySet()) {
			// Before every file: Agrona's manager falls back to the first package it
			// was given when a writer closes.
			output.setPackageName(annotated.packageName());
			try (Writer writer = output.createOutput(source.getKey())) {
				writer.write(source.getValue());
			} catch (IOException e) {
				throw new UncheckedIOException(e);
			}
		}
		return List.of();
	}

	/**
	 * How one field reaches the wire: the plain call each way, and the optional
	 * forms where the wire has a null value for it.
	 */
	private record Access(String encode, @Nullable String encodeOptional, String decode, @Nullable String isNull) {
	}

	/**
	 * Whose flyweight a token's accessors are on: the message's, whose decoder
	 * guards by version, or a composite's, which never does; {@code prefix} keeps a
	 * member's array pair apart from a field's of the same name.
	 */
	private record Owner(String flyweightClass, String prefix, boolean guarded) {
	}

	/**
	 * The codec's source, or null with a problem for a construct not covered yet.
	 */
	private @Nullable String codec(Annotated.Message message) {
		String header = ir.headerStructure().tokens().get(0).name();
		if (!header.equals(STANDARD_HEADER)) {
			return refuse(message, "a header type of its own");
		}
		if (ir.byteOrder() != ByteOrder.LITTLE_ENDIAN) {
			return refuse(message, "big-endian byte order");
		}
		List<Token> tokens = ir.getMessage(message.id());
		List<Token> fields = new ArrayList<>();
		List<Token> groups = new ArrayList<>();
		List<Token> varData = new ArrayList<>();
		int index = GenerationUtil.collectFields(tokens, 1, fields);
		index = GenerationUtil.collectGroups(tokens, index, groups);
		GenerationUtil.collectVarData(tokens, index, varData);
		if (!groups.isEmpty()) {
			return refuse(message, "a group");
		}
		if (!varData.isEmpty()) {
			return refuse(message, "var-data");
		}
		String flyweights = ir.applicableNamespace();
		String messageClass = JavaUtil.formatClassName(tokens.get(0).name());
		List<String> encodeFields = new ArrayList<>();
		Map<Annotated.Component, String> reads = new IdentityHashMap<>();
		Map<String, String> helpers = new LinkedHashMap<>();
		Map<String, String> bindings = new LinkedHashMap<>();
		Owner owner = new Owner(messageClass, "", true);
		for (int i = 0; i < fields.size(); i += fields.get(i).componentTokenCount()) {
			Token field = fields.get(i);
			Token type = fields.get(i + 1);
			String unsupported = unsupported(type);
			if (unsupported != null) {
				return refuse(message, unsupported);
			}
			String property = JavaUtil.formatPropertyName(field.name());
			List<Token> typeTokens = fields.subList(i + 1, i + 1 + type.componentTokenCount());
			Annotated.Field component = component(message, field);
			if (component == null) {
				if (type.signal() == Signal.BEGIN_COMPOSITE) {
					return refuse(message, "an unmapped field of a composite");
				}
				if (!constant(field)) {
					encodeFields.add(
							encodeUnmapped(unmapped(message, field).name(), type, flyweights, messageClass, property)
					);
				}
				continue;
			}
			Annotated.Binding binding = component.binding();
			String bindingName = binding == null ? null : bindingName(binding, bindings);
			if (binding != null && bindingName == null) {
				problems.add(
						new Problem(
								message, "two bindings share the simple name " + simpleName(binding.qualifiedName())
										+ " in one codec; the second is " + binding.qualifiedName()
						)
				);
				return null;
			}
			String source = bindingName == null
					? SOURCE.fill("component", component.javaName())
					: BOUND_SOURCE.fill("name", bindingName, "component", component.javaName());
			Access access = access(
					field, typeTokens, component.javaName(), component.javaType(), declarationOf(component), source,
					owner, flyweights, helpers
			);
			if (bindingName != null) {
				// The null value and the version are decided before the binding is called.
				access = new Access(
						access.encode(), access.encodeOptional(),
						BOUND_READ.fill("name", bindingName, "read", access.decode()), access.isNull()
				);
			}
			encodeFields.add(encodeField(field, component.javaName(), component.javaType(), access));
			reads.put(component, decodeField(field, flyweights, owner, property, access));
		}
		// The canonical constructor takes the components as declared, which the
		// layout may order differently from the wire; the block is addressed by
		// offset, so either order reads it.
		List<String> decodeFields = new ArrayList<>();
		for (Annotated.Component component : message.components()) {
			String read = reads.get(component);
			if (read == null) {
				throw new IllegalStateException(message.javaName() + " has no field for a component");
			}
			decodeFields.add(read);
		}
		int baseline = annotated.baselineVersion();
		return CODEC.fill(
				"package", annotated.packageName(),
				"codec", message.javaName() + "Codec",
				"record", annotated.packageName() + "." + message.javaName(),
				"flyweights", flyweights,
				"header", JavaUtil.formatClassName(header),
				"message", messageClass,
				"bindings", bindingFields(bindings),
				"encodeFields", String.join("\n", encodeFields),
				"refuseBelowBaseline", baseline == 0
						? ""
						: REFUSE_BELOW_BASELINE.fill("message", messageClass, "baseline", String.valueOf(baseline)),
				"decodeFields", String.join(",\n", decodeFields),
				"helpers", helpers.isEmpty() ? "" : "\n" + String.join("\n\n", helpers.values())
		);
	}

	/** A field no component carries is written as its null value and never read. */
	private static String encodeUnmapped(String name, Token type, String flyweights, String owner, String property) {
		return switch (type.signal()) {
			case ENCODING ->
				ENCODE_UNMAPPED_FIELD.fill("property", property, "flyweights", flyweights, "message", owner);
			case BEGIN_ENUM -> ENCODE_UNMAPPED_ENUM_FIELD.fill(
					"property", property, "flyweights", flyweights,
					"enum", JavaUtil.formatClassName(type.applicableTypeName())
			);
			case BEGIN_SET -> ENCODE_UNMAPPED_SET_FIELD.fill("property", property);
			default -> throw new IllegalStateException(name + " is a field of " + type.signal());
		};
	}

	/**
	 * The encode side is decided from the component: an optional field takes the
	 * null value for null, any other component that may be null refuses it.
	 */
	private static String encodeField(Token field, String javaName, Annotated.JavaType javaType, Access access) {
		if (optional(field)) {
			if (access.encodeOptional() == null) {
				throw new IllegalStateException(javaName + " is optional without a null value");
			}
			return access.encodeOptional();
		}
		if (javaType instanceof Annotated.Primitive primitive && !primitive.boxed()) {
			return access.encode();
		}
		return ENCODE_CHECKED_FIELD.fill("component", javaName, "call", access.encode());
	}

	/**
	 * The decode side is decided from the wire: the null value for an optional
	 * field, whatever its version, since below the acting version the getter
	 * returns it; the version for a required field added above the baseline, which
	 * only a message's flyweight guards.
	 */
	private String decodeField(Token field, String flyweights, Owner owner, String property, Access access) {
		if (constant(field)) {
			return access.decode();
		}
		if (optional(field)) {
			if (access.isNull() == null) {
				throw new IllegalStateException(field.name() + " is optional without a null value");
			}
			return DECODE_OPTIONAL_FIELD.fill("isNull", access.isNull(), "read", access.decode());
		}
		if (owner.guarded() && field.version() > annotated.baselineVersion()) {
			return DECODE_ADDED_FIELD.fill(
					"flyweights", flyweights, "message", owner.flyweightClass(), "property", property, "read",
					access.decode()
			);
		}
		return access.decode();
	}

	/**
	 * How one token reaches the wire, by its type: a constant checked and read, a
	 * primitive, an enum, a set or a composite through its own shape.
	 */
	private Access access(
			Token field, List<Token> typeTokens, String javaName, Annotated.JavaType javaType,
			Annotated.@Nullable Declaration declaration, String source, Owner owner, String flyweights,
			Map<String, String> helpers
	) {
		Token type = typeTokens.get(0);
		String property = JavaUtil.formatPropertyName(field.name());
		if (constant(field)) {
			return constantAccess(
					field, typeTokens, javaName, declaration, flyweights, owner, property, source, helpers
			);
		}
		return switch (type.signal()) {
			case ENCODING -> encodingAccess(type, flyweights, owner, property, javaName, source, helpers);
			case BEGIN_ENUM -> enumAccess(
					typeTokens, declared(declaration, Annotated.Enum.class, javaName), flyweights,
					owner.flyweightClass(), property, javaName, helpers
			);
			case BEGIN_SET -> setAccess(
					typeTokens, declared(declaration, Annotated.Set.class, javaName), flyweights, property, javaName,
					helpers
			);
			case BEGIN_COMPOSITE -> compositeAccess(
					typeTokens, declared(declaration, Annotated.Composite.class, javaName), flyweights, property,
					source, helpers
			);
			default -> throw new IllegalStateException("a field of " + type.signal());
		};
	}

	/** The declaration the face rule saw to, in the shape the token says. */
	private static <D extends Annotated.Declaration> D declared(
			Annotated.@Nullable Declaration declaration, Class<D> shape, String javaName
	) {
		if (shape.isInstance(declaration)) {
			return shape.cast(declaration);
		}
		throw new IllegalStateException(javaName + " is not a field of " + shape.getSimpleName());
	}

	/**
	 * A composite field or member goes through the pair of its type, declared on
	 * first use after the pairs it nests, which register while it is built.
	 */
	private Access compositeAccess(
			List<Token> typeTokens, Annotated.Composite composite, String flyweights, String property, String source,
			Map<String, String> helpers
	) {
		String compositeClass = JavaUtil.formatClassName(typeTokens.get(0).applicableTypeName());
		String key = "type " + typeTokens.get(0).applicableTypeName();
		if (!helpers.containsKey(key)) {
			helpers.put(key, compositePair(typeTokens, composite, flyweights, compositeClass, helpers));
		}
		return new Access(
				ENCODE_COMPOSITE_FIELD.fill("composite", compositeClass, "source", source, "property", property),
				null,
				DECODE_COMPOSITE_FIELD.fill("composite", compositeClass, "property", property),
				null
		);
	}

	/**
	 * The composite's members with the shapes a field has, over the composite's
	 * flyweight; the record's constructor takes its components as declared, where
	 * the layout may order the wire otherwise.
	 */
	private String compositePair(
			List<Token> typeTokens, Annotated.Composite composite, String flyweights, String compositeClass,
			Map<String, String> helpers
	) {
		Owner owner = new Owner(compositeClass, compositeClass, false);
		List<String> encodes = new ArrayList<>();
		Map<Annotated.Member, String> reads = new IdentityHashMap<>();
		for (int i = 1; i < typeTokens.size() - 1; i += typeTokens.get(i).componentTokenCount()) {
			Token member = typeTokens.get(i);
			List<Token> memberTokens = typeTokens.subList(i, i + member.componentTokenCount());
			String property = JavaUtil.formatPropertyName(member.name());
			Annotated.Member annotated = member(composite, member.name());
			if (annotated == null) {
				if (!constant(member)) {
					String name = unmappedMember(composite, member.name()).name();
					encodes.add(encodeUnmapped(name, member, flyweights, compositeClass, property));
				}
				continue;
			}
			String javaName = javaName(annotated);
			Annotated.JavaType javaType = javaTypeOf(annotated);
			Access access = access(
					member, memberTokens, javaName, javaType, declarationOf(annotated),
					SOURCE.fill("component", javaName), owner, flyweights, helpers
			);
			encodes.add(encodeField(member, javaName, javaType, access));
			reads.put(annotated, decodeField(member, flyweights, owner, property, access));
		}
		List<String> arguments = new ArrayList<>();
		for (Annotated.Member member : composite.members()) {
			String read = reads.get(member);
			if (read == null) {
				throw new IllegalStateException(composite.javaName() + " has no member for a component");
			}
			arguments.add(read);
		}
		return String.join(
				"\n\n",
				WRITE_COMPOSITE.fill(
						"composite", compositeClass, "record", composite.qualifiedName(), "flyweights", flyweights,
						"members", String.join("\n", encodes)
				),
				READ_COMPOSITE.fill(
						"record", composite.qualifiedName(), "composite", compositeClass, "flyweights", flyweights,
						"members", String.join(",\n", arguments)
				)
		);
	}

	/**
	 * A char string goes through the flyweight's own String form, checked by
	 * {@code ascii} first; any other array through a pair per field; a scalar
	 * through its accessor.
	 */
	private static Access encodingAccess(
			Token type, String flyweights, Owner owner, String property, String javaName, String source,
			Map<String, String> helpers
	) {
		if (type.arrayLength() <= 1) {
			return primitiveAccess(type, flyweights, owner.flyweightClass(), property, javaName, source);
		}
		if (type.encoding().primitiveType() == PrimitiveType.CHAR) {
			helpers.computeIfAbsent("ascii", name -> ASCII.fill());
			return new Access(
					ENCODE_STRING_FIELD.fill(
							"property", property, "source", source, "component", javaName, "flyweights", flyweights,
							"message", owner.flyweightClass()
					),
					null,
					DECODE_FIELD.fill("property", property),
					null
			);
		}
		String field = owner.prefix() + Generators.toUpperFirstChar(property);
		helpers.computeIfAbsent(
				"field " + field, name -> arrayPair(type, flyweights, owner.flyweightClass(), property, field, javaName)
		);
		return new Access(
				ENCODE_ARRAY_FIELD.fill("field", field, "source", source),
				null,
				DECODE_ARRAY_FIELD.fill("field", field),
				null
		);
	}

	private static String arrayPair(
			Token type, String flyweights, String messageClass, String property, String field, String component
	) {
		PrimitiveType primitive = type.encoding().primitiveType();
		if (primitive == PrimitiveType.UINT8) {
			return String.join(
					"\n\n",
					WRITE_BYTES.fill(
							"field", field, "flyweights", flyweights, "message", messageClass, "property", property,
							"component", component
					),
					READ_BYTES.fill(
							"field", field, "flyweights", flyweights, "message", messageClass, "property", property
					)
			);
		}
		String face = JavaUtil.javaTypeName(primitive);
		return String.join(
				"\n\n",
				WRITE_ARRAY.fill(
						"field", field, "face", face, "flyweights", flyweights, "message", messageClass, "property",
						property, "component", component
				),
				READ_ARRAY.fill(
						"field", field, "face", face, "flyweights", flyweights, "message", messageClass, "property",
						property
				)
		);
	}

	/**
	 * A constant carries no bytes: encode checks the component against the
	 * flyweight's own constant, or for an enum against the record's constant the
	 * valueRef names, and decode reads the constant as any field.
	 */
	private Access constantAccess(
			Token field, List<Token> typeTokens, String javaName, Annotated.@Nullable Declaration declaration,
			String flyweights, Owner owner, String property, String source, Map<String, String> helpers
	) {
		Token type = typeTokens.get(0);
		return switch (type.signal()) {
			case ENCODING -> {
				Encoding encoding = type.encoding();
				boolean string = encoding.primitiveType() == PrimitiveType.CHAR
						&& encoding.constValue().byteArrayValue(PrimitiveType.CHAR).length > 1;
				Template check = string ? CHECK_CONSTANT_STRING_FIELD : CHECK_CONSTANT_FIELD;
				yield new Access(
						check.fill("source", source, "component", javaName, "property", property),
						null,
						DECODE_FIELD.fill("property", property),
						null
				);
			}
			case BEGIN_ENUM -> {
				Annotated.Enum enumeration = declared(declaration, Annotated.Enum.class, javaName);
				Access plain = enumAccess(
						typeTokens, enumeration, flyweights, owner.flyweightClass(), property, javaName, helpers
				);
				String reference = field.encoding().constValue().toString();
				String constant = validValue(enumeration, reference.substring(reference.indexOf('.') + 1)).javaName();
				yield new Access(
						CHECK_CONSTANT_ENUM_FIELD.fill(
								"component", javaName, "javaEnum", enumeration.qualifiedName(), "constant", constant
						),
						null,
						plain.decode(),
						null
				);
			}
			default -> throw new IllegalStateException("a constant field of " + type.signal());
		};
	}

	private static Access primitiveAccess(
			Token type, String flyweights, String messageClass, String property, String component, String source
	) {
		return new Access(
				ENCODE_FIELD.fill("property", property, "source", source),
				ENCODE_OPTIONAL_FIELD.fill(
						"property", property, "component", component, "source", source, "flyweights", flyweights,
						"message", messageClass
				),
				DECODE_FIELD.fill("property", property),
				isNull(type, flyweights, messageClass, property)
		);
	}

	private static String isNull(Token type, String flyweights, String messageClass, String property) {
		PrimitiveType primitive = type.encoding().primitiveType();
		if (primitive == PrimitiveType.FLOAT || primitive == PrimitiveType.DOUBLE) {
			// The box is the one name that neither the IR nor JavaUtil holds.
			String box = primitive == PrimitiveType.FLOAT ? "Float" : "Double";
			return IS_NULL_FLOATING
					.fill("box", box, "property", property, "flyweights", flyweights, "message", messageClass);
		}
		return IS_NULL.fill("property", property, "flyweights", flyweights, "message", messageClass);
	}

	private static Access enumAccess(
			List<Token> tokens, Annotated.Enum enumeration, String flyweights, String messageClass, String property,
			String component, Map<String, String> declaredTypes
	) {
		String enumClass = JavaUtil.formatClassName(tokens.get(0).applicableTypeName());
		declaredTypes.computeIfAbsent(
				tokens.get(0).applicableTypeName(), name -> enumPair(tokens, enumeration, flyweights, enumClass)
		);
		return new Access(
				ENCODE_ENUM_FIELD.fill("property", property, "enum", enumClass, "component", component),
				ENCODE_OPTIONAL_ENUM_FIELD
						.fill(
								"property", property, "component", component, "flyweights", flyweights, "enum",
								enumClass
						),
				DECODE_ENUM_FIELD.fill("enum", enumClass, "property", property),
				IS_NULL_ENUM.fill("property", property, "flyweights", flyweights, "enum", enumClass)
		);
	}

	/**
	 * The wire value is read raw and mapped by the valid values' text, never
	 * through the flyweight's enum, so an unknown value is ours to decide: the
	 * constant the enum designates, or an exception.
	 */
	private static String enumPair(
			List<Token> tokens, Annotated.Enum enumeration, String flyweights, String enumClass
	) {
		PrimitiveType primitive = tokens.get(0).encoding().primitiveType();
		List<String> toWire = new ArrayList<>();
		List<String> fromWire = new ArrayList<>();
		for (Token value : tokens) {
			if (value.signal() != Signal.VALID_VALUE) {
				continue;
			}
			String constant = validValue(enumeration, value.name()).javaName();
			toWire.add(
					ENUM_TO_WIRE.fill(
							"constant", constant, "flyweights", flyweights, "enum", enumClass,
							"wireConstant", JavaUtil.formatForJavaKeyword(value.name())
					)
			);
			fromWire.add(
					WIRE_TO_ENUM.fill(
							"literal", JavaUtil.generateLiteral(primitive, value.encoding().constValue().toString()),
							"javaEnum", enumeration.qualifiedName(), "constant", constant
					)
			);
		}
		String unknown = enumeration.unknownValue();
		if (unknown == null) {
			fromWire.add(WIRE_TO_NOTHING.fill("enum", enumClass));
		} else {
			toWire.add(UNKNOWN_TO_WIRE.fill("constant", unknown, "enum", enumClass));
			fromWire.add(WIRE_TO_UNKNOWN.fill("javaEnum", enumeration.qualifiedName(), "constant", unknown));
		}
		return String.join(
				"\n\n",
				ENCODE_ENUM.fill(
						"flyweights", flyweights, "enum", enumClass, "javaEnum", enumeration.qualifiedName(),
						"cases", String.join("\n", toWire)
				),
				DECODE_ENUM.fill(
						"javaEnum", enumeration.qualifiedName(), "enum", enumClass,
						"face", JavaUtil.javaTypeName(primitive), "cases", String.join("\n", fromWire)
				)
		);
	}

	private static Access setAccess(
			List<Token> tokens, Annotated.Set set, String flyweights, String property, String component,
			Map<String, String> declaredTypes
	) {
		String setClass = JavaUtil.formatClassName(tokens.get(0).applicableTypeName());
		declaredTypes.computeIfAbsent(
				tokens.get(0).applicableTypeName(), name -> setPair(tokens, set, flyweights, setClass)
		);
		return new Access(
				ENCODE_SET_FIELD.fill("set", setClass, "component", component, "property", property),
				null,
				DECODE_SET_FIELD.fill("set", setClass, "property", property),
				null
		);
	}

	private static String setPair(List<Token> tokens, Annotated.Set set, String flyweights, String setClass) {
		List<String> encodeChoices = new ArrayList<>();
		List<String> decodeChoices = new ArrayList<>();
		List<String> knownBits = new ArrayList<>();
		for (Token choice : tokens) {
			if (choice.signal() != Signal.CHOICE) {
				continue;
			}
			String property = JavaUtil.formatPropertyName(choice.name());
			String constant = choice(set, choice.name()).javaName();
			encodeChoices
					.add(ENCODE_CHOICE.fill("choice", property, "javaEnum", set.qualifiedName(), "constant", constant));
			decodeChoices
					.add(DECODE_CHOICE.fill("choice", property, "javaEnum", set.qualifiedName(), "constant", constant));
			knownBits.add(KNOWN_BIT.fill("bit", choice.encoding().constValue().toString()));
		}
		return String.join(
				"\n\n",
				ENCODE_SET.fill(
						"set", setClass, "javaEnum", set.qualifiedName(), "flyweights", flyweights,
						"choices", String.join("\n", encodeChoices)
				),
				DECODE_SET.fill(
						"javaEnum", set.qualifiedName(), "set", setClass, "flyweights", flyweights,
						"knownBits", String.join(" | ", knownBits), "choices", String.join("\n", decodeChoices)
				)
		);
	}

	/**
	 * The codec's field for the binding, named after the class,
	 * {@code priceBinding} for {@code Price}, and declared on first use; null when
	 * another class of that simple name already has the name.
	 */
	private static @Nullable String bindingName(Annotated.Binding binding, Map<String, String> bindings) {
		String simpleName = simpleName(binding.qualifiedName());
		String name = Character.toLowerCase(simpleName.charAt(0)) + simpleName.substring(1);
		if (!name.endsWith("Binding")) {
			name += "Binding";
		}
		String declared = bindings.putIfAbsent(name, binding.qualifiedName());
		return declared == null || declared.equals(binding.qualifiedName()) ? name : null;
	}

	private static String bindingFields(Map<String, String> bindings) {
		List<String> fields = new ArrayList<>();
		for (Map.Entry<String, String> binding : bindings.entrySet()) {
			fields.add(BINDING_FIELD.fill("binding", binding.getValue(), "name", binding.getKey()));
		}
		return String.join("\n", fields);
	}

	private static String simpleName(String qualifiedName) {
		return qualifiedName.substring(qualifiedName.lastIndexOf('.') + 1);
	}

	private static boolean optional(Token field) {
		return field.encoding().presence() == Encoding.Presence.OPTIONAL;
	}

	private static boolean constant(Token field) {
		return field.encoding().presence() == Encoding.Presence.CONSTANT;
	}

	/**
	 * What the codec cannot do with the field's type yet, or null for a primitive,
	 * an array, an ASCII string, an enum, a set or a composite.
	 */
	private static @Nullable String unsupported(Token type) {
		return switch (type.signal()) {
			case BEGIN_ENUM, BEGIN_SET, BEGIN_COMPOSITE -> null;
			case ENCODING -> encodingUnsupported(type);
			default -> throw new IllegalStateException("a field of " + type.signal());
		};
	}

	/**
	 * The flyweight's String form of a char array is ASCII-checked only for ASCII.
	 */
	private static @Nullable String encodingUnsupported(Token type) {
		Encoding encoding = type.encoding();
		if (type.arrayLength() > 1 && encoding.primitiveType() == PrimitiveType.CHAR
				&& !JavaUtil.isAsciiEncoding(encoding.characterEncoding())) {
			return "a string in " + encoding.characterEncoding();
		}
		return null;
	}

	private @Nullable String refuse(Annotated.Message message, String construct) {
		problems.add(new Problem(message, "no codec for " + construct + " yet; set codecs = false on @SbeSchema"));
		return null;
	}

	/**
	 * The record component the field token came from, by wire name; null for a
	 * field no component carries.
	 */
	private static Annotated.@Nullable Field component(Annotated.Message message, Token field) {
		for (Annotated.Component component : message.components()) {
			if (component instanceof Annotated.Field candidate && wireName(candidate).equals(field.name())) {
				return candidate;
			}
		}
		return null;
	}

	/** The unmapped declaration the field token came from, by wire name. */
	private static Annotated.Field unmapped(Annotated.Message message, Token field) {
		for (Annotated.Field candidate : message.unmapped()) {
			if (wireName(candidate).equals(field.name())) {
				return candidate;
			}
		}
		throw new IllegalStateException(message.javaName() + " has no component for field " + field.name());
	}

	/**
	 * What a field is written as, named by {@code type} or as the component's own
	 * type; null for a primitive.
	 */
	private static Annotated.@Nullable Declaration declarationOf(Annotated.Field field) {
		if (field.type() != null) {
			return field.type();
		}
		return declarationOf(field.javaType());
	}

	private static Annotated.@Nullable Declaration declarationOf(Annotated.JavaType javaType) {
		if (javaType instanceof Annotated.Declared declared) {
			return declared.declaration();
		}
		if (javaType instanceof Annotated.SetOf setOf) {
			return setOf.declaration();
		}
		return null;
	}

	/** What a composite's member is written as; null for an inline type. */
	private static Annotated.@Nullable Declaration declarationOf(Annotated.Member member) {
		return switch (member) {
			case Annotated.Type type -> null;
			case Annotated.Ref ref -> ref.value() != null ? ref.value() : declarationOf(ref.javaType());
			case Annotated.Enum enumeration -> enumeration;
			case Annotated.Set set -> set;
			case Annotated.Composite composite -> composite;
		};
	}

	/** The component's type behind a member: an inline declaration is its own. */
	private static Annotated.JavaType javaTypeOf(Annotated.Member member) {
		return switch (member) {
			case Annotated.Type type -> {
				if (type.javaType() == null) {
					throw new IllegalStateException(type.javaName() + " is a member without a component");
				}
				yield type.javaType();
			}
			case Annotated.Ref ref -> ref.javaType();
			case Annotated.Enum enumeration -> new Annotated.Declared(enumeration);
			case Annotated.Set set -> new Annotated.SetOf(set);
			case Annotated.Composite composite -> new Annotated.Declared(composite);
		};
	}

	private static String javaName(Annotated.Member member) {
		return switch (member) {
			case Annotated.Type type -> type.javaName();
			case Annotated.Ref ref -> ref.javaName();
			case Annotated.Enum enumeration -> enumeration.javaName();
			case Annotated.Set set -> set.javaName();
			case Annotated.Composite composite -> composite.javaName();
		};
	}

	/**
	 * The member the token came from, by wire name; null for one no component
	 * carries.
	 */
	private static Annotated.@Nullable Member member(Annotated.Composite composite, String wireName) {
		for (Annotated.Member member : composite.members()) {
			if (wireName(member).equals(wireName)) {
				return member;
			}
		}
		return null;
	}

	private static Annotated.Type unmappedMember(Annotated.Composite composite, String wireName) {
		for (Annotated.Type member : composite.unmapped()) {
			if (wireName(member.name(), member.javaName()).equals(wireName)) {
				return member;
			}
		}
		throw new IllegalStateException(composite.javaName() + " has no component for member " + wireName);
	}

	private static String wireName(Annotated.Member member) {
		return switch (member) {
			case Annotated.Type type -> wireName(type.name(), type.javaName());
			case Annotated.Ref ref -> wireName(ref.name(), ref.javaName());
			case Annotated.Enum enumeration -> wireName(enumeration.name(), enumeration.javaName());
			case Annotated.Set set -> wireName(set.name(), set.javaName());
			case Annotated.Composite composite -> wireName(composite.name(), composite.javaName());
		};
	}

	private static String wireName(String name, String javaName) {
		return name.isEmpty() ? javaName : name;
	}

	private static Annotated.ValidValue validValue(Annotated.Enum enumeration, String wireName) {
		for (Annotated.ValidValue value : enumeration.values()) {
			if ((value.name().isEmpty() ? value.javaName() : value.name()).equals(wireName)) {
				return value;
			}
		}
		throw new IllegalStateException(enumeration.javaName() + " has no value " + wireName);
	}

	private static Annotated.Choice choice(Annotated.Set set, String wireName) {
		for (Annotated.Choice choice : set.choices()) {
			if ((choice.name().isEmpty() ? choice.javaName() : choice.name()).equals(wireName)) {
				return choice;
			}
		}
		throw new IllegalStateException(set.javaName() + " has no choice " + wireName);
	}

	private static String wireName(Annotated.Field field) {
		return field.name().isEmpty() ? field.javaName() : field.name();
	}
}
