package net.concini.sbebuddy.generator;

/**
 * The text of a message's reader: the class and its control, the methods that
 * arrive at each stage, and the steps between them. {@link ReaderWriter} fills
 * them from a {@link FlyweightModel}; the stages themselves are in
 * {@link ReaderStageTemplates}.
 */
final class ReaderTemplates {

	private ReaderTemplates() {
	}

	static final Template READER = Template.of(
			"""
					package {flyweights};

					/**
					 * The message {@code {messageName}} as the sequence of its stages over sbe-tool's
					 * {@code {message}Decoder}: the root block, then each group's header and entries
					 * and each var-data, in wire order. Generated by sbe-buddy from the schema of
					 * this package; do not edit.
					 */
					@javax.annotation.processing.Generated("net.concini.sbebuddy")
					public final class {reader} implements Iterable<{reader}.Stage>, java.util.Iterator<{reader}.Stage> {

						/** A stage of {@code {messageName}}, in the order they come. */
						public sealed interface Stage extends net.concini.sbebuddy.Stage permits {permits} {
						}

						/** Where the reader is, in wire order: a stage is open while this lies in its range. */
						private enum At {
							{positions}
						}

						private final {flyweights}.{headerClass}Decoder header = new {flyweights}.{headerClass}Decoder();
						private final {flyweights}.{message}Decoder decoder = new {flyweights}.{message}Decoder();
						private final {flyweights}.{message}Decoder measure = new {flyweights}.{message}Decoder();
						private final RootBlock rootBlockStage = new RootBlock();
						{fields}
						private At at = At.BEFORE_ROOT_BLOCK;

						/**
						 * Reads the header at the offset and stands before the root block; another
						 * template is sbe-tool's {@link IllegalStateException}.
						 */
						public {reader} wrap(org.agrona.DirectBuffer buffer, int offset) {
							decoder.wrapAndApplyHeader(buffer, offset, header);
							at = At.BEFORE_ROOT_BLOCK;
							return this;
						}

						/** Back before the root block of the message wrapped. */
						public {reader} rewind() {
							decoder.sbeRewind();
							at = At.BEFORE_ROOT_BLOCK;
							return this;
						}

						/** The header as read, for its own members. */
						public {flyweights}.{headerClass}Decoder header() {
							return header;
						}

						public int actingVersion() {
							return decoder.actingVersion();
						}

						/**
						 * The bytes of the whole message, header included, at any point. Once no stage
						 * is left the limit is at its end; before that a second decoder walks the
						 * message, so the group decoders in use are not disturbed.
						 */
						public int decodedLength() {
							if (!hasNext()) {
								return {flyweights}.{headerClass}Decoder.ENCODED_LENGTH + decoder.encodedLength();
							}
							return {flyweights}.{headerClass}Decoder.ENCODED_LENGTH
									+ measure.wrap(decoder.buffer(), decoder.offset(), header.blockLength(), header.version()).sbeDecodedLength();
						}

						@Override
						public java.util.Iterator<Stage> iterator() {
							return this;
						}

						/** Whether a stage follows; reads nothing and moves nothing. */
						@Override
						public boolean hasNext() {
							return switch (at) {
								{hasNextCases}
							};
						}

						/** The next stage; what the current one left unread is passed over. */
						@Override
						public Stage next() {
							return switch (at) {
								{nextCases}
							};
						}

						private Stage openRootBlock() {
							at = At.ROOT_BLOCK;
							return rootBlockStage;
						}
						{methods}

						private Stage end() {
							at = At.END;
							throw new java.util.NoSuchElementException();
						}

						private void open(At first, At last, String stage) {
							if (at.compareTo(first) < 0 || at.compareTo(last) > 0) {
								throw new IllegalStateException(stage + " is not open");
							}
						}

						private void current(At expected, String stage) {
							if (at != expected) {
								throw new IllegalStateException(stage + " is not the current stage");
							}
						}

						{stages}
					}
					"""
	);

	static final Template POSITION = Template.of("{name},");

	static final Template CASE = Template.of("case {name} -> {step};");

	static final Template GROUP_FIELDS = Template.of("""
			private final {name} {property}Stage = new {name}();
			private final {entry} {property}EntryStage = new {entry}();
			private {decoder} {property}Decoder;
			private int {property}Index;""");

	static final Template DATA_FIELDS = Template.of("""
			private final {name} {property}Stage = new {name}();
			private int {property}Start;
			private int {property}Length;""");

	/**
	 * A group arrives with its header, from the flyweight of the block holding it;
	 * its entries are counted here, the group decoder keeping its index private.
	 */
	static final Template GROUP_METHODS = Template.of("""

			private Stage open{name}() {
				{property}Decoder = {owner}.{property}();
				{property}Index = -1;
				at = At.{position};
				return {property}Stage;
			}

			private Stage next{entry}() {
				{property}Decoder.next();
				{property}Index++;
				at = At.{entryPosition};
				return {property}EntryStage;
			}

			/** Past an entry of {@code {path}}, or its header: the next entry, else what follows the group. */
			private Stage rest{name}() {
				return {property}Decoder.hasNext() ? next{entry}() : {following};
			}

			private boolean hasRest{name}() {
				return {hasRest};
			}""");

	/** Var-data is passed over on arrival, where it lies kept for reading. */
	static final Template DATA_METHODS = Template.of("""

			private Stage open{name}() {
				{property}Start = decoder.limit();
				{property}Length = {owner}.skip{bulk}();
				at = At.{position};
				return {property}Stage;
			}""");

	// ---- the steps: what next() does, and what hasNext() asks

	static final Template CALL = Template.of("{method}()");

	static final Template GROUP_DECODER = Template.of("{property}Decoder");

	static final Template HAS_NEXT_ENTRY = Template.of("{property}Decoder.hasNext()");

	static final Template ARRIVE_SINCE = Template.of("{present} ? {method}() : {otherwise}");

	static final Template PRESENT = Template.of("decoder.actingVersion() >= {sinceVersion}");

	static final Template OR = Template.of("{left} || {right}");

	static final Template END_CALL = Template.of("end()");

	static final Template TRUE = Template.of("true");

	static final Template FALSE = Template.of("false");
}
