package net.concini.sbebuddy.generator;

/**
 * The text of the sub-chains a writer's step opens: a composite's, every member
 * in wire order and the last returning the caller's next stage {@code N}, and a
 * set's, its choices then {@code end()}. One instance per site, wrapped by the
 * step that hands it out. {@link WriterWriter} fills them; their methods are
 * {@link WriterStepTemplates}'.
 */
final class SubWriterTemplates {

	private SubWriterTemplates() {
	}

	/** A composite whose members after the first are stages of their own. */
	static final Template COMPOSITE = Template.of(
			"""
					package {flyweights};

					/**
					 * The composite {@code {compositeName}} as a step of a writer's chain: every member
					 * but the constants, in wire order, over sbe-tool's {@code {encoder}}, the last
					 * handing back the stage {@code N} the chain continues with. Generated by sbe-buddy
					 * from the schema of this package; do not edit.
					 */
					@javax.annotation.processing.Generated("net.concini.sbebuddy")
					public final class {writer}<N> {

						{stages}

						private final Chain chain = new Chain();
						{sites}
						private {encoder} encoder;
						private N next;

						{writer}<N> wrap({encoder} encoder, N next) {
							this.encoder = encoder;
							this.next = next;
							return this;
						}
						{methods}

						private final class Chain implements {chain} {
							{chainMethods}
						}
					}
					"""
	);

	/** A composite of one member, which hands back the caller's stage itself. */
	static final Template SHORT_COMPOSITE = Template.of(
			"""
					package {flyweights};

					/**
					 * The composite {@code {compositeName}} as a step of a writer's chain: its one member
					 * that is not a constant, over sbe-tool's {@code {encoder}}, handing back the stage
					 * {@code N} the chain continues with. Generated by sbe-buddy from the schema of this
					 * package; do not edit.
					 */
					@javax.annotation.processing.Generated("net.concini.sbebuddy")
					public final class {writer}<N> {
						{sites}
						private {encoder} encoder;
						private N next;

						{writer}<N> wrap({encoder} encoder, N next) {
							this.encoder = encoder;
							this.next = next;
							return this;
						}
						{methods}
					}
					"""
	);

	static final Template STAGE = Template.of("""
			{javadoc}
			public interface {name}<N> {
				{methods}
			}""");

	static final Template SET = Template.of(
			"""
					package {flyweights};

					/**
					 * The set {@code {setName}} as a step of a writer's chain: its choices over sbe-tool's
					 * {@code {encoder}}, in any order, then {@code end()} back to the stage {@code N} the
					 * chain continues with. Generated by sbe-buddy from the schema of this package; do not
					 * edit.
					 */
					@javax.annotation.processing.Generated("net.concini.sbebuddy")
					public final class {writer}<N> {

						private {encoder} set;
						private N next;

						{writer}<N> wrap({encoder} set, N next) {
							this.set = set;
							this.next = next;
							return this;
						}
						{choices}

						public N end() {
							if (next == null) {
								throw new IllegalStateException("{writer} has ended");
							}
							N following = next;
							next = null;
							return following;
						}
					}
					"""
	);

	static final Template CHOICE = Template.of("""

			public {writer}<N> {choice}(boolean value) {
				if (next == null) {
					throw new IllegalStateException("{writer} has ended");
				}
				set.{choice}(value);
				return this;
			}""");
}
