package net.concini.sbebuddy.generator;

/**
 * The text of a union's codec: one case per member, delegating to the member's
 * codec. {@link UnionWriter} fills them from its model; a template's names in
 * braces are the only values it takes.
 */
final class UnionTemplates {

	private UnionTemplates() {
	}

	static final Template UNION_CODEC = Template.of(
			"""
					package {packageName};

					/** Generated by sbe-buddy from the schema of this package; do not edit. */
					@javax.annotation.processing.Generated("net.concini.sbebuddy")
					public final class {codec} implements net.concini.sbebuddy.Codec<{union}, {headerRecord}> {

						private final {flyweights}.{headerClass}Decoder headerDecoder = new {flyweights}.{headerClass}Decoder();
						{fields}
						private net.concini.sbebuddy.Codec<?, ?> lastDecoder = {first};

						public {codec}() {
						}

						@Override
						public int encodedLength({union} value) {
							if (value == null) {
								throw new IllegalArgumentException("value is required");
							}
							return switch (value) {
								{encodedLengths}
							};
						}

						@Override
						public int encode({union} value, org.agrona.MutableDirectBuffer buffer, int offset) {
							if (value == null) {
								throw new IllegalArgumentException("value is required");
							}
							return switch (value) {
								{encodes}
							};
						}

						@Override
						public int encode({union} value, {headerRecord} header, org.agrona.MutableDirectBuffer buffer, int offset) {
							if (value == null) {
								throw new IllegalArgumentException("value is required");
							}
							return switch (value) {
								{headerEncodes}
							};
						}

						@Override
						public {union} decode(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							if (headerDecoder.schemaId() != {firstDecoder}.SCHEMA_ID) {
								throw notOurs();
							}
							return switch (headerDecoder.templateId()) {
								{decodes}
								default -> throw notOurs();
							};
						}

						@Override
						public boolean canDecode(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							return switch (headerDecoder.templateId()) {
								{canDecodes}
								default -> false;
							};
						}

						@Override
						public {headerRecord} decodeHeader(org.agrona.DirectBuffer buffer, int offset) {
							return {first}.decodeHeader(buffer, offset);
						}

						@Override
						public int lastDecodedLength() {
							return lastDecoder.lastDecodedLength();
						}

						@Override
						public int decodedLength(org.agrona.DirectBuffer buffer, int offset) {
							headerDecoder.wrap(buffer, offset);
							if (headerDecoder.schemaId() != {firstDecoder}.SCHEMA_ID) {
								throw notOurs();
							}
							return switch (headerDecoder.templateId()) {
								{decodedLengths}
								default -> throw notOurs();
							};
						}

						private IllegalArgumentException notOurs() {
							return new IllegalArgumentException("not a {unionName}: schemaId " + headerDecoder.schemaId() + ", templateId "
									+ headerDecoder.templateId() + "; its templates are " + {templateIds});
						}
					}
					"""
	);

	static final Template UNION_CODEC_FIELD = Template.of("private final {codec} {field} = new {codec}();");

	static final Template UNION_ENCODED_LENGTH_CASE = Template
			.of("case {record} member -> {field}.encodedLength(member);");

	static final Template UNION_ENCODE_CASE = Template
			.of("case {record} member -> {field}.encode(member, buffer, offset);");

	static final Template UNION_HEADER_ENCODE_CASE = Template
			.of("case {record} member -> {field}.encode(member, header, buffer, offset);");

	/** The decoding codec is remembered, so {@code lastDecodedLength} asks it. */
	static final Template UNION_DECODE_CASE = Template.of("""
			case {decoder}.TEMPLATE_ID -> {
				lastDecoder = {field};
				yield {field}.decode(buffer, offset);
			}""");

	static final Template UNION_DECODED_LENGTH_CASE = Template
			.of("case {decoder}.TEMPLATE_ID -> {field}.decodedLength(buffer, offset);");

	static final Template UNION_CAN_DECODE_CASE = Template
			.of("case {decoder}.TEMPLATE_ID -> {field}.canDecode(buffer, offset);");

	static final Template UNION_TEMPLATE_ID = Template.of("{decoder}.TEMPLATE_ID");
}
