package net.concini.sbebuddy.generator;

/**
 * The text of a message's writer: the class, its stages as interfaces, the
 * objects behind them, and the null values a block is filled with when it
 * opens. {@link WriterWriter} fills them from a {@link WriterModel}; the
 * methods of the objects are in {@link WriterStepTemplates}.
 */
final class WriterTemplates {

	private WriterTemplates() {
	}

	static final Template WRITER = Template.of(
			"""
					package {packageName};

					/**
					 * The message {@code {messageName}} written over sbe-tool's {@code {message}Encoder} as
					 * a chain of stages: every required field, group and var-data in wire order, each
					 * stage offering only the next, and {@code length()} once the message is complete.
					 * Generated by sbe-buddy from the schema of this package; do not edit.
					 */
					@javax.annotation.processing.Generated("net.concini.sbebuddy")
					public final class {writer} {

						{stages}

						/** Where the writer is, in wire order: a stage's methods want it at the stage. */
						private enum At {
							{positions}
						}

						{contexts}
						private final {flyweights}.{headerClass}Encoder header = new {flyweights}.{headerClass}Encoder();
						private final {flyweights}.{message}Encoder encoder = new {flyweights}.{message}Encoder();
						{bindings}
						{fields}
						private At at = At.BEFORE_ROOT_BLOCK;

						/**
						 * Writes the header at the offset, its own members as their null values, fills
						 * the root block with its null values and stands at its first step.
						 */
						public {first} wrap(org.agrona.MutableDirectBuffer buffer, int offset) {
							encoder.wrapAndApplyHeader(buffer, offset, header);
							nullHeader(header);
							nulls(encoder);
							at = At.ROOT_BLOCK;
							return rootBlockStage;
						}

						/** The header as written, for its own members. */
						public {flyweights}.{headerClass}Encoder header() {
							return header;
						}

						private void current(At first, At last, String stage) {
							if (at.compareTo(first) < 0 || at.compareTo(last) > 0) {
								throw new IllegalStateException(stage + " is not the current stage");
							}
						}

						private static void nullHeader({flyweights}.{headerClass}Encoder encoder) {
							{header}
						}
						{nulls}

						{implementations}
						{helpers}
					}
					"""
	);

	static final Template STAGE = Template.of("""
			{javadoc}
			public interface {name} {
				{methods}
			}""");

	static final Template EXTENDING_STAGE = Template.of("""
			{javadoc}
			public interface {name} extends {parents} {
				{methods}
			}""");

	// ---- what each stage is, by its kind

	static final Template FIELD_DOC = Template
			.of("/** Before the required field {@code {subject}}: its step is the one way on. */");

	static final Template ROOT_BLOCK_DOC = Template.of(
			"/** The root block complete: its optional fields, in any order, and what follows it. */"
	);

	static final Template ENTRY_DOC = Template.of(
			"/** An entry of {@code {subject}} complete: its optional fields, in any order, and what follows it. */"
	);

	static final Template GROUP_DOC = Template.of(
			"/** The group {@code {subject}}: {@code entry()} for each entry, then {@code end()}, which settles the count. */"
	);

	static final Template AFTER_DOC = Template.of("/** Past {@code {subject}}: what follows it. */");

	static final Template BOUND_DOC = Template.of(
			"/** The record's view of {@code {subject}}: each step takes a component as the record holds it, through its binding. */"
	);

	static final Template MEMBER_DOC = Template
			.of("/** Before the member {@code {subject}}: its step is the one way on. */");

	static final Template DECLARATION = Template.of("{returns} {name}({parameters});");

	static final Template PARAMETER = Template.of("{type} {name}");

	static final Template POSITION = Template.of("{name},");

	static final Template OBJECT_FIELD = Template.of("private final {name} {field} = new {name}();");

	static final Template ENCODER_FIELD = Template.of("private {type} {name};");

	static final Template SITE_FIELD = Template.of("private final {writer}<{next}> {name} = new {writer}<>();");

	/**
	 * Every field or member the class of {@code encoder} holds, as its null value.
	 */
	static final Template NULLS = Template.of("""

			private static void nulls({encoder} encoder) {
				{writes}
			}""");

	static final Template IMPLEMENTATION = Template.of("""
			private final class {name} implements {stages} {
				{sites}
				{methods}
			}""");
}
