package corpus.composites.sbe;

/**
 * The composite {@code Quote} as a step of a writer's chain: every member
 * but the constants, in wire order, over sbe-tool's {@code corpus.composites.sbe.QuoteEncoder}, the last
 * handing back the stage {@code N} the chain continues with. Generated by sbe-buddy
 * from the schema of this package; do not edit.
 */
@javax.annotation.processing.Generated("net.concini.sbebuddy")
public final class QuoteWriter<N> {

	/** Before the member {@code Quote.ask}: its step is the one way on. */
	public interface Ask<N> {
		corpus.composites.sbe.DecimalWriter<Side<N>> ask();
	}

	/** Before the member {@code Quote.side}: its step is the one way on. */
	public interface Side<N> {
		Flags<N> side(corpus.composites.sbe.Side value);
	}

	/** Before the member {@code Quote.flags}: its step is the one way on. */
	public interface Flags<N> {
		corpus.composites.sbe.FlagsWriter<Stamp<N>> flags();
	}

	/** Before the member {@code Quote.stamp}: its step is the one way on. */
	public interface Stamp<N> {
		corpus.composites.sbe.StampWriter<N> stamp();
	}

	private final Chain chain = new Chain();
	private final corpus.composites.sbe.DecimalWriter<Ask<N>> bidWriter = new corpus.composites.sbe.DecimalWriter<>();
	private final corpus.composites.sbe.DecimalWriter<Side<N>> askWriter = new corpus.composites.sbe.DecimalWriter<>();
	private final corpus.composites.sbe.FlagsWriter<Stamp<N>> flagsWriter = new corpus.composites.sbe.FlagsWriter<>();
	private final corpus.composites.sbe.StampWriter<N> stampWriter = new corpus.composites.sbe.StampWriter<>();
	private corpus.composites.sbe.QuoteEncoder encoder;
	private N next;

	QuoteWriter<N> wrap(corpus.composites.sbe.QuoteEncoder encoder, N next) {
		this.encoder = encoder;
		this.next = next;
		return this;
	}

	public corpus.composites.sbe.DecimalWriter<Ask<N>> bid() {
		if (next == null) {
			throw new IllegalStateException("QuoteWriter has ended");
		}
		return bidWriter.wrap(encoder.bid(), chain);
	}

	private final class Chain implements Ask<N>, Side<N>, Flags<N>, Stamp<N> {

		@Override
		public corpus.composites.sbe.DecimalWriter<Side<N>> ask() {
			if (next == null) {
				throw new IllegalStateException("QuoteWriter has ended");
			}
			return askWriter.wrap(encoder.ask(), chain);
		}

		@Override
		public Flags<N> side(corpus.composites.sbe.Side value) {
			if (next == null) {
				throw new IllegalStateException("QuoteWriter has ended");
			}
			encoder.side(value);
			return chain;
		}

		@Override
		public corpus.composites.sbe.FlagsWriter<Stamp<N>> flags() {
			if (next == null) {
				throw new IllegalStateException("QuoteWriter has ended");
			}
			return flagsWriter.wrap(encoder.flags(), chain);
		}

		@Override
		public corpus.composites.sbe.StampWriter<N> stamp() {
			if (next == null) {
				throw new IllegalStateException("QuoteWriter has ended");
			}
			N following = next;
			next = null;
			return stampWriter.wrap(encoder.stamp(), following);
		}
	}
}
