package corpus.groups.sbe;

/**
 * The message {@code Groups} written over sbe-tool's {@code GroupsEncoder} as
 * a chain of stages: every required field, group and var-data in wire order, each
 * stage offering only the next, and {@code length()} once the message is complete.
 * Generated by sbe-buddy from the schema of this package; do not edit.
 */
@javax.annotation.processing.Generated("net.concini.sbebuddy")
public final class GroupsWriter {

	/** Before the required field {@code orderId}: its step is the one way on. */
	public interface RootBlockOrderId {
		RootBlock orderId(long value);
	}

	/** The root block complete: its optional fields, in any order, and what follows it. */
	public interface RootBlock {
		Legs legs();
	}

	/** The group {@code legs}: {@code entry()} for each entry, then {@code end()}, which settles the count. */
	public interface Legs {
		LegsEntryLegId entry();
		AfterLegs end();
	}

	/** Before the required field {@code legs.legId}: its step is the one way on. */
	public interface LegsEntryLegId {
		LegsEntryLegRatio legId(int value);
	}

	/** Before the required field {@code legs.legRatio}: its step is the one way on. */
	public interface LegsEntryLegRatio {
		LegsEntry legRatio(short value);
	}

	/** An entry of {@code legs} complete: its optional fields, in any order, and what follows it. */
	public interface LegsEntry {
		Allocations allocations();
	}

	/** The group {@code legs.allocations}: {@code entry()} for each entry, then {@code end()}, which settles the count. */
	public interface Allocations {
		AllocationsEntryAccount entry();
		Legs end();
	}

	/** Before the required field {@code legs.allocations.account}: its step is the one way on. */
	public interface AllocationsEntryAccount {
		AllocationsEntry account(int value);
	}

	/** An entry of {@code legs.allocations} complete: its optional fields, in any order, and what follows it. */
	public interface AllocationsEntry extends Allocations {
		AllocationsEntry share(int value);
	}

	/** Past {@code legs}: what follows it. */
	public interface AfterLegs {
		Fills fills();
	}

	/** The group {@code fills}: {@code entry()} for each entry, then {@code end()}, which settles the count. */
	public interface Fills {
		FillsEntryPrice entry();
		AfterFills end();
	}

	/** Before the required field {@code fills.price}: its step is the one way on. */
	public interface FillsEntryPrice {
		Fills price(long value);
	}

	/** Past {@code fills}: what follows it. */
	public interface AfterFills {
		int length();
	}

	/** Where the writer is, in wire order: a stage's methods want it at the stage. */
	private enum At {
		BEFORE_ROOT_BLOCK,
		ROOT_BLOCK,
		LEGS,
		LEGS_ENTRY,
		ALLOCATIONS,
		ALLOCATIONS_ENTRY,
		AFTER_LEGS,
		FILLS,
		FILLS_ENTRY,
		AFTER_FILLS,
	}

	private final corpus.groups.sbe.MessageHeaderEncoder header = new corpus.groups.sbe.MessageHeaderEncoder();
	private final corpus.groups.sbe.GroupsEncoder encoder = new corpus.groups.sbe.GroupsEncoder();
	private final RootBlockStage rootBlockStage = new RootBlockStage();
	private final LegsStage legsStage = new LegsStage();
	private final LegsEntryStage legsEntryStage = new LegsEntryStage();
	private final AllocationsStage allocationsStage = new AllocationsStage();
	private final AllocationsEntryStage allocationsEntryStage = new AllocationsEntryStage();
	private final FillsStage fillsStage = new FillsStage();
	private final FillsEntryStage fillsEntryStage = new FillsEntryStage();
	private corpus.groups.sbe.GroupsEncoder.LegsEncoder legsEncoder;
	private corpus.groups.sbe.GroupsEncoder.LegsEncoder.AllocationsEncoder allocationsEncoder;
	private corpus.groups.sbe.GroupsEncoder.FillsEncoder fillsEncoder;
	private At at = At.BEFORE_ROOT_BLOCK;

	/**
	 * Writes the header at the offset, its own members as their null values, fills
	 * the root block with its null values and stands at its first step.
	 */
	public RootBlockOrderId wrap(org.agrona.MutableDirectBuffer buffer, int offset) {
		encoder.wrapAndApplyHeader(buffer, offset, header);
		nullHeader(header);
		nulls(encoder);
		at = At.ROOT_BLOCK;
		return rootBlockStage;
	}

	/** The header as written, for its own members. */
	public corpus.groups.sbe.MessageHeaderEncoder header() {
		return header;
	}

	private void current(At first, At last, String stage) {
		if (at.compareTo(first) < 0 || at.compareTo(last) > 0) {
			throw new IllegalStateException(stage + " is not the current stage");
		}
	}

	private static void nullHeader(corpus.groups.sbe.MessageHeaderEncoder encoder) {
	}

	private static void nulls(corpus.groups.sbe.GroupsEncoder encoder) {
		encoder.orderId(corpus.groups.sbe.GroupsEncoder.orderIdNullValue());
	}

	private static void nulls(corpus.groups.sbe.GroupsEncoder.LegsEncoder encoder) {
		encoder.legId(corpus.groups.sbe.GroupsEncoder.LegsEncoder.legIdNullValue());
		encoder.legRatio(corpus.groups.sbe.GroupsEncoder.LegsEncoder.legRatioNullValue());
	}

	private static void nulls(corpus.groups.sbe.GroupsEncoder.LegsEncoder.AllocationsEncoder encoder) {
		encoder.account(corpus.groups.sbe.GroupsEncoder.LegsEncoder.AllocationsEncoder.accountNullValue());
		encoder.share(corpus.groups.sbe.GroupsEncoder.LegsEncoder.AllocationsEncoder.shareNullValue());
	}

	private static void nulls(corpus.groups.sbe.GroupsEncoder.FillsEncoder encoder) {
		encoder.price(corpus.groups.sbe.GroupsEncoder.FillsEncoder.priceNullValue());
	}

	private final class RootBlockStage implements RootBlockOrderId, RootBlock, AfterLegs, AfterFills {

		@Override
		public RootBlock orderId(long value) {
			GroupsWriter.this.current(At.ROOT_BLOCK, At.ROOT_BLOCK, "RootBlock");
			encoder.orderId(value);
			return this;
		}

		@Override
		public Legs legs() {
			GroupsWriter.this.current(At.ROOT_BLOCK, At.ROOT_BLOCK, "RootBlock");
			legsEncoder = encoder.legsCount(corpus.groups.sbe.GroupsEncoder.LegsEncoder.countMaxValue());
			at = At.LEGS;
			return legsStage;
		}

		@Override
		public Fills fills() {
			GroupsWriter.this.current(At.AFTER_LEGS, At.AFTER_LEGS, "AfterLegs");
			fillsEncoder = encoder.fillsCount(corpus.groups.sbe.GroupsEncoder.FillsEncoder.countMaxValue());
			at = At.FILLS;
			return fillsStage;
		}

		@Override
		public int length() {
			GroupsWriter.this.current(At.AFTER_FILLS, At.AFTER_FILLS, "AfterFills");
			return corpus.groups.sbe.MessageHeaderEncoder.ENCODED_LENGTH + encoder.encodedLength();
		}
	}

	private final class LegsStage implements Legs {

		@Override
		public LegsEntryLegId entry() {
			GroupsWriter.this.current(At.LEGS, At.LEGS, "Legs");
			legsEncoder.next();
			GroupsWriter.nulls(legsEncoder);
			at = At.LEGS_ENTRY;
			return legsEntryStage;
		}

		@Override
		public AfterLegs end() {
			GroupsWriter.this.current(At.LEGS, At.LEGS, "Legs");
			legsEncoder.resetCountToIndex();
			at = At.AFTER_LEGS;
			return rootBlockStage;
		}
	}

	private final class LegsEntryStage implements LegsEntryLegId, LegsEntryLegRatio, LegsEntry {

		@Override
		public LegsEntryLegRatio legId(int value) {
			GroupsWriter.this.current(At.LEGS_ENTRY, At.LEGS_ENTRY, "LegsEntry");
			legsEncoder.legId(value);
			return this;
		}

		@Override
		public LegsEntry legRatio(short value) {
			GroupsWriter.this.current(At.LEGS_ENTRY, At.LEGS_ENTRY, "LegsEntry");
			legsEncoder.legRatio(value);
			return this;
		}

		@Override
		public Allocations allocations() {
			GroupsWriter.this.current(At.LEGS_ENTRY, At.LEGS_ENTRY, "LegsEntry");
			allocationsEncoder = legsEncoder.allocationsCount(corpus.groups.sbe.GroupsEncoder.LegsEncoder.AllocationsEncoder.countMaxValue());
			at = At.ALLOCATIONS;
			return allocationsStage;
		}
	}

	private final class AllocationsStage implements Allocations {

		@Override
		public AllocationsEntryAccount entry() {
			GroupsWriter.this.current(At.ALLOCATIONS, At.ALLOCATIONS_ENTRY, "Allocations");
			allocationsEncoder.next();
			GroupsWriter.nulls(allocationsEncoder);
			at = At.ALLOCATIONS_ENTRY;
			return allocationsEntryStage;
		}

		@Override
		public Legs end() {
			GroupsWriter.this.current(At.ALLOCATIONS, At.ALLOCATIONS_ENTRY, "Allocations");
			allocationsEncoder.resetCountToIndex();
			at = At.LEGS;
			return legsStage;
		}
	}

	private final class AllocationsEntryStage implements AllocationsEntryAccount, AllocationsEntry {

		@Override
		public AllocationsEntry account(int value) {
			GroupsWriter.this.current(At.ALLOCATIONS_ENTRY, At.ALLOCATIONS_ENTRY, "AllocationsEntry");
			allocationsEncoder.account(value);
			return this;
		}

		@Override
		public AllocationsEntryAccount entry() {
			return allocationsStage.entry();
		}

		@Override
		public Legs end() {
			return allocationsStage.end();
		}

		@Override
		public AllocationsEntry share(int value) {
			GroupsWriter.this.current(At.ALLOCATIONS_ENTRY, At.ALLOCATIONS_ENTRY, "AllocationsEntry");
			allocationsEncoder.share(value);
			return this;
		}
	}

	private final class FillsStage implements Fills {

		@Override
		public FillsEntryPrice entry() {
			GroupsWriter.this.current(At.FILLS, At.FILLS_ENTRY, "Fills");
			fillsEncoder.next();
			GroupsWriter.nulls(fillsEncoder);
			at = At.FILLS_ENTRY;
			return fillsEntryStage;
		}

		@Override
		public AfterFills end() {
			GroupsWriter.this.current(At.FILLS, At.FILLS_ENTRY, "Fills");
			fillsEncoder.resetCountToIndex();
			at = At.AFTER_FILLS;
			return rootBlockStage;
		}
	}

	private final class FillsEntryStage implements FillsEntryPrice {

		@Override
		public Fills price(long value) {
			GroupsWriter.this.current(At.FILLS_ENTRY, At.FILLS_ENTRY, "FillsEntry");
			fillsEncoder.price(value);
			return fillsStage;
		}
	}
}
