<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 https://maven.apache.org/xsd/maven-4.1.0.xsd">
  <modelVersion>4.1.0</modelVersion>

  <parent>
    <groupId>net.concini</groupId>
    <artifactId>sbe-buddy-parent</artifactId>
  </parent>

  <artifactId>sbe-buddy-generator</artifactId>

  <dependencies>
    <dependency>
      <groupId>net.concini</groupId>
      <artifactId>sbe-buddy-api</artifactId>
    </dependency>
    <dependency>
      <groupId>uk.co.real-logic</groupId>
      <artifactId>sbe-tool</artifactId>
      <version>${sbe-tool.version}</version>
    </dependency>
    <dependency>
      <groupId>org.xmlunit</groupId>
      <artifactId>xmlunit-assertj3</artifactId>
      <version>${xmlunit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <properties>
    <module.name>net.concini.sbebuddy.generator</module.name>
  </properties>
</project>
